### ISSUE TITLE
Recommended structural changes

### ISSUE THREAD

**Issue by kardianos** [shirou/gopsutil#100]
Factor out all the new calls:
    common.GetEnv -> common.GetProc and common.GetSys.
    Call filepath.Join within the GetProc and GetSys calls.
    Currently lots of room for copy and paste errors.

Move common package into "internal" directory. No need to make API promise on that one, correct?

**Comment by shirou** [comment]
Yes, refactoring is required. I agree. and also, add mocking.
However, I have not solid blocks of developing time currently, please be patiant.
Thank you.
