### ISSUE TITLE
Wrong CPUPercent reports

### ISSUE THREAD

**Issue by vkuznet** [shirou/gopsutil#1006]
**Describe the bug**
I found that monitoring of process CPU percent is wrong if I use Go server which runs several goroutines and monitor it use gopsutil `proc.CPUPercent` function. Here is a proof;
```
# on k8s server I have a web server with PID 28
# below I dump usage of CPU using top and proc_mon.go code (see below)
# as can be seen from several attempts the %CPU report numbers are quite different
# I executed side-by-side top and gopsutil code
top -p 28 -n 1 && ./proc_mon -pid 28
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
     28 root      20   0 2884316  57560  28444 S   0.0  0.2   4:11.71 dbs2go
2020/12/07 21:26:06 PID 28, cpu 44.307152107818155

top -p 28 -n 1 && ./proc_mon -pid 28
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
     28 root      20   0 2884316  57792  28444 S 280.0  0.2   4:30.29 dbs2go
2020/12/07 21:26:54 PID 28, cpu 43.751437932120716

top -p 28 -n 1 && ./proc_mon -pid 28
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
     28 root      20   0 2884316  57792  28444 S 293.3  0.2   7:07.27 dbs2go
2020/12/07 21:28:01 PID 28, cpu 62.544830080650456

top -p 28 -n 1 && ./proc_mon -pid 28
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
     28 root      20   0 2958048  57816  28444 S   0.0  0.2   8:33.91 dbs2go
2020/12/07 21:28:35 PID 28, cpu 71.51142184852769

```

**To Reproduce**
```
# proc_mon.go codebase
package main

import (
	"flag"
	"log"

	"github.com/shirou/gopsutil/process"
)

func main() {
	var pid int
	flag.IntVar(&pid, "pid", 0, "pid to watch")
	flag.Parse()
	run(pid)
}

func run(pid int) {
	if proc, err := process.NewProcess(int32(pid)); err == nil {
		if v, e := proc.CPUPercent(); e == nil {
			log.Printf("PID %d, cpu %v\n", pid, v)
		}
	}
}
```

**Expected behavior**
I'm not sure about logic of CPUPercent function but it should match values reported by top. If I run a single process then I see that top and gopsutil code is consistent. When I run Go-based server code which spawn multiple goroutines  then I see very weird numbers reported by gopsutil codebase. All tests above were done on kubernetes cluster running Linux and web server code is provisioned to use 4 cores.

**Environment (please complete the following information):**
 - Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
CentOS Linux 7 (Core)
Linux dbs2go-75cd7bd46-9mlx5 5.4.8-200.fc31.x86_64 #1 SMP Mon Jan 6 16:44:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

and I run pod under root account.

**Additional context**
Code is compiled with go version 1.15.2

**Comment by Lomanic** [comment]
gopsutil is not a port of (h)top or similar but psutil. Did you compare the values between gopsutil and psutil?

See https://github.com/shirou/gopsutil/issues/886#issuecomment-636357520, #690, #732, #765.

**Comment by vkuznet** [comment]
I'm not sure I understand the logic of statement that we only mimic psutil. I think you just need to clarify what exactly CPUPercent means and how it is calculated. All aforementioned tickets points out to inconsistency between system tools any user is familiar with and CPUPercent values.

**Comment by cw4t** [comment]
I have also meet this Prob, and I've compared the value with psutil's result, They arn't same:
`	p, _ := process.NewProcess(4815)
	fmt.Println(p.Name())
	pc, err := p.CPUPercent()
	pm, err := p.MemoryPercent()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(pc, pm)`

python's Version:
`import psutil

if __name__ == '__main__':
   p = psutil.Process(4815)
   print(p.cpu_percent(interval=2), p.memory_percent())`

**THE Result of Python:**
1.0 1.1357217169631044
0.5 1.1357217169631044
0.0 1.1357217169631044

**The Result of gopsutil:**
0.3682570277352589 1.1357217
0.3682569746702613 1.1357217
0.3682570894211848 1.1357217

**Comment by feng-crazy** [comment]
I had the same problem

**Comment by feng-crazy** [comment]
The CPU occupancy rate is calculated according to the time from when the process is started to the moment when the interface is called.

**Comment by vkuznet** [comment]
I can confirm that using `process.Percent` I can reach similar behavior as top. Here is example of working code which you can use to test your favorite process:
```
package main

import (
	"flag"
	"log"
	"time"

	"github.com/shirou/gopsutil/process"
)

func main() {
	var pid int
	flag.IntVar(&pid, "pid", 0, "pid to watch")
	flag.Parse()
	run(pid)
}

func run(pid int) {
	for {
		if proc, err := process.NewProcess(int32(pid)); err == nil {
			pr, err := proc.Percent(time.Duration(1 * time.Second))
			if err == nil {
				log.Printf("PID %d, proc percent %v\n", pid, pr)
			}
		}
	}
}
```
I run this code along with top and visually observer quite similar reporting values for given pid. I think the difference is really now depends on duration interval, but using 1 second is close enough to top output.

Thanks for suggestion, closing the ticket.
