### ISSUE TITLE
gopsutil/cpu cause debug(go-delve) exception on apple silicon

### ISSUE THREAD

**Issue by Cluas** [shirou/gopsutil#1021]
**Describe the bug**
gopsutil/cpu cause debug(go-delve) exception

see screenshot

**To Reproduce**
```go
package main

import (
	"fmt"

	"github.com/shirou/gopsutil/cpu"
)

func main() {
	a:=1
	fmt.Println(a)
	v, _ = cpu.Info()
	// convert to JSON. String() is also implemented
	fmt.Println(v)
}
```

**Expected behavior**

see screenshot

**Environment (please complete the following information):**
Mac OS arm64

**Additional context**
![image](https://user-images.githubusercontent.com/10056928/104810741-b0560000-5831-11eb-9f46-8c74d6688429.png)
![image](https://user-images.githubusercontent.com/10056928/104810744-b4821d80-5831-11eb-8926-6a7d40415f8f.png)

**Comment by shirou** [comment]
duplicate #1000
