### ISSUE TITLE
Windows Load only work with English system language

### ISSUE THREAD

**Issue by jabdr** [shirou/gopsutil#1026]
**Describe the bug**
Currently the implementation uses PdhAddCounter. The counters on windows are system language specific. To use the counters on a windows with german or french requires either a translated counter from it's id or the use of PdhAddEnglishCounterW.

**To Reproduce**
Run it on any windows system with system (installation) language != english
```go
l, err := load.AvgWithContext(ctx)

if err != nil {
return nil, err
}
```

**Expected behavior**
The load avg

**Environment (please complete the following information):**
 - [X] Windows: any

**Additional context**

**Comment by shirou** [comment]
I have a non-English(Japanese) Windows 10. But there are no error on my PC. Could you show me the error? (But `PdhAddEnglishCounterW` seems better to use, thank you!)

**Comment by jabdr** [comment]
Yes, sometimes on some systems with some counters it also works with PdhAddCounterW. I have no clue why...
On my windows machine the counters have german names and it only works with PdhAddEnglishCounterW:
```
> (Get-Counter -ListSet System).Counter
\System\Lesevorgänge/s
\System\Schreibvorgänge/s
\System\Dateisteuervorgänge/s
\System\Bytes gelesen/s
\System\Bytes geschrieben/s
\System\Dateisteuerbytes/s
\System\Kontextwechsel/s
\System\Systemaufrufe/s
\System\Dateivorgänge/s
\System\Systembetriebszeit
\System\Prozessor-Warteschlangenlänge
\System\Prozesse
\System\Threads
\System\Ausrichtungskorrekturen/s
\System\Ausnahmeverteilungen/s
\System\Gleitkommaemulationen/s
\System\Max. verwendete Registrierungsgröße (%)
```

I don't have the actual error message right now because I am not at work.

**Comment by shirou** [comment]
`(Get-Counter -ListSet System).Counter` returns English counter name on my PC. But as you said, there is some other point. Thank you so much!
