### ISSUE TITLE
gopsutil contains some GPL-licensed code

### ISSUE THREAD

**Issue by jihoon-seo** [shirou/gopsutil#1031]
- Previous identical issue: #518 

> gopsutil is licensed under BSD 3-clause license https://github.com/shirou/gopsutil/blob/master/LICENSE
> 
> However, its code contains two files which are licensed under GPL and are most probably just copied from some project:

https://github.com/shirou/gopsutil/blob/master/v3/cpu/_smc.c
https://github.com/shirou/gopsutil/blob/master/v3/cpu/_smc.h

PTAL @shirou !

**Comment by shirou** [comment]
I'm so sorry. Those two files are accidentally added from my local when I create v3 directory. I merged #1032.

Those two files are not used from gopsutil code. So I think library users are not affected.

Thank you for letting us know.
