### ISSUE TITLE
cpu: CPUInfo needs to clarify or correct topology.

### ISSUE THREAD

**Issue by kardianos** [shirou/gopsutil#104]
nomad currently uses cpu.CPUInfo to count cores. It takes the total CPUInfo struct count and adds each core count in each cpu to get the total number of cores. For example my six core machine will result in reporting 36 total cores when counted this way.

Probably Processor / Cores need better topology reporting on all architectures. For example under "/sys/.../cpuX/topology/ it can report which cores are in each processor.

**Comment by shirou** [comment]
On my understanding, what you want to say is,
- ARM processer doesn't have `cpu cores` in /proc/cpuinfo. so we use `/sys/.../cpuX/topology` to get core nums

If so, we can extend `finshCPUInfo()` to get core nums by using `topology/core_id` (or else). correct?

**Comment by kardianos** [comment]
No. Well, kinda.

On my amd64 I have 1 socket, 6 processor cpu. cpu.CPUInfo() will report 6 array items, each item has "cores" = 6. Right now nomad does something like this:
```
func totalCoreCount() int {
    total := 0
    for c, _ := range cpu.CPUInfo() {
        total += cpu.Cores
    }
    return total
}
```

The above function will report 36 cores on my 6 core amd64 cpu! Now either nomad is interpreting the struct incorrectly or CPUInfo doesn't have a strict enough semantic meaning to all the fields.

**Comment by kardianos** [comment]
@shirou My recommendation is to either:
1) hardcode the "cores" property to 1; currently each array item is a core.
or 2) Change it so each returned array item is a Processor / Socket, with the correct core count.

If you choose I could send a PR.

**Comment by shirou** [comment]
@kardianos Thank you for the suggestion. I don't want to change API, so currently I want to choose 1), `hardcode property to 1`. I will appliciate if you send a PR.
Since FreeBSD can not get multi CPU information yet, I want to restructure CPU information. 

and, if you want to get just a total count of cores, you'd better to use `runtime.NumCPU`, I think.

**Comment by kardianos** [comment]
@shirou Neither one would change the API. Choosing (1) would keep the same number of array elements [6] on my single socket 6-core machine, and hardcode "1" core for each. Choosing (2) would return 1 array element on my single socket 6-core machine and in that element have "6" for cores.

I'll send one or two PR, then you can merge what you would like.

**Comment by shirou** [comment]
If my understanding is correct, (2) will change the meaning what the struct is. Not API, sorry.
So, I prefer (1).

**Comment by kardianos** [comment]
@shirou As a side note, `runtime.NumCPU` will report only the number of hardware threads the running go process is allowed to use, not necessarily the total count.
