### ISSUE TITLE
process.Name returns an empty string in Apple Silicon

### ISSUE THREAD

**Issue by rberrelleza** [shirou/gopsutil#1043]
**Describe the bug**
Calling `process.Name()` returns an empty string in Apple Silicon. This happens with any process.

**To Reproduce**
```go
package main

import (
	"log"
	"os"

	"github.com/shirou/gopsutil/v3/process"
)

func main() {
	pid := os.Getpid()
	proc, err := process.NewProcess(int32(pid))
	if err != nil {
		log.Fatalf("Could not create process %d, %s", pid, err)
	}

	log.Println(proc.Pid)
	name, err := proc.Name()
	if err != nil {
		log.Fatalln("Could not read process name,", err)
	}

	if name == "" {
		log.Fatalln("Could not parse process name")
	}
}
```

**Expected behavior**
`process.Name()` returns an empty string. 

**Environment (please complete the following information):**
 - [ ] Windows: [paste the result of `ver`]
 - [ ] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
 - [x] Mac OS: [paste the result of `sw_vers` and `uname -a`
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

ProductName:	macOS
ProductVersion:	11.2
BuildVersion:	20D64

Darwin ramiros-mini.lan 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64

**Additional context**
The same reproduces in `github.com/shirou/gopsutil/v3/process` and `github.com/shirou/gopsutil/process`

**Comment by rberrelleza** [comment]
In case it helps, https://github.com/mitchellh/go-ps/blob/master/process_darwin.go#L45 works fine on my M1.

**Comment by shirou** [comment]
Finally my friend run this PR. but from his environment, he can not reproduce this.

**Comment by shirou** [comment]
Also I can not reproduce this.
```
ProductName:    macOS
ProductVersion: 12.0.1
BuildVersion:   21A559
```

Feel free to reopen if you get more concrete condition. Thank you for reporting.
