### ISSUE TITLE
process on xp use windows api GetExitCodeProcess issue

### ISSUE THREAD

**Issue by xiaobingcaicai** [shirou/gopsutil#1044]
**Describe the bug**
process_windows.go use windows api GetExitCodeProcess,but the param handle has not correct value
it use only ROCESS_QUERY_LIMITED_INFORMATION 
the windows suggest:
```
Parameters
hProcess

A handle to the process.

The handle must have the PROCESS_QUERY_INFORMATION or PROCESS_QUERY_LIMITED_INFORMATION access right. For more information, see Process Security and Access Rights.

Windows Server 2003 and Windows XP:  The handle must have the PROCESS_QUERY_INFORMATION access right.
```
so i suggest use the param 
i dont know if this will make other error?
```
PROCESS_QUERY_LIMITED_INFORMATION | PROCESS_QUERY_INFORMATION 
```

**Comment by shirou** [comment]
From [Go 1.11 which is released 2018, Windows 7 or later is required](https://golang.org/doc/go1.11#ports). So gopsutil also does not support WindowsXP.

**Comment by Lomanic** [comment]
Duplicate of #714.
