### ISSUE TITLE
Freebsd(jail): process.NewProcess doesnt work if no procfs mounted

### ISSUE THREAD

**Issue by stiray** [shirou/gopsutil#1049]
**Describe the bug**
Important, this is within jail. I don't have freshly installed FreeBSD to check what is situation on fresh install.

Within jails procfs is not mounted by default, but /proc exists. 

Due to this, process.NewProcess(pid) doesnt work.

The issue is handling within process_posix.go

`func PidExistsWithContext(ctx context.Context, pid int32) (bool, error)`

`if _, err := os.Stat(common.HostProc()); err == nil { //Means that proc filesystem exist`

The issue is that HostProc returns /proc by default, and the directory is really there but if procfs is not in use, it is just empty directory. When stat checks for /proc it is found and presumes procfs is there. 

Further down the code it checks if process is within the /proc direcectory and always fails.
 
`_, err := os.Stat(common.HostProc(strconv.Itoa(int(pid))))`

Even if you are having handling for systems without procfs mounted, it is never called.

**To Reproduce**
```go
    _, err := process.NewProcess(int32(os.Getpid()))
```

**Expected behavior**
The check for procfs is inadequate, fast fix would be to instead rather check if /proc is empty while the ultimate solution would be to actually check if procfs is mounted. Workaround would be to mount procfs but it would be nice if this wouldnt be a requirement.

**Environment (please complete the following information):**
 - [x] FreeBSD: [
FreeBSD build 12.2-RELEASE FreeBSD 12.2-RELEASE r366954 GENERIC  amd64
12.2-RELEASE-p3

**Additional context**
No cross compiling.

**Comment by Lomanic** [comment]
Consequence of this change https://github.com/shirou/gopsutil/pull/821

I'm surprised you have a `/proc` dir on freebsd, but one can indeed mount a procfs on freebsd. https://docs.freebsd.org/en/articles/linux-users/procfs.html https://man.freebsd.org/procfs/

@stiray could you test #1051 in your jail?

**Comment by shirou** [comment]
I can confirm it works on my PC. but if @stiray can not work on your jail, please let us know. Thank you!
