### ISSUE TITLE
CPU voltage reporting?

### ISSUE THREAD

**Issue by stevekm** [shirou/gopsutil#1055]
I was looking through the documentation for this library and did not see any mention of CPU voltage. Am I missing something?

For example, when I run `lm-sensors`, I can see voltages;

```
$ sensors
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:            N/A

k10temp-pci-00c3
Adapter: PCI adapter
Vcore:         1.14 V
Vsoc:          1.09 V
Tctl:         +58.8°C
Tdie:         +58.8°C
Tccd1:        +60.5°C
Tccd2:        +56.8°C
Icore:        28.00 A
Isoc:          9.00 A
```

Are these available from `gopsutil`?

**Comment by shirou** [comment]
Currently no and no plan to implement. It is better to use other library to get such a hardware related information.
