### ISSUE TITLE
Plan to stop v2, target is 2021-11-30

### ISSUE THREAD

**Issue by shirou** [shirou/gopsutil#1078]
**Is your feature request related to a problem? Please describe.**

This is a feature request.

**Describe the solution you'd like**

Currently gopsutil have two versions, `v2` and `v3`. But it is difficult to support both versions from our limited resource. I want to terminate v2 and move v3 version to root directory.

My plan is 6 months later, end of November of this year, this means `2021-11-30`. After that day, we will not have v2 any more. Please migrate your code from v2 to v3 until that day.

**Plan**

- [ ] Oct.: check difference between v2 and v3. If there is something which v3 doesn't have, open a PR.
- [ ] Beginning of Nov.: Open a PR which move v3 to root, and check feasibility.
- [ ] End of Nov.: merge the PR.

**Comment by Lomanic** [comment]
Do you plan on removing v2 files or just freeze the sub-packages? I fear that that removing files would break a lot of things downstream.

Otherwise, I agree with the idea of freezing v2.

**Comment by shirou** [comment]
I am planning remove v2 files and move v3 to top. I understand it breaks a lot, but it's something we are going to have to do at some point.

**Comment by Lomanic** [comment]
Closing with #1174 merged
