### ISSUE TITLE
IsRunning unreliable on OSX

### ISSUE THREAD

**Issue by travisgroth** [shirou/gopsutil#1092]
**Describe the bug**
We're using `IsRunningWithContext` to detect if a child process has died in a ticker driven loop.  On a regular but random basis, `IsRunning` returns false, even though the exact same child process is still running.

After doing some digging, it seems the creation time originally stored in the `Process` can differ slightly from the new instance created during the `IsRunning` check.  

So far we've only seen instances of this on intel based OSX, but it happens both on the native OS as well as a docker (thus, a Linux VM).

Here's the code we used to track down the issue - largely a copy/paste of `IsRunning`:

```go
	for {
		// wait for the next tick
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
		}

		origCtime, err := proc.CreateTimeWithContext(ctx)
		if err != nil {
			log.Error(ctx).Err(err).Msg("envoy: failed to get original creation time")
		}
		newProc, err := process.NewProcessWithContext(ctx, pid)
		if err != nil {
			log.Error(ctx).Err(err).Msg("envoy: failed to get new process handle")
		}
		newCtime, err := newProc.CreateTimeWithContext(ctx)
		if err != nil {
			log.Error(ctx).Err(err).Msg("envoy: failed to get new creation time")
		}

		running := origCtime == newCtime

                 if !running {

			log.Fatal().Err(err).
				Int64("original-creation-time", origCtime).
				Int64("new-creation-time", newCtime).
				Int64("delta-creation-time", newCtime-origCtime).
				Int32("pid", pid).
				Msg("envoy: subprocess exited")
		}
	}
```

It produced this log message:

> {"level":"fatal","original-creation-time":1625173444000,"new-creation-time":1625173445000,"delta-creation-time":1000,"pid":99425,"time":"2021-07-01T19:09:26-04:00","message":"envoy: subprocess exited"}

**To Reproduce**
```go
package main

import (
	"fmt"
	"os/exec"
	"syscall"
	"time"

	"github.com/shirou/gopsutil/v3/process"
)

func main() {
	err := run()
	if err != nil {
		fmt.Printf("error: %s", err)
	}
}

func run() error {
	ticker := time.NewTicker(time.Millisecond)
	defer ticker.Stop()

	path, err := exec.LookPath("sleep")
	if err != nil {
		return err
	}

	cmd := exec.Command(path, "999999999")
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}

	err = cmd.Start()
	if err != nil {
		return err
	}

	pid := int32(cmd.Process.Pid)
	proc, err := process.NewProcess(pid)
	if err != nil {
		return err
	}

	for {
		<-ticker.C

		// Reproduce IsRunning internals
		//
		// 	origCtime, err := proc.CreateTime()
		// 	if err != nil {
		// 		return fmt.Errorf("could not get original create time: %w", err)
		// 	}
		// 	newProc, err := process.NewProcess(pid)
		// 	if err != nil {
		// 		return fmt.Errorf("could not create new process: %w", err)
		// 	}
		// 	newCtime, err := newProc.CreateTime()
		// 	if err != nil {
		// 		return fmt.Errorf("could not get create time of new process: %w", err)
		// 	}

		// 	running := origCtime == newCtime

		// 	if !running {
		// 		return fmt.Errorf("subprocess died: origCtime:%d newCtime:%d pid:%d", origCtime, newCtime, pid)
		// 	}

		// Use IsRunning API
		//
		running, err := proc.IsRunning()
		if err != nil {
			return fmt.Errorf("could not get process status: %w", err)
		}

		if !running {

			return fmt.Errorf("subprocess died: pid:%d", pid)
		}

	}
}
```

**Expected behavior**

`IsRunning` to reliably return true for processes still running.

**Environment (please complete the following information):**
 - [ ] Windows: [paste the result of `ver`]
 - [ ] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
 - [x] Mac OS: [paste the result of `sw_vers` and `uname -a`:
 ```
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71
```
```
Darwin XXXXXX 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
```
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

**Additional context**

We originally saw the bug very randomly with a 1s ticker.  Using a 1ms ticker reproduces in <1m on my machine.

**Comment by travisgroth** [comment]
Update: We're also seeing this on M1 based machines.

**Comment by Lomanic** [comment]
@travisgroth process.CreateTime() was changed in #1226 to not rely on an exec call to `ps` anymore, could you test with the latest gopsutil master? I can't test it myself as I don't own any darwin device nor VM these days.

**Comment by Lomanic** [comment]
No news in months, let's assume it's fixed
