### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by gao114882** [shirou/gopsutil#1095]
**Describe the bug**
i use the cpu module, go version 1.15, today build failed, can you fix this bug?

**To Reproduce**
```go
github.com/shirou/gopsutil/cpu imports
	github.com/StackExchange/wmi: github.com/StackExchange/wmi@v0.0.0-20210708210415-b284ef6ab838: parsing go.mod:
	module declares its path as: wmi
	        but was required as: github.com/StackExchange/wmi


```

**Expected behavior**
build success . 
**Environment (please complete the following information):**
 - [ ] Windows: [paste the result of `ver`]
 - [ 1] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
 - [ ] Mac OS: [paste the result of `sw_vers` and `uname -a`
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

**Additional context**

**Comment by shirou** [comment]
Thanks to @lespea, I think #1096 can solve this. Could you try again?

**Comment by gao114882** [comment]
Thanks, already fixed。
