### ISSUE TITLE
support zenpower module

### ISSUE THREAD

**Issue by liljenstolpe** [shirou/gopsutil#1104]
**Is your feature request related to a problem? Please describe.**
gopsutil does not show temperatures for zen3 processors (Ryzen 3xxx and 5xxx)

**Describe the solution you'd like**
There is a kernel module (zenpower) that surfaces all of the CPU usage, voltage, and temps - it would be good if gopsutil  was able to pull data from that in Ryzen systems

**Describe alternatives you've considered**
None

**Additional context**

**Comment by Lomanic** [comment]
This doesn't look easily feasible at all and it's really specific for a given architecture and OS.

Not worth the effort for gopsutil I would say sorry.
