### ISSUE TITLE
Include additional process states for load.Misc method

### ISSUE THREAD

**Issue by tbarker25** [shirou/gopsutil#1114]
**Is your feature request related to a problem? Please describe.**
We would like have process counts by more process states in the host receiver of the OpenTelemetry collector. For more specifics on our use-case see: https://github.com/open-telemetry/opentelemetry-collector/issues/3762

Process states include the following:
> blocked, daemon, detached, orphan, paging, running, sleeping, stopped, system, total, zombies

Additional states are very much OS-dependent. For example, the paging state is unique to Linux, orphan is unique to Solaris.

**Describe the solution you'd like**
The `load.Misc` (or another method) returns process counts in other states.

**Describe alternatives you've considered**
Implementing this in the otel-collector instead. This is certainly possible, but we would prefer the logic be in gopsutil.

**Additional context**
Getting these process states is OS-dependent. In Linux and Solaris, process states can be found by iterating over `/proc/{PID}/stat`. Other OSs would require a syscall.

Here is an example of collecting this in Linux: https://github.com/tbarker25/opentelemetry-collector/blob/processes-states/receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_scraper_linux.go

**Comment by tbarker25** [comment]
if this is a change you are amenable to then we're willing to write a PR (at least for the OSs we care about)

**Comment by shirou** [comment]
Same as #1115 basically "No". But there is a room to discuss.

I think if you want to know process counts by states, just call `process.Processes()`, iterate the slice and count by State. Is this not enough?

**Comment by tbarker25** [comment]
Ha, I hadn't even thought of just iterating over process.Processes(). That is certainly sufficient. Thanks 😄
