### ISSUE TITLE
Unable to get disks' serial number with IOCounters on linux

### ISSUE THREAD

**Issue by jbliao** [shirou/gopsutil#1139]
**Describe the bug**
`IOCountersStat.SerialNumber` always have no value on linux

I use telegraf to monitor disk which use this go module to get disk info, and the serial of disk always be null.

**To Reproduce**
```go
package main

import (
    "github.com/shirou/gopsutil/v3/disk"
    "fmt"
)

func main() {
    info, err := disk.IOCounters("/dev/sda")
    if (err != nil) {
        fmt.Print(err)
    }
    fmt.Println(info)

    serialNumber, err := disk.SerialNumber("/dev/sda")
    if (err != nil) {
        fmt.Print(err)
    }
    fmt.Println(serialNumber)

    serialNumber, err = disk.SerialNumber("sda")
    if (err != nil) {
        fmt.Print(err)
    }
    fmt.Println(serialNumber)

}                                 
```
result:
```
map[sda:{"readCount":398790,"mergedReadCount":1,"writeCount":613726,"mergedWriteCount":360,"readBytes":20676746240,"writeBytes":55764192768,"readTime":3302034,"writeTime":2927377,"iopsInProgress":0,"ioTime":6360176,"weightedIO":8757288,"name":"sda","serialNumber":"","label":""}]
INTEL_SSDSC2BW240A4_CVDA4152****<CENSORED>***
no such file or directory
```

**Expected behavior**
`disk.IOCounters` should contain serial number of disks.

**Environment (please complete the following information):**
Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]

* `cat /etc/os_release`
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
* `uname -a`
```
Linux truenas.local 5.10.42+truenas #1 SMP Mon Aug 30 21:54:59 UTC 2021 x86_64 GNU/Linux
```

**Additional context**
Actually this line will fail every time when it was called from IOCounters
https://github.com/shirou/gopsutil/blob/8d7a3abddb09aa082668d23e1e50cf719bbf875d/v3/disk/disk_linux.go#L444

The `name` variable should prepend `/dev/`

**Comment by shirou** [comment]
According to your report, `disk.SerialNumber("/dev/sda")` seems succeeded (and I confirmed it works on my local). Why do you want to specify `"sda"`?
