### ISSUE TITLE
README incorrectly states process `Terminal` works on macOS

### ISSUE THREAD

**Issue by florisvdg** [shirou/gopsutil#1144]
**Describe the bug**

In the README, it says that the `process` `Terminal()` should work on macOS: https://github.com/shirou/gopsutil/blob/fd4fbd9c79807791211c38257838483305295005/README.md#L195

But in reality, it returns an `ErrNotImplementedError`:
https://github.com/shirou/gopsutil/blob/fd4fbd9c79807791211c38257838483305295005/v3/process/process_darwin.go#L243-L244

**Expected behavior**

Either a valid `darwin` implementation or the docs not stating that it works.

**Comment by shirou** [comment]
Thank you for the report! Indeed, terminal is not implemented yet on macOS. I have removed that mark from README.
