### ISSUE TITLE
Deprecated code in macOS Monterey

### ISSUE THREAD

**Issue by lavrxxx** [shirou/gopsutil#1164]
**Describe the bug**
There is a deprecation messages while building code with gopsutil v3.
```
# github.com/shirou/gopsutil/disk
iostat_darwin.c:28:2: warning: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:132:1: note: 'IOMasterPort' has been explicitly marked deprecated here
# github.com/shirou/gopsutil/host
smc_darwin.c:75:41: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
```

**To Reproduce**
```go
package main

import (
	_ "github.com/shirou/gopsutil/cpu"
	_ "github.com/shirou/gopsutil/disk"
	_ "github.com/shirou/gopsutil/host"
	_ "github.com/shirou/gopsutil/mem"
)

func main() {}
```

**Expected behavior**
There isn't any messages about deprecation.

**Environment (please complete the following information):**
 - [x] Mac OS: [paste the result of `sw_vers` and `uname -a`
```
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559
```
```
Darwin MacBook-Pro.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64
```

**Comment by zls3434** [comment]
I got the same warning

**Comment by lfjdhr123** [comment]
same here

**Comment by vikieQ** [comment]
same,too

**Comment by Kennnnnnji** [comment]
This may relate to CGO. I found a temporary solution: 
```
go env -w CGO_ENABLED="0"
```

**Comment by janflyborg** [comment]
> This may relate to CGO. I found a temporary solution, use this before building projects:
> 
> ```
> go env -w CGO_ENABLED="0"
> ```

Sure, but some people need cgo, so this workaround does not work for everyone.

**Comment by Lomanic** [comment]
Can any of you try `go build github.com/shirou/gopsutil/disk` and `go build github.com/shirou/gopsutil/host` after applying (`curl -L https://github.com/shirou/gopsutil/files/7612001/diff.txt | git apply`) the following diff on both macos 12 and a lower macos version?

[diff.txt](https://github.com/shirou/gopsutil/files/7612001/diff.txt)

**Comment by lavrxxx** [comment]
@Lomanic can you describe requirements with more details? I can try on macOS 12. Do I need to apply diff in my project or u need to download gopsutil source?

**Comment by lavrxxx** [comment]
@Lomanic I have applied your diff in master branch, then I have tried to execute `go build github.com/shirou/gopsutil/disk` and `go build github.com/shirou/gopsutil/host` in `v3` folder and I had warnings about deprecation code.

**Comment by Mxxim** [comment]
Hi, I have got the same warning in macOS 12.0.1, do you known how to fix it?

```
# github.com/shirou/gopsutil/cpu
../../../../pkg/mod/github.com/shirou/gopsutil@v2.20.7+incompatible/cpu/cpu_darwin_cgo.go:13:5: warning: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Wundef-prefix=TARGET_OS_]
# github.com/shirou/gopsutil/disk
iostat_darwin.c:28:2: warning: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:132:1: note: 'IOMasterPort' has been explicitly marked deprecated here
```

**Comment by dt** [comment]
@Lomanic Should that `MAC_OS_X_VERSION_MAX_ALLOWED` be `MAC_OS_X_VERSION_MIN_REQUIRED` instead, to avoid the missing symbol on older deployment targets?

**Comment by Mxxim** [comment]
@shirou Hi, how can I use the latest version of this repository after pr #1191  has merged? My previous go.mod file is like this:

```go
github.com/shirou/gopsutil v2.20.7+incompatible
```

And then I updated this version to v3.21.12 from v2.20.7+incompatible, but got error like this:
```go
 require github.com/shirou/gopsutil: version "v3.21.12" invalid: should be v0 or v1, not v3
```

**Comment by liuhaoran666** [comment]
+1 how to resolve it?

**Comment by lavrxxx** [comment]
> +1 how to resolve it?

You can update package to the latest v3 version

**Comment by bsergean** [comment]
```
# github.com/shirou/gopsutil/v3/disk
iostat_darwin.c:28:2: warning: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
```

@lavrxxx I'm getting this warning with the v3 version as well.

**Comment by shoce** [comment]
i have the same, should be reopened or a new one created

**Comment by ashutosh-tikaj** [comment]
> This may relate to CGO. I found a temporary solution, use this before building projects:
> 
> ```
> go env -w CGO_ENABLED="0"
> ```

You saved my day, I had already spent 2 hours finding the issue :(
