### ISSUE TITLE
load.Avg() always returns 0 on Windows

### ISSUE THREAD

**Issue by dittakaviram** [shirou/gopsutil#1183]
https://github.com/shirou/gopsutil/blob/de385f50a8dff3eb43229740f5c451b32ff084ea/load/load_windows.go#L57

load.Avg() returning 0 values all the time on windows, is this expected?

**Comment by shirou** [comment]
First `Avg()` invocation starts a retrieval goroutine and return 0. But after 5 sec or more later, `Avg()` returns a value.
