### ISSUE TITLE
Error: "'TARGET_OS_IPHONE' is not defined, evaluates to 0" on XCode 13.1 and MacOS 12.0.1

### ISSUE THREAD

**Issue by jsastriques** [shirou/gopsutil#1187]
I'm getting this error when I tried to build my RN project, has somebody any idea or solution?

<img width="406" alt="Screen Shot 2021-11-23 at 23 32 22" src="https://user-images.githubusercontent.com/44577048/143161271-7c913c45-1523-4e13-b254-95316bc5d0e2.png">

**Comment by DerekStrickland** [comment]
I had this exact issue after updating to BigSur 11.6.1 and XCode 13.  I had to uninstall XCode entirely, but keep the command line tools, in order to build again.
