### ISSUE TITLE
 IOMasterPort  is deprecated: first deprecated in macOS 12

### ISSUE THREAD

**Issue by FlameMida** [shirou/gopsutil#1188]
**Describe the bug**

github.com/shirou/gopsutil/disk
iostat_darwin.c:28:2: warning: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:132:1: note: 'IOMasterPort' has been explicitly marked deprecated here

**Environment (please complete the following information):**
 Mac OS: 
```bash
 sw_vers                                     
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559

uname -a                                                             
Darwin MacBook-Pro-16.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64
```

**Comment by Lomanic** [comment]
Duplicate of #1164
