### ISSUE TITLE
use macos 12.0.1 get warning

### ISSUE THREAD

**Issue by asd257644432** [shirou/gopsutil#1189]
# github.com/shirou/gopsutil/disk
iostat_darwin.c:28:2: warning: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:132:1: note: 'IOMasterPort' has been explicitly marked deprecated here

**Comment by shirou** [comment]
duplicate #1164
