### ISSUE TITLE
Depreciation warning: kIOMasterPortDefault

### ISSUE THREAD

**Issue by iwahbe** [shirou/gopsutil#1190]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
Build on macOS Montaray 12.0.1. The error looks like this
```
# github.com/shirou/gopsutil/host
smc_darwin.c:75:41: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
```

**Expected behavior**
No depreciation warning. 

**Environment (please complete the following information):**
 - [ ] Windows: [paste the result of `ver`]
 - [ ] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
 - [X] Mac OS: [paste the result of `sw_vers` and `uname -a`
`sw_vers`: 
```
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559
```
`name -a`:
 ```
Darwin ${NAME} 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64
```
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

**Additional context**
[Cross-compiling? Paste the command you are using to cross-compile and the result of the corresponding `go env`]

**Comment by shirou** [comment]
deprecate #1164
