### ISSUE TITLE
ClockTicks on FreeBSD

### ISSUE THREAD

**Issue by dveeden** [shirou/gopsutil#1197]
On Linux there is `process.ClockTicks`, but on FreeBSD this is missing.

Maybe these sysctl's can help?
```
% sysctl kern.timecounter.tick
kern.timecounter.tick: 1
% sysctl kern.clockrate
kern.clockrate: { hz = 1000, tick = 1000, profhz = 8128, stathz = 127 }
```

**Comment by Lomanic** [comment]
There's no exported `ClockTicks` variable anymore in the `process` package on v3 https://godocs.io/github.com/shirou/gopsutil/v3/process, this was an oversight and never meant to be exposed in the first place.
