### ISSUE TITLE
f.ReadDir undefined (type *os.File has no field or method ReadDir, but does have Readdir)

### ISSUE THREAD

**Issue by thhy** [shirou/gopsutil#1198]
**Describe the bug**
[A clear and concise description of what the bug is.]
It reports "net/net_linux.go:548:22: f.ReadDir undefined (type *os.File has no field or method ReadDir, but does have Readdir)" when I run make build_test
**To Reproduce**
```go
// paste example code reproducing the bug you are reporting
```
Run make build_test on top dir.
**Expected behavior**
[A clear and concise description of what you expected to happen.]
Every testcase passed.
**Environment (please complete the following information):**
 - [√ ] Linux: [centos6]

**Additional context**
[Cross-compiling? Paste the command you are using to cross-compile and the result of the corresponding `go env`]
go1.15.6

**Comment by shirou** [comment]
sorry, from #1105 go 1.15 is not supported.
