### ISSUE TITLE
Doesn't handle processes with spaces in name

### ISSUE THREAD

**Issue by jimmidyson** [shirou/gopsutil#120]
As per http://man7.org/linux/man-pages/man5/proc.5.html, the second field is the filename of the executable in parentheses:

> 2) comm  %s
                        The filename of the executable, in parentheses.
                        This is visible whether or not the executable is
                        swapped out.

In the case of spaces in the filename (as I observed today) `/proc/[pid]/stat` looks like:

    1591 (Plex Media Serv) S 1 1591 1591 0 -1 1077952768 19063 0 306 0 257 95 0 0 20 0 17 0 1353 596594688 13330 18446744073709551615 1 1 0 0 0 0 0 4097 17646 18446744073709551615 0 0 17 4 0 0 69 0 0 0 0 0 0 0 0 0 0

Rather than hard coding the field numbers they should be offset from the field ending in `)`.

**Comment by shirou** [comment]
Thank you very much!
