### ISSUE TITLE
Test_Children Failing on RHEL/UBI Platform Reference: #477

### ISSUE THREAD

**Issue by saurabhghumnar** [shirou/gopsutil#1211]
Hi,
I am testing the **gopsutil/v3** repo tests using golang

Command used :  `go test ./...`

Platform : **Redhat Linux UBI 8.4 Container**

Test Outcome:
```
Building  with v3.21.1
go: downloading github.com/shirou/gopsutil/v3 v3.21.1
go: downloading github.com/shirou/gopsutil v3.21.1+incompatible
Testing  with v3.21.1
go: /home/tester/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.1/go.mod already exists
go: downloading golang.org/x/sys v0.0.0-20201024232916-9f70ab9862d5
go: downloading github.com/stretchr/testify v1.6.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/davecgh/go-spew v1.1.0
go: downloading gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
ok      github.com/shirou/gopsutil/v3/cpu       0.199s
ok      github.com/shirou/gopsutil/v3/disk      0.006s
ok      github.com/shirou/gopsutil/v3/docker    0.017s
**--- FAIL: TestUsers (0.00s)
    host_test.go:80: error open /var/run/utmp: no such file or directory
    host_test.go:84: Users is empty**
FAIL
FAIL    github.com/shirou/gopsutil/v3/host      0.010s
ok      github.com/shirou/gopsutil/v3/internal/common   0.055s
ok      github.com/shirou/gopsutil/v3/load      0.004s
ok      github.com/shirou/gopsutil/v3/mem       0.005s
ok      github.com/shirou/gopsutil/v3/net       0.027s
**--- FAIL: Test_Children (0.10s)
    process_test.go:525: error process does not have children
FAIL**
FAIL    github.com/shirou/gopsutil/v3/process   1.829s
FAIL
```

Although the tests pass on Centos using same command. Is there some configurations missing that I would need to do explicitly or the test itself is not built for the platform?

Thank you !

Referencing issue :
https://github.com/shirou/gopsutil/issues/477#issue-283565764

**Comment by shirou** [comment]
By using [UBI minimal container on Docker Hub](https://hub.docker.com/r/redhat/ubi8-minimal), the "utmp" nor "wtmp" file is not exists. So "host.Users()" will fail. Do you have any idea about utmp in UBI container? (I think there is no such a information in the container)

**Comment by saurabhghumnar** [comment]
Yeah, UBI containers don't have a utmp file so host_test.go will fail. But not sure about why the Test_Children fails. Is that test OS or Platform dependent ? 
I ran the tests outside docker containers, they work fine though.

**Comment by shirou** [comment]
`Children()` uses `pgrep` command internally. And `redhat/ubi8-minimal` does not have `pgrep` along with `ps`. So that test also failed.

In the `Children()`, check [pid length at first](https://github.com/shirou/gopsutil/blob/master/process/process_linux.go#L354). even if pgrep failed with "command not found" which returns empty pids, `ErrorNoChildren` error returns. I think this `len(pids) == 0` check should run only `err == nil`. I will make a PR. Thank you for your report!
