### ISSUE TITLE
Getting partitions with hidepid=2 on proc fails

### ISSUE THREAD

**Issue by rikvdh** [shirou/gopsutil#1212]
**Describe the bug**
When getting disk.Partitions on a system for an unprivileged user, whilst having hidepid=2 option on the proc-mount fails.

Behavior was broken by this commit: https://github.com/shirou/gopsutil/commit/b39f8bb90e5a83b4837cc62b001309562e63cd28#diff-1c057146d22f660d0d6142cbda77095e8621efa99d8b4058bbf885c81e6e397e

/proc/1 might not be available. Perhaps a fallback to self can be added?

**Environment (please complete the following information):**
 - [ ] Windows: [paste the result of `ver`]
 - [X] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
 - [ ] Mac OS: [paste the result of `sw_vers` and `uname -a`
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

**Comment by Lomanic** [comment]
Adding a fallback to `/proc/self` is tracked in  #1159
