### ISSUE TITLE
smc_darwin.c calls are deprecated in MacOS > 12.0

### ISSUE THREAD

**Issue by aalmenar** [shirou/gopsutil#1227]
Describe the bug
kIOMasterPortDefault has been renamed to kIOMainPortDefault, apparently.

When compiling using the host library you get:

smc_darwin.c:75:41: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here

**Comment by Lomanic** [comment]
Duplicate of #1164
