### ISSUE TITLE
iOS support: fatal error: 'libproc.h' file not found

### ISSUE THREAD

**Issue by imWildCat** [shirou/gopsutil#1230]
**Describe the bug**

I'm building a library (`rclone`) targeting iOS with `gopsutil` as a dependency. However, it does not work due to the iOS platform support.

**To Reproduce**
```shell
GOOS=ios CGO_CFLAGS='-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -miphoneos-version-min=13.0 -fembed-bitcode -arch arm64' CGO_CXXFLAGS='-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -miphoneos-version-min=13.0 -fembed-bitcode -arch arm64' CGO_LDFLAGS='-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -miphoneos-version-min=13.0 -fembed-bitcode -arch arm64' CGO_ENABLED=1 GOARCH=arm64 DARWIN_SDK=iphoneos go test ./... 
```

```shell
?       github.com/shirou/gopsutil/v3   [no test files]
# github.com/shirou/gopsutil/v3/cpu
cpu/cpu_darwin_cgo.go:15:10: fatal error: 'libproc.h' file not found
#include <libproc.h>
         ^~~~~~~~~~~
1 error generated.
# github.com/shirou/gopsutil/v3/cpu
cpu/cpu_darwin_cgo.go:15:10: fatal error: 'libproc.h' file not found
#include <libproc.h>
         ^~~~~~~~~~~
1 error generated.
FAIL    github.com/shirou/gopsutil/v3/cpu [build failed]
# github.com/shirou/gopsutil/v3/disk
iostat_darwin.c:8:10: fatal error: 'IOKit/IOKitLib.h' file not found
iostat_darwin.c:8:10: note: did not find header 'IOKitLib.h' in framework 'IOKit' (loaded from '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk/System/Library/Frameworks')
FAIL    github.com/shirou/gopsutil/v3/disk [build failed]
FAIL    github.com/shirou/gopsutil/v3/docker [build failed]
FAIL    github.com/shirou/gopsutil/v3/host [build failed]
signal: killed
FAIL    github.com/shirou/gopsutil/v3/internal/common   0.002s
signal: killed
FAIL    github.com/shirou/gopsutil/v3/load      0.001s
signal: killed
FAIL    github.com/shirou/gopsutil/v3/mem       0.001s
signal: killed
FAIL    github.com/shirou/gopsutil/v3/net       0.001s
FAIL    github.com/shirou/gopsutil/v3/process [build failed]
FAIL
```

**Expected behavior**

Tests can pass

**Environment (please complete the following information):**
 - [ ] Windows: [paste the result of `ver`]
 - [ ] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
 - [ ] Mac OS: [paste the result of `sw_vers` and `uname -a`
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

It's `ios` in addition to `darwin`.

**Additional context**
[Cross-compiling? Paste the command you are using to cross-compile and the result of the corresponding `go env`]

**Comment by shirou** [comment]
I don't know the iOS, but how about to build without cgo, this means `CGO_ENABLED=0` ?

**Comment by imWildCat** [comment]
It would fail:

```shell
$ GOOS=ios CGO_ENABLED=0 GOARCH=arm64 DARWIN_SDK=iphoneos go test ./...
?   	github.com/shirou/gopsutil/v3	[no test files]
# github.com/shirou/gopsutil/v3/cpu.test
loadinternal: cannot find runtime/cgo
# github.com/shirou/gopsutil/v3/disk.test
loadinternal: cannot find runtime/cgo
# github.com/shirou/gopsutil/v3/docker.test
loadinternal: cannot find runtime/cgo
# github.com/shirou/gopsutil/v3/internal/common.test
loadinternal: cannot find runtime/cgo
# github.com/shirou/gopsutil/v3/load.test
loadinternal: cannot find runtime/cgo
# github.com/shirou/gopsutil/v3/host.test
loadinternal: cannot find runtime/cgo
# github.com/shirou/gopsutil/v3/net.test
loadinternal: cannot find runtime/cgo
ok  	github.com/shirou/gopsutil/v3/cpu	(cached)
ok  	github.com/shirou/gopsutil/v3/disk	(cached)
ok  	github.com/shirou/gopsutil/v3/docker	(cached)
ok  	github.com/shirou/gopsutil/v3/host	(cached)
ok  	github.com/shirou/gopsutil/v3/internal/common	(cached)
ok  	github.com/shirou/gopsutil/v3/load	(cached)
# github.com/shirou/gopsutil/v3/mem.test
loadinternal: cannot find runtime/cgo
--- FAIL: TestVirtual_memory (0.00s)
    mem_test.go:33: {"total":68719476736,"available":46526464000,"used":22193012736,"usedPercent":32.29508399963379,"free":31000166400,"active":16775135232,"inactive":15526297600,"wired":3182903296,"laundry":0,"buffers":0,"cached":0,"writeBack":0,"dirty":0,"writeBackTmp":0,"shared":0,"slab":0,"sreclaimable":0,"sunreclaim":0,"pageTables":0,"swapCached":0,"commitLimit":0,"committedAS":0,"highTotal":0,"highFree":0,"lowTotal":0,"lowFree":0,"swapTotal":0,"swapFree":0,"mapped":0,"vmallocTotal":0,"vmallocUsed":0,"vmallocChunk":0,"hugePagesTotal":0,"hugePagesFree":0,"hugePageSize":0}
    mem_test.go:52:
        	Error Trace:	mem_test.go:52
        	Error:      	Not equal:
        	            	expected: 0x1000000000
        	            	actual  : 0xc628f8000
        	Test:       	TestVirtual_memory
        	Messages:   	Total should be computable (used + free + buffers + cached): {"total":68719476736,"available":46526464000,"used":22193012736,"usedPercent":32.29508399963379,"free":31000166400,"active":16775135232,"inactive":15526297600,"wired":3182903296,"laundry":0,"buffers":0,"cached":0,"writeBack":0,"dirty":0,"writeBackTmp":0,"shared":0,"slab":0,"sreclaimable":0,"sunreclaim":0,"pageTables":0,"swapCached":0,"commitLimit":0,"committedAS":0,"highTotal":0,"highFree":0,"lowTotal":0,"lowFree":0,"swapTotal":0,"swapFree":0,"mapped":0,"vmallocTotal":0,"vmallocUsed":0,"vmallocChunk":0,"hugePagesTotal":0,"hugePagesFree":0,"hugePageSize":0}
FAIL
FAIL	github.com/shirou/gopsutil/v3/mem	0.310s
ok  	github.com/shirou/gopsutil/v3/net	(cached)
# github.com/shirou/gopsutil/v3/process.test
loadinternal: cannot find runtime/cgo
ok  	github.com/shirou/gopsutil/v3/process	22.179s
FAIL
```

**Comment by jigar-f** [comment]
@imWildCat  Any update on this?

**Comment by imWildCat** [comment]
@jigar-f What update?

**Comment by jigar-f** [comment]
@imWildCat I mean are you able to fix this issue, I am getting same problem while generating ios binding

**Comment by imWildCat** [comment]
@jigar-f I cannot remember. The answer should be no. Coz I'm no longer use go/gomobile anymore for mobile dev.

(off-topic) Rust is 10x better in this case

**Comment by simbadMarino** [comment]
> @imWildCat I mean are you able to fix this issue, I am getting same problem while generating ios binding

Unfortunately this is more a iOS SDK (Apple does not include libproc.h in iOS SDK) limitation than a problem with gopsitul to be honest. There is a [workaround](https://github.com/simbadMarino/btfs-sharedLib/releases/v2.3.1) by using a CGO flag pointing to macOS SDK. Try writing `#cgo CFLAGS: -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include` before #include libproc.h.

**Comment by yscMichael** [comment]
+1, I'm experience the same issue.

**Comment by simbadMarino** [comment]
@yscMichael , I found a workaround, would be good if you could try on your end and if all good I could opening a PR for iOS support :)

run go vendor & replace cpu_darwin_cgo.go content with following code:

//go:build darwin && cgo
// +build darwin,cgo

package cpu

/*
#include <stdlib.h>
#include <sys/sysctl.h>
#include <sys/mount.h>
#include <mach/mach_init.h>
#include <mach/mach_host.h>
#include <mach/host_info.h>
#include <TargetConditionals.h>
#if TARGET_OS_MAC
#if TARGET_OS_IPHONE  //Iphone build check to differentiate between iPhone and Mac
#define IOS 1 //dummy define
#endif
#elif
#include <libproc.h>
#endif
#include <mach/processor_info.h>
#include <mach/vm_map.h>
*/
import "C"

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"unsafe"
)

// these CPU times for darwin is borrowed from influxdb/telegraf.

func perCPUTimes() ([]TimesStat, error) {
	var (
		count   C.mach_msg_type_number_t
		cpuload *C.processor_cpu_load_info_data_t
		ncpu    C.natural_t
	)

	status := C.host_processor_info(C.host_t(C.mach_host_self()),
		C.PROCESSOR_CPU_LOAD_INFO,
		&ncpu,
		(*C.processor_info_array_t)(unsafe.Pointer(&cpuload)),
		&count)

	if status != C.KERN_SUCCESS {
		return nil, fmt.Errorf("host_processor_info error=%d", status)
	}

	// jump through some cgo casting hoops and ensure we properly free
	// the memory that cpuload points to
	target := C.vm_map_t(C.mach_task_self_)
	address := C.vm_address_t(uintptr(unsafe.Pointer(cpuload)))
	defer C.vm_deallocate(target, address, C.vm_size_t(ncpu))

	// the body of struct processor_cpu_load_info
	// aka processor_cpu_load_info_data_t
	var cpu_ticks [C.CPU_STATE_MAX]uint32

	// copy the cpuload array to a []byte buffer
	// where we can binary.Read the data
	size := int(ncpu) * binary.Size(cpu_ticks)
	buf := (*[1 << 30]byte)(unsafe.Pointer(cpuload))[:size:size]

	bbuf := bytes.NewBuffer(buf)

	var ret []TimesStat

	for i := 0; i < int(ncpu); i++ {
		err := binary.Read(bbuf, binary.LittleEndian, &cpu_ticks)
		if err != nil {
			return nil, err
		}

		c := TimesStat{
			CPU:    fmt.Sprintf("cpu%d", i),
			User:   float64(cpu_ticks[C.CPU_STATE_USER]) / ClocksPerSec,
			System: float64(cpu_ticks[C.CPU_STATE_SYSTEM]) / ClocksPerSec,
			Nice:   float64(cpu_ticks[C.CPU_STATE_NICE]) / ClocksPerSec,
			Idle:   float64(cpu_ticks[C.CPU_STATE_IDLE]) / ClocksPerSec,
		}

		ret = append(ret, c)
	}

	return ret, nil
}

func allCPUTimes() ([]TimesStat, error) {
	var count C.mach_msg_type_number_t
	var cpuload C.host_cpu_load_info_data_t

	count = C.HOST_CPU_LOAD_INFO_COUNT

	status := C.host_statistics(C.host_t(C.mach_host_self()),
		C.HOST_CPU_LOAD_INFO,
		C.host_info_t(unsafe.Pointer(&cpuload)),
		&count)

	if status != C.KERN_SUCCESS {
		return nil, fmt.Errorf("host_statistics error=%d", status)
	}

	c := TimesStat{
		CPU:    "cpu-total",
		User:   float64(cpuload.cpu_ticks[C.CPU_STATE_USER]) / ClocksPerSec,
		System: float64(cpuload.cpu_ticks[C.CPU_STATE_SYSTEM]) / ClocksPerSec,
		Nice:   float64(cpuload.cpu_ticks[C.CPU_STATE_NICE]) / ClocksPerSec,
		Idle:   float64(cpuload.cpu_ticks[C.CPU_STATE_IDLE]) / ClocksPerSec,
	}

	return []TimesStat{c}, nil
}
