### ISSUE TITLE
Test failure: expected `ErrorNoChild` but got `exit status 1`

### ISSUE THREAD

**Issue by crvena-sonja** [shirou/gopsutil#1248]
**Describe the bug**
TestChildZombie (relevant code below) is failing with `exit status 1`, when we expected to see `ErrorNoChildren` when run on `RHEL 7` & `Ubuntu 18.04`.

**To Reproduce**
```go
ctx := context.Background()
_ , err := p.ChildrenWithContext(ctx)
	if err != nil {
		if err == process.ErrorNoChildren {
			return nil
		}
		return fmt.Errorf("%w", err)
	}
```

**Expected behavior**
Expect to see `ErrorNoChildren`. 

**Environment (please complete the following information):**
 - [X] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]

**Comment by Lomanic** [comment]
There's no `TestChildZombie` in gopsutil, what is this issue about?
