### ISSUE TITLE
question: `(*process.Process).CPUPercent()` returning values above 100, what does this number represent?

### ISSUE THREAD

**Issue by gekigek99** [shirou/gopsutil#1266]
when printing `(*process.Process).CPUPercent()` of a process that is pretty heavy i get numbers in the range of 500 or 600 (sometimes more). _(When the tested process finishes the heavy calculations, this number returns to around 2 or 3.)_

Why is that? should't it be a precentage with maximum value of 100?

**Comment by ddyurchenko** [comment]
This is how normally it works when process uses more than 1 CPU for task execution.

See more on StackOverflow:
https://stackoverflow.com/questions/52671289/why-is-cpu-used-more-than-100/52671789
https://stackoverflow.com/questions/41225475/cpu-usage-exceeding-more-than-100-in-top-command-third-line

**Comment by Lomanic** [comment]
Thanks @ddyurchenko
