### ISSUE TITLE
Add LinuxOnly structs and functions

### ISSUE THREAD

**Issue by shirou** [shirou/gopsutil#1282]
**Is your feature request related to a problem? Please describe.**

I am little bit tired many people open issues and PRs which get Linux specific information.

**Describe the solution you'd like**

Introduce `LinuxOnly` structs and functions. ex `mem.VirtualMemoryStatLinuxOnly` or `disk.IOCountersStatLinuxOnly`. This structs and functions are only found in the `linux` build tag file. Thus, cannot be compile on other operating systems. We already have some `Ex` structs, but it will be deprecate, same as psutil.

We may expand to other platforms like `WindowsOnly`

**Additional context**

If we remove Ex structs, it breaks API compatibility. In v3, I want to add just a `Deprecated:` in the comment. Those will be delete v4.

**Comment by Lomanic** [comment]
In my opinion, people wanting linux-specific stats should use https://github.com/prometheus/procfs which is made to cover linux procfs parsing extensively, while gopsutil value is providing a same interface over every supported platforms. So I'm against the idea proposed in this issue @shirou.

**Comment by shirou** [comment]
Indeed. Then, I close this issue. Thank you for the comment!
