### ISSUE TITLE
darwin: process.Name() behaves differently in cgo and !cgo builds

### ISSUE THREAD

**Issue by cfergeau** [shirou/gopsutil#1288]
**Describe the bug**

When trying to list all the running processes on macOS, I get `invalid argument` errors when calling `Name()`. This only happens with cgo-builds, if I rebuild my test program with `CGO_ENABLED=0` then I can successfully list all process names. Calling `Exe()` does not error out (but then there are more issues with it :-/ ).

**To Reproduce**
```go
package main

import (
	"fmt"
	"log"

	"github.com/shirou/gopsutil/v3/process"
)

func main() {
	processes, err := process.Processes()
	if err != nil {
		log.Fatal(err)
	}
	for _, process := range processes {
		exe, err := process.Exe()
		if err != nil {
			fmt.Println("error calling Exe()", err)
			log.Fatal(err)
		}
		fmt.Println("exe: ", exe)

		name, err := process.Name()
		if err != nil {
			fmt.Println("error calling Name()", err)
			log.Fatal(err)
		}
		fmt.Println("name: ", name)
	}
}
```

**Expected behavior**
Building this with CGO_ENABLED=1 results in errors for some processes:
```
exe:  /System/Library/Frameworks/ColorSync.framework/Versions/A/XPCServices/com.apple.ColorSyncXPCAgent.xpc/Contents/MacOS/com.apple.ColorSyncXPCAgent
error calling Name() invalid argument
```
The same process shows up correctly in `ps aux`, and `Exe()` is also successful, so an error is unexpected.

**Environment (please complete the following information):**
 - [x] Mac OS: [paste the result of `sw_vers` and `uname -a`
 ```
$ sw_vers 
ProductName:	macOS
ProductVersion:	11.6.5
BuildVersion:	20G527

$ uname -a
Darwin MacBook-Pro 20.6.0 Darwin Kernel Version 20.6.0: Tue Feb 22 21:10:41 PST 2022; root:xnu-7195.141.26~1/RELEASE_X86_64 x86_64
```

**Additional context**
I'm building natively on the mac.

**Comment by Lomanic** [comment]
In https://github.com/code-ready/crc/pull/3109#discussion_r853099430 you wrote

> Name() errors come from processes which are not owned by the current user as far as I can tell.

ps has the SUID bit set https://stackoverflow.com/a/52314668 (I can't verify without a darwin host/VM but that's what I remember from https://github.com/shirou/gopsutil/pull/1229#issuecomment-1012408022), which your program probably doesn't have. If you run your `CGO_ENABLED=1` program as root (or set the SUID bit), I guess the errors disappear, right?

**Comment by cfergeau** [comment]
Oh, I did not realize `ps` is SUID. `sudo` helps, though the test program fails to get `Name()`/`Exe()` for zombie processes which `ps` correctly shows as `(process_name)`. But that's a different issue, the initial issue is not really a bug
