### ISSUE TITLE
Use of Windows PDH counters

### ISSUE THREAD

**Issue by ArjunDhar** [shirou/gopsutil#1294]
**Is your feature request related to a problem? Please describe.**
Windows the official way is to use [Performance Counters using the V2 PDH Win-API architecture](https://docs.microsoft.com/en-us/windows/win32/perfctrs/about-performance-counters). I noticed the windows method is using `QueryServiceStatusEx` (Win equivalent [QueryServiceStatusEx](https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-queryservicestatusex)); which is a service query method I think outside the Performance counter architecture. Is this the most optimal and  can we use Performance Counter paths in the near future?

**Describe the solution you'd like**
[https://pypi.org/project/winstats/](https://pypi.org/project/winstats/) > `winstats.get_perf_data(...)`

See Also: [Get current frequency in python with psutil (Windows)](https://stackoverflow.com/questions/68201683/get-current-frequency-in-python-with-psutil-windows)

**Describe alternatives you've considered**
* psutil
* [golang perfcounters](https://pkg.go.dev/github.com/cloudradar-monitoring/cagent/perfcounters)
* [grofer](https://opensourcelibs.com/lib/grofer)
* collectdwin (A `collectd` alternative in Windows)

**Comment by Lomanic** [comment]
I'm not sure to understand which calls you want to replace in gopsutil, you mention QueryServiceStatusEx [which is only used in the `winservices` package](https://github.com/shirou/gopsutil/blob/def686540282ccab5cd575eddf300f80580e595c/winservices/winservices.go#L89) and performance counters are unrelated to that.

Performance Counters were mentioned previously in https://github.com/shirou/gopsutil/issues/618#issuecomment-496615945 for the `disk` package to replace the slow and buggy wmi calls, but this is not necessary anymore: https://github.com/shirou/gopsutil/issues/618#issuecomment-599273475

Having already looked into it in the past, PdhOpenQuery is notoriously hard to use so we won't go out of our way to use it for no real reason.
