### ISSUE TITLE
I have a Windows process that definitely exists, but I'm getting "process does not exist" error

### ISSUE THREAD

**Issue by AndrewSav** [shirou/gopsutil#1298]
**Describe the bug**
On Windows, when calling `NewProcess` passing a pid that exists for some processes I get "process does not exist" error, whereas the process definitely exists.

**To Reproduce**
This happens to some processes only, it works as exepcted for most of the processes.

```go
package main

import (
	"fmt"
	"github.com/shirou/gopsutil/v3/process"
)

func findPid(pid int32) {
	if pids, err := process.Pids(); err != nil {
		fmt.Printf("error calling Pids: %v\n", pid, err)
	} else {
		pidFound := false
		for _, c := range pids {
			if c == pid {
				pidFound = true
				break
			}
		}
		fmt.Printf("Pid %d found: %v\n", pid, pidFound)
	}

}

func callNewProcess(pid int32) {
	if p, err := process.NewProcess(pid); err != nil {
		fmt.Printf("error calling NewProcess for pid %d: %v\n", pid, err)
	} else {
		fmt.Printf("ok calling NewProcess for pid %d. Result: %v\n", pid, p)
	}
}

func main() {
	pid := int32(6756)
	findPid(pid)
	callNewProcess(pid)
	findPid(pid)
	callNewProcess(pid)

}
```

Output:

```
Pid 6756 found: true
error calling NewProcess for pid 6756: process does not exist
Pid 6756 found: true
error calling NewProcess for pid 6756: process does not exist
```

**Expected behavior**
Since the pid and the process exist I expect the NewProcess call to succeed.

**Environment (please complete the following information):**
 - Windows: Microsoft Windows [Version 10.0.14393]

**Additional context**
This is happening with some but not all VirtualBox Headless Frontend processes. I can see the process in the Process Explorer, I can also kill it form there if I like, as far as I can see it is no different from other processes. Process Explorer marks this process as "packed" and the command line for the process as displayed by the process explorer does not start with the executable name, which is a difference from most processes. Some pictures are below.

![ps01](https://user-images.githubusercontent.com/658865/167236015-0c477bb2-fb87-4830-a74b-eefcd0dca61d.png)
![ps02](https://user-images.githubusercontent.com/658865/167236032-34c2b734-4973-4c63-b9e8-0823d50898f9.png)

**Comment by shirou** [comment]
I can not reproduce it on Windows 11 22000.613. It this comes from the difference between Windows 10 and 11?

```
Pid 19136 found: true
ok calling NewProcess for pid 19136. Result: {"pid":19136}
Pid 19136 found: true
ok calling NewProcess for pid 19136. Result: {"pid":19136}
```

![image](https://user-images.githubusercontent.com/177213/167282977-ad97bdac-9291-47ee-9570-7f4a0424f57a.png)

**Comment by AndrewSav** [comment]
Unlikely. I'm actually not running it on Windows 10. The questionnaire asked to run ver, so that's what I did, the actual OS is Windows Server 2016 Datacenter if that matters which I think it is not.

This can be reproduced by my CI/CD pipeline where I drive virtual machine templates creation from [Teamcity](https://www.jetbrains.com/teamcity/) with [Hashicorp Packer](https://www.packer.io/). Teamcity Server kicks off the process, it gets picked up by the teamcity agent on the Win2016 machine, where it starts Packer. Packer executes VM to build the image. When Packer finishes, a Virtual Box process left behimd about one time out of 5. When it does happen I can go and kill it manually, but I wanted to automated it, so I tried `gopsutil`, but it seems to fail to manipulate that process.

**Comment by shirou** [comment]
If you simply want to execute `Kill()`, how about creating a struct with just `Process{Pid: 19136}` instead of `NewProcess()` and invoke `Kill()`? NewProcess() [checks the process is active or not](https://github.com/shirou/gopsutil/blob/master/process/process_windows.go#L288).

**Comment by AndrewSav** [comment]
> If you simply want to execute `Kill()`, how about creating a struct with just `Process{Pid: 19136}` instead of `NewProcess()` and invoke `Kill()`? NewProcess() [checks the process is active or not](https://github.com/shirou/gopsutil/blob/master/process/process_windows.go#L288).

It's a bit more nuanced than that and irrelevant for the issue, but since you've asked:

There are a few agents running on the same box and we should not kill other agent processes. With this in mind we need to interrogate the process object before killing it to find the process owner and compare with our own identity, as we would not kill the other agent process. It is not just killing by ID, this is why I needed a library such as `gopsutil` in the first place.

The repro in OP is oversimplification that succinctly demonstrates the issue, the actual code use is different.

**Comment by Lomanic** [comment]
I couldn't reproduce on a Windows Server 2016 in Virtualbox either. Though I'd like to know what's going on in [PidExistsWithContext](https://github.com/shirou/gopsutil/blob/19771aaf91f3ab81482bdbfa5f5e3c35685cd3e5/process/process_windows.go#L267-L303) (where the [ErrorProcessNotRunning](https://github.com/shirou/gopsutil/blob/19771aaf91f3ab81482bdbfa5f5e3c35685cd3e5/process/process.go#L21) error seems to be raised), can you report back what's the result of the following program @AndrewSav?

```go
package main

import (
	"fmt"
	"syscall"

	"golang.org/x/sys/windows"
)

func PidExists(pid int32) (bool, error) {
	const STILL_ACTIVE = 259 // https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getexitcodeprocess
	h, err := windows.OpenProcess(windows.PROCESS_QUERY_LIMITED_INFORMATION, false, uint32(pid))
	if err == windows.ERROR_ACCESS_DENIED {
		return true, nil
	}
	if err == windows.ERROR_INVALID_PARAMETER {
		fmt.Println("A")
		return false, nil
	}
	if err != nil {
		fmt.Println("B")
		return false, err
	}
	defer syscall.CloseHandle(syscall.Handle(h))
	var exitCode uint32
	err = windows.GetExitCodeProcess(h, &exitCode)
	fmt.Println("C", exitCode)
	return exitCode == STILL_ACTIVE, err
}

func main() {
	pid := int32(6756)
	fmt.Println(PidExists(pid))
}
```

NB: we should probably use [`WaitForSingleObject`](http://msdn.microsoft.com/en-us/library/ms687032.aspx) with a 0 delay as described in https://stackoverflow.com/a/6493793

**Comment by AndrewSav** [comment]
It gives:

```
C 0
false <nil>
```

(I changed the code a bit to get the process id from the args since I no longer have that process number)

**Comment by Lomanic** [comment]
@AndrewSav can you test your program (the one in OP) with the following in `go.mod` (then run `go mod download github.com/shirou/gopsutil/v3`)?

```
replace github.com/shirou/gopsutil/v3 => github.com/Lomanic/gopsutil/v3 issue1298
```

**Comment by AndrewSav** [comment]
@Lomanic amazing:

```
PS E:\Software> ./wp.exe 8076
Pid 8076 found: true
error calling NewProcess for pid 8076: process does not exist
Pid 8076 found: true
error calling NewProcess for pid 8076: process does not exist
PS E:\Software> ./new.exe 8076
Pid 8076 found: true
ok calling NewProcess for pid 8076. Result: {"pid":8076}
Pid 8076 found: true
ok calling NewProcess for pid 8076. Result: {"pid":8076}
PS E:\Software>
```
`wp` is before the change, `new` is after the change.
