### ISSUE TITLE
process: NewProcess can not find existing PID in container

### ISSUE THREAD

**Issue by gbbr** [shirou/gopsutil#1303]
I'm having trouble with `process.NewProcess` as it can't find the process returned by `os.Getpid`. The process exists when I run `ps`:

```
root       14497  0.2  0.2 1615728 39592 pts/0   Sl+  09:27   0:01 /tmp/go-build1554220197/b001/exe/trace-agent
```

Yet, I get:
```
{"pid":14497} process does not exist
```

I have tried outputting everything returned by `process.Processes` and found the process there with a different PID. 

```
41960 /pts/0 /tmp/go-build1554220197/b001/exe/trace-agent
```

Can someone shed some light? This makes no sense to me. This is going on in a Docker container into which I've shelled into using `kubectl exec`. 

```sh
# uname -a
Linux 2100sps-7.37.0-rc.1-5ffbd48c98-72p94 5.13.0-1023-aws #25~20.04.1-Ubuntu SMP Mon Apr 25 19:28:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by gbbr** [comment]
It seems that the issue is the way that this is handled. The process PID is initially identified [here](https://github.com/DataDog/k8s-resources/pull/31530), but then later (for some reason) the code tries to resolve it in the `/host/proc` folder [here](https://github.com/shirou/gopsutil/blob/master/process/process_posix.go#L111-L115). What is the reasoning behind that? If one is trying to retrieve a process, shouldn't the code assume that the program is trying to do so in the innermost entity (the container) and not the outer one (the host) ?

Regardless, it seems to me that the current code makes it impossible to receive a local process, which is bad. There should be some way to decide whether this happens or not.

**Comment by gbbr** [comment]
> @gbbr, is procfs mounted inside the container (/proc)? Are you mounting the host system's procfs inside the container, in place of the container's own procfs (like with docker run -v /prov:/proc)?

Yes, but not quite. The host's `/proc` folder was mounted as `/host/proc` inside the container.

To be very specific, the Kubernetes configuration was like this:
```yaml
volumeMounts:
        - name: procdir
          mountPath: /host/proc
          readOnly: true
volumes:
        - hostPath:
            path: /proc
          name: procdir
```
I have since then removed this mount and everything works as expected now. But despite this, I still think that the library should pick up the most local PID and not dismiss it for the `/host/proc`.

Disclaimer: I don't have a lot of experience here so I may be misunderstanding something!

**Comment by Lomanic** [comment]
If you don't specify the `HOST_PROC` environment variable to `/host/proc`, it won't use it as procfs and will use `/proc`, I'm quite sure you set this variable and the library is working as intended.

**Comment by Lomanic** [comment]
No it shouldn't try `/proc` first (and gopsutil is not aware of the concept of containers), then you would never be able to get information about say PID 1 in `/host/proc` because it would  find `/proc/1` first.
