### ISSUE TITLE
Whether linux/loong64 can be supported?

### ISSUE THREAD

**Issue by zhangyongding** [shirou/gopsutil#1338]
../../../pkg/mod/github.com/shirou/gopsutil/v3@v3.22.7/host/host_linux.go:98:22: undefined: sizeOfUtmp
../../../pkg/mod/github.com/shirou/gopsutil/v3@v3.22.7/host/host_linux.go:103:14: undefined: sizeOfUtmp
../../../pkg/mod/github.com/shirou/gopsutil/v3@v3.22.7/host/host_linux.go:105:9: undefined: utmp

**Comment by xen0n** [comment]
In progress at #1228.

**Comment by shirou** [comment]
close by #1228 has been merged.
