### ISSUE TITLE
Environment variables in Windows container (Telegraf)

### ISSUE THREAD

**Issue by ismail-second** [shirou/gopsutil#1351]
I want to run Telegraf in a Windows container for which I created an image myself. As far as I know, Telegraf uses gopsutil to collect system metrics. However, if I run the container all works fine except the metrics collected are from the container and not from the host. 

In the README.md I saw the option to set environment variables (such as: HOST_PROC/HOST_SYS/etc.) to look at an alternative location. This is also the recommended way (as explained in the official [Telegraf Docker](https://hub.docker.com/_/telegraf/) for Linux) to monitor the host. As I am not so familiar with the Windows OS, is it possible to set an alternative location such that the we collect host metrics from a Windows Telegraf container?

**Comment by Lomanic** [comment]
Windows doesn't expose any procfs, so you can't mount it (and point the agent to it with environment variables) in the container. Sorry but this is a self-inflicted edge-case when there are a native telegraf windows binary.

**Comment by ismail-second** [comment]
> Windows doesn't expose any procfs, so you can't mount it (and point the agent to it with environment variables) in the container. Sorry but this is a self-inflicted edge-case when there are native telegraf windows binaries.

Thank you for your answer. I had such a feeling that it was not possible but opened this issue to see if I did not miss something. I get that this is an edge-case, but windows binaries were the requirement.
