### ISSUE TITLE
Allow to optionally specify process id when querying NetIOCounters

### ISSUE THREAD

**Issue by tarrychk** [shirou/gopsutil#136]
My use case is that I want to collect network statistics of various docker containers. At least in Linux every process has it's own version of /proc/net/dev in /proc/PID/net/dev. Usually those are identical but in docker containers the PID-specific net/dev only shows the container specific network namespace. This makes it very easy to parse container specific

Only thing missing is the possibility to override the static "net/dev" in NetIOCounters function with "PID/net/dev". It would be great if you could add
```
func NetIOCountersByPID(pid int, pernic bool) ([]NetIOCountersStat, error) {
  filename := common.HostProc(pid, "net/dev")
[...]
}
```
or something similar.

**Comment by shirou** [comment]
How about add `NetIOCounters` to `process` package? It is not so difficult to implement (But `net` package refactoring is required).

```
proc := process.NewProcess(somepid)
counter, err := proc.NetIOCounters()
...
```

Can this idea help your use case?

**Comment by tarrychk** [comment]
Yes, that should work fine.

Thanks for considering this.

**Comment by shirou** [comment]
@tarrychk 
I have created a PR #137 which implements `process.NetIOCounter()` Could you verify it can work on your environment?

notice: As I wrote on the PR, `ByFile` is not good for other platform. I will research about that and may change the method name. Please be patient to merging PR.

**Comment by tarrychk** [comment]
PR #137 works out great :-)
Here is how I use it:
```
cnt, err := s.dockerClient.InspectContainer(container.ID)
if err != nil {
  return nil, err
}

ctproc, err := process.NewProcess(int32(cnt.State.Pid))
if err != nil {
  return nil, err
}

net, err := ctproc.NetIOCounters(true)
if err != nil {
  return nil, err
}
```
Works like a charm.

Cya Ed

**Comment by shirou** [comment]
Sorry for late response. From my study, other platform has no feature to get NetIO per process. (If I am wrong, I hope some other people let me know), So I merged it.

I will close this issue. Feel free to re-open this issue or open a new issue. Thank you for your suggestion.
