### ISSUE TITLE
Include UBR (Update Build Revision) into Windows version number

### ISSUE THREAD

**Issue by d1ss0nanz** [shirou/gopsutil#1372]
**Is your feature request related to a problem? Please describe.**
The currently returned version string on Windows is missing the UBR (Update Build Revision).

**Describe the solution you'd like**
In PlatformInformationWithContext read the 'UBR' key from 'SOFTWARE\Microsoft\Windows NT\CurrentVersion' and append it to the version.
Instead of "10.0.19044 Build 19044" we would have "10.0.19044.1949 Build 19044".

**Describe alternatives you've considered**
None.

**Additional context**
The version withour UBR is not very useful, since it only changes in the half-yearly updates. The UBR allows to track if the Windows installation is up to date.
https://learn.microsoft.com/en-us/windows/release-health/windows11-release-information

**Comment by d1ss0nanz** [comment]
BTW: Is there a reason for the redundant build number in the version string?
"10.0.**19044** Build **19044**"

**Comment by shirou** [comment]
Thank you for the information! I have opened PR #1374. Could you take a look?

> BTW: Is there a reason for the redundant build number in the version string?

I can not remember, but I think this format comes from [ohai](https://github.com/chef/ohai/blob/de7b4f4349c767120f223b0569687187082ad73c/lib/ohai/plugins/kernel.rb#L276). You can check `Get-WmiObject Win32_OperatingSystem` and `Version` string contains a version same as BuildNumber.
