### ISSUE TITLE
Cannot import internal common package.

### ISSUE THREAD

**Issue by davidnewhall** [shirou/gopsutil#1377]
Now that `host.Warnings` has been [moved into an internal package](https://github.com/shirou/gopsutil/blob/672e2518f2ce365ab8504c9f1a8038dc3ad09cf6/internal/common/warnings.go#L5), how are we supposed to unwrap it? 

I used to do this, but my code quit working when I updated this library to the latest release today. ie. `go get ./...` in my project.
```go
	var warns *host.Warnings
	if !errors.As(err, &warns) {
		return fmt.Errorf("unable to get sensor temperatures: %w", err)
	}

	for i, w := range warns.List {
		fmt.Sprint("warning %v: %v", i+1, w)
	}
```

Re: #1347

**Comment by shirou** [comment]
oh, unwrap... Yes, you are true. Then, I will make a PR about moving back Warnings to `disk` and `host` from common. Thank you so much!
