### ISSUE TITLE
Negative total system memory (`*mem.VirtualMemoryStat`)

### ISSUE THREAD

**Issue by gekigek99** [shirou/gopsutil#1388]
**Describe the bug**
Some clients report a negative total system memory

**To Reproduce**
```go
package main

import (
	"fmt"

	"github.com/shirou/gopsutil/mem"
)

func main() {
	if memInfo, err := mem.VirtualMemory(); err != nil {
		fmt.Println(-1, err.Error())
	} else {
		fmt.Println(int(memInfo.Total))
	}
}
```

**Expected behavior**
return a non negative system memory, or find an explanation of why this is happening.

**Environment (please complete the following information):**
environment of compilation or production? cause I don't know the environment of clients that are using my software (I have many running in a docker env (in ptero))

**Additional context**
`set GOOS=linux && set GOARCH=amd64 && go build .`

_If you need more info ask me, I'll try to clarify..._

**Comment by shirou** [comment]
From your code, I think `-1` is because `mem.VirtualMemory()` returned an error. What error happened?

**Comment by gekigek99** [comment]
No the problem is that clients report a big negative value (different from -1 which I reserve for an "error")

42 clients out of 1729 have this problem (2.4%)

I only have a few info about the clients.

But I'm sure that there wasn't an error while getting the memstats, otherwise -1 would have been logged.

**Comment by shirou** [comment]
We, of course, do not know your client's information. We cannot do anything without information about errors.

**Comment by gekigek99** [comment]
Yeah i completely agree.

But since no error is reported and a negative number (memInfo.total) is returned, I wanted to know if this was a known thing and if there was a way to understand more on what is happening (even with an incriminated client in front of me I could not report the error, as `VirtualMemory()` doesnt throw one)

**Comment by Lomanic** [comment]
[`mem.VirtualMemoryStat.Total`](https://godocs.io/github.com/shirou/gopsutil/v3/mem#VirtualMemoryStat) is defined as a uint64 value, so `mem.VirtualMemory()` can't return a negative value. To me, the casting to an `int` results in an overflow in your code ([for values bigger than `math.Int64`](https://go.dev/play/p/epok0G2pkzO)).

@gekigek99 if you could provide us a [`/proc/meminfo`](https://github.com/shirou/gopsutil/blob/835767a611173070e0740ced4d7dc3cf0c629668/mem/mem_linux.go#L59) from a host where you get a negative value, we could be sure.

**Comment by gekigek99** [comment]
> if you could provide us a [/proc/meminfo](https://github.com/shirou/gopsutil/blob/835767a611173070e0740ced4d7dc3cf0c629668/mem/mem_linux.go#L59) from a host where you get a negative value, we could be sure.

I will ask my collaborator to execute the test script on the machine with the biggest memory he has together with `/proc/meminfo`.

> [mem.VirtualMemoryStat.Total](https://godocs.io/github.com/shirou/gopsutil/v3/mem#VirtualMemoryStat) is defined as a uint64 value, so mem.VirtualMemory() can't return a negative value. To me, the casting to an int results in an overflow in your code ([for values bigger than math.Int64](https://go.dev/play/p/epok0G2pkzO)).

Yeah I tought of that... but I would be impressed by our human technology (let alone some server of this kind using my program) if a ram of 9223 PB was the problem LOL XD....

Jokes aside, maybe this explanation can be used on the database causing the overflow issue: I'll ask my collaborator about it.

**Comment by gekigek99** [comment]
I verified on serverside/database and apparently it's my golang application that is reporting a negative mem value.

this is the data I think might be useful:
| "machine_os" | "machine_arch" | "machine_cpu_model" | "machine_cpu_vendor" | "machine_mem" |
| --- | --- | --- | --- | --- |
| "linux" | "arm" | "ARMv7 Processor rev 3 (v7l)" | "ARM" | -229990400 |
| "linux" | "386" | "AMD EPYC 7702P 64-Core Processor" | "AuthenticAMD" | -358215680 |
| "windows" | "386" | "Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz" | "GenuineIntel" | -229867520 |
| "windows" | "386" | "AMD Ryzen 7 1700 Eight-Core Processor          " | "AuthenticAMD" | -85176320 |
| ... | ... | ... | ... | ... |

_i have ~50 clients more that reported a negative value if you want I can share the full table_

----

_If you want more data ask but I don't think I have anything useful left._

_If you have some test I can try tell me, but again this are clients reporting, I cannot test myself locally._

**Comment by Lomanic** [comment]
I assumed from 

>  `set GOOS=linux && set GOARCH=amd64 && go build .`

you compiled your program to 64 bit but your table seems to show it's executing on 32 bit arch (arm) or 32 bit mode (386 on windows), where `int` will be `int32`, much easier to overflow. See [this SO answer](https://stackoverflow.com/a/51853321) to check for the size of `int` according to GOARCH.

Closing as there's no issue in gopsutil here.

**Comment by gekigek99** [comment]
@Lomanic but this doesn't mean that `memInfo.Total` is int32 on arch 386? It's still int64 no?

If i replace int(memInfo.Total) with int64(memInfo.Total) it should also work on a 32bit arch correct?

**Comment by gekigek99** [comment]
yes I tested it and using int64 instead of int works also on 32bit arch
