### ISSUE TITLE
invalid memory address or nil pointer dereference in disk_windows.go

### ISSUE THREAD

**Issue by Nyx2022** [shirou/gopsutil#1399]
![image](https://user-images.githubusercontent.com/51039208/208613905-5904b648-d483-4821-a869-c066afc34556.png)
there is a bug,wish you can fix it by check if i ==nil

**Comment by shirou** [comment]
Perhaps that is related to #1396.

**Comment by Nyx2022** [comment]
> Perhaps that is related to #1396.

yes,can it be fixed in 3.22.12?
