### ISSUE TITLE
Windows 11: `panic: runtime error: when disk.Partitions(false)

### ISSUE THREAD

**Issue by ahmadissa** [shirou/gopsutil#1405]
**Describe the bug**
Error when getting disk portions on windows
**To Reproduce**
```go
disk.Partitions(false)
```

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Environment (please complete the following information):**
 - [ ] Windows: windows 11
 - [ ] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
 - [ ] Mac OS: [paste the result of `sw_vers` and `uname -a`
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xf3018a]

goroutine 70 [running]:
github.com/shirou/gopsutil/v3/disk.PartitionsWithContext({0xc000496630?, 0x40?}, 0x0?)
        github.com/shirou/gopsutil/v3/disk/disk_windows.go:107 +0x20a

```

**Comment by shirou** [comment]
This might be duplicated issue with #1396.

**Comment by ahmadissa** [comment]
@shirou  thanks for the reply, it is duplicate, closing it
