### ISSUE TITLE
NetConnections doesn't handle multiple threads.

### ISSUE THREAD

**Issue by solarisfire** [shirou/gopsutil#143]
NetConnections doesn't handle multiple threads listening on the same port correctly.

For example, Apache running multiple threads listening on 80 & 443 gives:

[{"fd":4,"family":10,"type":1,"localaddr":{"ip":"*","port":80},"remoteaddr":{"ip":"","port":0},"status":"LISTEN","pid":10493} {"fd":6,"family":10,"type":1,"localaddr":{"ip":"*","port":443},"remoteaddr":{"ip":"","port":0},"status":"LISTEN","pid":10493} {"fd":4,"family":10,"type":1,"localaddr":{"ip":"*","port":80},"remoteaddr":{"ip":"","port":0},"status":"LISTEN","pid":10495} {"fd":6,"family":10,"type":1,"localaddr":{"ip":"*","port":443},"remoteaddr":{"ip":"","port":0},"status":"LISTEN","pid":10495} {"fd":4,"family":10,"type":1,"localaddr":{"ip":"*","port":80},"remoteaddr":{"ip":"","port":0},"status":"LISTEN","pid":10497} {"fd":6,"family":10,"type":1,"localaddr":{"ip":"*","port":443},"remoteaddr":{"ip":"","port":0},"status":"LISTEN","pid":10497} {"fd":4,"family":10,"type":1,"localaddr":{"ip":"*","port":80},"remoteaddr":{"ip":"","port":0},"status":"LISTEN","pid":10558} {"fd":6,"family":10,"type":1,"localaddr":{"ip":"*","port":443},"remoteaddr":{"ip":"","port":0},"status":"LISTEN","pid":10558} {"fd":4,"family":10,"type":1,"localaddr":{"ip":"*","port":80},"remoteaddr":{"ip":"","port":0},"status":"LISTEN","pid":10560} {"fd":6,"family":10,"type":1,"localaddr":{"ip":"*","port":443},"remoteaddr":{"ip":"","port":0},"status":"LISTEN","pid":10560} {"fd":4,"family":10,"type":1,"localaddr":{"ip":"*","port":80},"remoteaddr":{"ip":"","port":0},"status":"LISTEN","pid":14003} {"fd":6,"family":10,"type":1,"localaddr":{"ip":"*","port":443},"remoteaddr":{"ip":"","port":0},"status":"LISTEN","pid":14003} {"fd":4,"family":10,"type":1,"localaddr":{"ip":"*","port":80},"remoteaddr":{"ip":"","port":0},"status":"LISTEN","pid":23044} {"fd":6,"family":10,"type":1,"localaddr":{"ip":"*","port":443},"remoteaddr":{"ip":"","port":0},"status":"LISTEN","pid":23044} {"fd":4,"family":10,"type":1,"localaddr":{"ip":"*","port":80},"remoteaddr":{"ip":"","port":0},"status":"LISTEN","pid":23046} {"fd":6,"family":10,"type":1,"localaddr":{"ip":"*","port":443},"remoteaddr":{"ip":"","port":0},"status":"LISTEN","pid":23046} {"fd":4,"family":10,"type":1,"localaddr":{"ip":"*","port":80},"remoteaddr":{"ip":"","port":0},"status":"LISTEN","pid":28452} {"fd":6,"family":10,"type":1,"localaddr":{"ip":"*","port":443},"remoteaddr":{"ip":"","port":0},"status":"LISTEN","pid":28452}]

**Comment by shirou** [comment]
Sorry for late response.

It's seems these results includes various pids. And if same pids, there are different port. So I think this result is not showing thread information and not wrong. How do you think?

**Comment by shirou** [comment]
@solarisfire `lsof` is replaced on Linux. Could you check it out? Or, if you use other architecture, please be patient...

**Comment by shirou** [comment]
Close this issue. If you have any other concern, please re-open this issue. Thank you!
