### ISSUE TITLE
Reference actions by commit SHA

### ISSUE THREAD

**Issue by gabibguti** [shirou/gopsutil#1458]
**Is your feature request related to a problem? Please describe.**
Referencing actions by commit SHA in workflows, guarantees you are using an immutable version. In contrast, actions referenced by tags and branches are vulnerable to attacks, such as the tag being moved to a malicious commit, a malicious commit being pushed to the branch or typosquatting.

**Describe the solution you'd like**
Analyze each workflow searching for actions referenced by tags and branches and replacing them by commit SHAs to prevent these attacks.

**Describe alternatives you've considered**
None.

**Additional context**
It's good to highlight that although there are pros and cons for using each reference (tags, branches and SHAs), GitHub acknowledges that [using commit SHAs is more reliable](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#using-shas), as does [Scorecard](https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies) security tool.

Hi again! I'm Gabriela, I recently recommended https://github.com/shirou/gopsutil/issues/1444, and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

If you agree, I can open a PR!

**Comment by shirou** [comment]
Great suggestion. I agree to use SHA for GitHub actions.
Could you open a PR for it? Thank you so much!
