### ISSUE TITLE
Potential leak in sleep.go

### ISSUE THREAD

**Issue by hhheiaenia** [shirou/gopsutil#1474]
I notice the ctx.Done() needs a cancel function to unblock the statement of ctx.Done in https://github.com/shirou/gopsutil/blob/master/internal/common/sleep.go#LL13C1-L13C1,
but I never find the cancel function in its invocation.  So if this may leak the goroutine where the ctx.Done() locates? 

Maybe what I said is not right, thank you.

**Comment by shirou** [comment]
After some searching, I thought your point was correct. Thank you for the suggestion, and I have opened a PR for fix it, #1475. Could you check it out? Thank you!
