### ISSUE TITLE
Why get processName from `/proc/(pid)/comm` should be at most 14 characters ?

### ISSUE THREAD

**Issue by JimChenWYU** [shirou/gopsutil#1485]
**Describe the bug**
Why get processName from `/proc/(pid)/comm` should be at most 14 letters ?

Refs https://github.com/shirou/gopsutil/blob/master/process/process_linux.go#L795

**To Reproduce**
1. My python script named `admin_worker.py`,  just example
```python
#!/usr/local/easyops/python/bin/python
# -*- coding: utf-8 -*-

from time import sleep

while True:
  print("process...")
  sleep(1)
```

2. Start `admin_worker.py`
```shell
$ chmod +x admin_worker.py
$ ./admin_worker.py
```

3. In Linux, running my go program
```go
// `pid` should be found by `ps` command in machine.

proce, _ := process.NewProcess(int32(pid))
name, _ := proce.Name()
fmt.Println(name)
```
I find the `name` is `/usr/local/easyops/python/bin/python`

**Expected behavior**
I expect the name is `admin_worker.py`, because i use `cat /proc/(pid)/comm` in machine, i get my expected value. 

**Environment (please complete the following information):**
 - [ ] Windows: [paste the result of `ver`]
 - [x] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
 - [ ] Mac OS: [paste the result of `sw_vers` and `uname -a`
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

os-release
```
```

uname -a
```
```

**Additional context**
[Cross-compiling? Paste the command you are using to cross-compile and the result of the corresponding `go env`]

No.

**Comment by shirou** [comment]
Umm. I faintly think there was a reason, but I can't recall the details, and I can not find any comments from GitHub. If no reason, we can remove the limitation.

**Comment by Lomanic** [comment]
An easy reproducer for python psutil

```bash
TMPDIR=$(mktemp -d)
python3 -m venv "$TMPDIR/venv"
"$TMPDIR/venv/bin/pip3" install psutil
cat > "$TMPDIR/loooooooooooooooooooong.py" <<EOF
#!$TMPDIR/venv/bin/python3
import psutil
print(psutil.Process().name())
EOF
chmod +x "$TMPDIR/loooooooooooooooooooong.py"
cp -a "$TMPDIR/loooooooooooooooooooong.py" "$TMPDIR/short.py"
"$TMPDIR/loooooooooooooooooooong.py"
# returns loooooooooooooo
"$TMPDIR/short.py"
# returns short.py
```

psutil uses `/proc/$PID/stat` on linux, see https://github.com/giampaolo/psutil/blob/962cb9ad58ca3bc21b20130f435f8d507d931051/psutil/_pslinux.py#L1745 and https://github.com/giampaolo/psutil/blob/962cb9ad58ca3bc21b20130f435f8d507d931051/psutil/_pslinux.py#L1686. `man proc` documents this property in the `/proc/$PID/stat` file with
```
              (2) comm  %s
                     The  filename  of  the executable, in parentheses.  Strings longer than TASK_COMM_LEN (16) characters (including the terminating null byte) are silently truncated.
                     This is visible whether or not the executable is swapped out.
```

I can't test psutil behaviour on bsd (including darwin), where gopsutil behaviour (aligned with linux, using cmdline as a fallback) is also probably similarly broken (falling back to `basename(cmdline[0])`, see #796/#795.

What should be done? This is misaligned with psutil (and inconsistent) but changing this behaviour in gopsutil to be the same as in psutil will break backward compatibility downstream.

**Comment by JimChenWYU** [comment]
Refs
- https://gitlab.com/procps-ng/procps/-/commit/3e1c00d051ae4a8319df7714d0545b4b7aa81557
- https://gitlab.com/procps-ng/procps/-/commit/bb272580a6f3c192c61e307f9e341514d892d06e
