### ISSUE TITLE
darwin/386 not suported

### ISSUE THREAD

**Issue by SchumacherFM** [shirou/gopsutil#149]
Hey ho!

thanks for the nice library!

When I run the go build on my repo https://github.com/SchumacherFM/mediamock I'll get compile errors for darwin/386.

I'm using the latest commit from your repo.

```
me at MBP in ~/GoPro/src/github.com/SchumacherFM/mediamock on master [+!]
$ GOOS=darwin GOARCH=386 go build .
# github.com/SchumacherFM/mediamock/vendor/github.com/shirou/gopsutil/process
vendor/github.com/shirou/gopsutil/process/process_darwin.go:317: undefined: KinfoProc
vendor/github.com/shirou/gopsutil/process/process_darwin.go:332: undefined: KinfoProc
vendor/github.com/shirou/gopsutil/process/process_darwin.go:333: invalid expression unsafe.Sizeof(k)
vendor/github.com/shirou/gopsutil/process/process_darwin.go:362: undefined: KinfoProc
vendor/github.com/shirou/gopsutil/process/process_darwin.go:363: undefined: KinfoProc
vendor/github.com/shirou/gopsutil/process/process_darwin.go:374: undefined: KinfoProc
vendor/github.com/shirou/gopsutil/process/process_darwin.go:376: undefined: KinfoProc
vendor/github.com/shirou/gopsutil/process/process_darwin.go:377: invalid expression unsafe.Sizeof(procK)
```

Maybe you can add build tags to exclude it some how from darwin/386 builds. I don't know if it's worth it to support such an old system ... 

Thanks!

**Comment by shirou** [comment]
If you copy `process_darwin_amd64.go` to  `process_darwin_386.go`, you can build. But it might be not work because struct size is different.
Since I can not get i386/darwin machine, I can not get struct size on 386 environment.  FreeBSD/Linux on i386 can be get from AWS, but no darwin. 

I can just add `process_darwin_386.go` to the repository, with warning comment. Do you really needs to darwin/386?

**Comment by SchumacherFM** [comment]
The best way would be to remove `process_darwin_386.go` and only provide mock functions. Once some one complains that he/she really needs those features ... you can still implement them properly with the guy owing the darwin/386 machine. What do you think?

**Comment by shirou** [comment]
process files are separated to 
- process_darwin.go
  - architecture independent
- process_drawin_amd64.go
  - have only struct definition which is architecture dependent

If I change process_darwin.go to architecture dependent as you suggested, become complicated.

**Comment by shirou** [comment]
Since I have no 386/darwin, I can not implement. If someone make a good PR, I will merge it. Thank you.
