### ISSUE TITLE
proc.MemoryInfo() rss sizes don't match top

### ISSUE THREAD

**Issue by vrecan** [shirou/gopsutil#150]
proc.MemoryInfo() output says my process is 9mb while top says the same process RES is 35mb. It also never seems to grow, if I write a memory grow it stays between 8 - 9mb while top reports it's over 1-2gb.

I am going to dig more into this but I wanted to see if anyone else is seeing this behavior? When I originally implemented these calls I got very similar results to top.

This is on centos 7 on a quadcore xeon box.

**Comment by vrecan** [comment]
ok I figured it out but I think it's still a bug. I had done a change where I was reusing the Process object that you get from NewProcess and calling MemoryInfo(). When I do this I get the same results every time. 

What I did to fix it was just rebuild the Process object every 5 seconds and then I get the correct results.

**Comment by shirou** [comment]
Could you provide arch/os/distro information? I dig it later.

Thanks!

**Comment by vrecan** [comment]
CPU: Intel(R) Xeon(R) CPU E5-2450 0 @ 2.10GHz
OS: Centos 7
output of uname -a:
Linux lrdx0000 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vrecan** [comment]
if I call MemoryInfoEx() instead it doesn't have this issue!

**Comment by vrecan** [comment]
pr fixes the issue! :)
