### ISSUE TITLE
arch linux host version `"rolling"` -> `rolling`

### ISSUE THREAD

**Issue by jxsl13** [shirou/gopsutil#1502]
**Describe the bug**

The string contains quotes. 
Would be great if it did not contain those.

Arch Linux
```
{
 "hostname": "arch",
 "uptime": 29735,
 "bootTime": 1691724924,
 "procs": 228,
 "os": "linux",
 "platform": "arch",
 "platformFamily": "arch",
 "platformVersion": "\"rolling\"",
 "kernelVersion": "6.4.8-arch1-1",
 "kernelArch": "x86_64",
 "virtualizationSystem": "",
 "virtualizationRole": "",
 "hostId": "0aff3c62-383e-11ee-b15e-67cecb7ee508"
}
```

**To Reproduce**
```go
package main

import (
	"encoding/json"
	"fmt"
	"log"

	"github.com/shirou/gopsutil/v3/host"
)

func main() {
	info, err := host.Info()
	if err != nil {
		log.Fatalln(err)
	}

	data, _ := json.MarshalIndent(info, "", " ")
	fmt.Println(string(data))

}
```

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Environment (please complete the following information):**
 - [ ] Windows: [paste the result of `ver`]
 - [x] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
 - [ ] Mac OS: [paste the result of `sw_vers` and `uname -a`
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

```
$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

````
$ uname -a
Linux arch 6.4.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Aug 2023 16:02:01 +0000 x86_64 GNU/Linux
````

**Additional context**
[Cross-compiling? Paste the command you are using to cross-compile and the result of the corresponding `go env`]

**Comment by shirou** [comment]
Could you show us the `/etc/lsb-release` file contents and the output of `/usr/bin/lsb_release` command?

**Comment by jxsl13** [comment]
```
$ cat /etc/lsb-release
DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
```

```
$ /usr/bin/lsb_release
LSB Version:    n/a
```
