### ISSUE TITLE
windows's swap mem wrong

### ISSUE THREAD

**Issue by chenjie199234** [shirou/gopsutil#1511]
gopsutil version:v3.23.7
I set the swap mem to 0 on windwos
But,when i use mem.SwapMemory() to get the info,there is still data return.
![1](https://github.com/shirou/gopsutil/assets/29348971/d63426c3-9abf-4095-9381-ad8b12ad75fa)
![2](https://github.com/shirou/gopsutil/assets/29348971/dc937d0f-4d68-48b1-81ac-b7e0743608bd)

**Comment by shirou** [comment]
psutil uses`Paging File(_Total)\\% Usage` via Performance Counter and then [calculating the amount](https://github.com/giampaolo/psutil/blob/c034e6692cf736b5e87d14418a8153bb03f6cf42/psutil/_pswindows.py#L257-L269). I think this is the way gopsutil should be done.
