### ISSUE TITLE
Please post CI results to PRs

### ISSUE THREAD

**Issue by walles** [shirou/gopsutil#154]
Hi!

Look at any merged PR.

There's no indication that any tests / validation / build has been run.

Could you please add CI builds that report their results to the Github PRs?

On OS X the unit tests don't pass so I suggest:
* Build on OS X
* Run unit tests on Linux

Static code analysis would be good as well of course, but anything would be nice really!

  Regards /Johan

**Comment by walles** [comment]
For an example of how the lack of CI was bad, merging #138 broke the `process.Test_Pids_Fail()` test case on Darwin.

If @sparrc had been informed about this breakage before merging, his PR would most likely have looked different.

**Comment by shirou** [comment]
Thank you for your suggestion. I added `Pull Request` on the webhook settings.

But tests will be run on only Linux/Ubuntu. Tests run with `GOOS=darwin`, `GOOS=freebsd` and so on, so build can be checked failed or success. However, it not guarantee works fine on that environment.  

Since we can not avoid all of mistakes by a CI, I think collaborators like you are very important and I appreciate all time.

**Comment by walles** [comment]
I just pushed a new change to https://github.com/shirou/gopsutil/pull/153 but no CI run was triggered. Can you review the settings again?

**Comment by shirou** [comment]
hmm. Network, CI server or something currently wrong, I think.

<img width="431" alt="2016-02-12 22 11 16" src="https://cloud.githubusercontent.com/assets/177213/13007738/9c1c985c-d1d5-11e5-999c-0db7c603fdf7.png">

**Comment by shirou** [comment]
I have started to switch CircleCI on #155. It seems work fine. I will merge after fixing the fail.

**Comment by walles** [comment]
Thanks, great improvement!

You said earlier in this thread that "Tests run with `GOOS=darwin`, `GOOS=freebsd` and so on, so build can be checked failed or success".

However, in the output from building #155...
https://circleci.com/gh/shirou/gopsutil/7
... I can't see any cross compiles.

Are they there?

**Comment by shirou** [comment]
Oops. I forget to add these builds same as drone.io https://drone.io/github.com/shirou/gopsutil/315. 
Thank you for notice me!

**Comment by walles** [comment]
But comments of PR #155 say: "shirou merged commit 614df95 into master 2 hours ago `1 check passed`"

If `2 checks` are done (both Circle and Drone), shouldn't the PR say `2 checks passed`?

**Comment by walles** [comment]
Ah, just found #156, that answers my questions.

Thanks!
