### ISSUE TITLE
proc.openfiles() crash

### ISSUE THREAD

**Issue by RRancio** [shirou/gopsutil#1543]
**Describe the bug**
you forgot a err handle

**To Reproduce**
```go
case <-ch:
			fileInfo, _ := os.Stat(fileName)
			// if err != nil {
			// 	continue
			// }
			if fileInfo.IsDir() {
				continue
			}
```

**Expected behavior**
crashes :V
**Environment (please complete the following information):**
![image](https://github.com/shirou/gopsutil/assets/80014347/3cc3a2f1-33c0-400a-893c-80326baab738)

**Additional context**
![image](https://github.com/shirou/gopsutil/assets/80014347/9866253f-efb5-4dfb-9d38-c619d578c2c6)

_btw file is process_windows.go_

**Comment by shirou** [comment]
Could you update to the latest version `v3.23.9` and try it again? The current version seems too old.
