### ISSUE TITLE
cpu.parseStatLine bug

### ISSUE THREAD

**Issue by heixiaoma** [shirou/gopsutil#1557]
device:iphone 14 pro

![IMG_3081](https://github.com/shirou/gopsutil/assets/10923974/4cf400b2-8769-49a8-a3cf-f9bc08128a1f)

**Comment by shirou** [comment]
What tool are you using ? [iSH Shell](https://apps.apple.com/jp/app/ish-shell/id1436902243) or else?
And could you share a reproducible source code?

**Comment by heixiaoma** [comment]
I think we can close this issue now. I am using version v3 and this problem no longer occurs. Thank you for your reply, buddy

**Comment by heixiaoma** [comment]
```
func SysInfo() string {
	defer func() {
		if err := recover(); err != nil {
		}
	}()
	info := bean.SysInfo{}
	v, err := mem.VirtualMemory()
	if err == nil {
		info.TotalMem = v.Total
		info.UseMem = v.Used
	}
	start, err := cpu.Times(false)
	if err == nil {
		var totalUsed float64
		// 计算每个 CPU 核心的使用率并相加
		for i := range start {
			totalUsed += (start[i].Total() - start[i].Idle) / start[i].Total()
		}
		info.CpuRate = (totalUsed / float64(len(start))) * 100.0
	}
	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	// 程序占用的总内存
	totalMemory := m.Sys
	// 程序当前使用的内存
	usedMemory := m.Alloc

	info.HpTotalMem = float64(totalMemory)
	info.HpUseMem = float64(usedMemory)
	marshal, _ := json.Marshal(info)
	return string(marshal)
}
```

I will encounter this issue with the v2 version of the same code, but not with v3

**Comment by heixiaoma** [comment]
![ac7c4fc22b1a14e81faf0b06ec2cea4](https://github.com/shirou/gopsutil/assets/10923974/9706e74e-40dc-4eb4-b9c2-97bc80383a4d)

app logo

**Comment by shirou** [comment]
> I think we can close this issue now. I am using version v3 and this problem no longer occurs.

Thank you for the information and code. v2 is not maintained anymore.
