### ISSUE TITLE
The host.Info() function is unable to correctly identify CentOS Stream 8.

### ISSUE THREAD

**Issue by ssongliu** [shirou/gopsutil#1571]
You're welcome! It seems there's an issue when attempting to retrieve the host version on a CentOS Stream 8 system using host.Info(). The function returns the release version as CentOS 8 instead of correctly identifying it as CentOS Stream 8.

![image](https://github.com/shirou/gopsutil/assets/73214554/6739affc-7e3c-4c8b-a39a-a838e764c3a0)

**Comment by Lomanic** [comment]
This is still a rhel 8, Stream is just its codename or flavour or commercial name. Its `/etc/os-release` file doesn't even mention Stream.
