### ISSUE TITLE
stat.Rdev (variable of type uint32) as uint64 

### ISSUE THREAD

**Issue by zzdboy** [shirou/gopsutil#1574]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
```go version go1.21.5 windows/amd64
// paste example code reproducing the bug you are reporting
```

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Environment (please complete the following information):**
 - [ ] Windows: [paste the result of `ver`]
 - [X] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
 - [ ] Mac OS: [paste the result of `sw_vers` and `uname -a`
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

**Additional context**
[Cross-compiling? Paste the command you are using to cross-compile and the result of the corresponding `go env`]

E:\Go\pkg\mod\github.com\shirou\gopsutil\v3@v3.23.12\disk\disk_linux.go:510:22: cannot use stat.Rdev (variable of type uint32) as uint64 value in argument to unix.Major
E:\Go\pkg\mod\github.com\shirou\gopsutil\v3@v3.23.12\disk\disk_linux.go:511:22: cannot use stat.Rdev (variable of type uint32) as uint64 value in argument to unix.Minor
E:\Go\pkg\mod\github.com\shirou\gopsutil\v3@v3.23.12\disk\disk_linux.go:544:22: cannot use stat.Rdev (variable of type uint32) as uint64 value in argument to unix.Major
E:\Go\pkg\mod\github.com\shirou\gopsutil\v3@v3.23.12\disk\disk_linux.go:545:22: cannot use stat.Rdev (variable of type uint32) as uint64 value in argument to unix.Minor

**Comment by shirou** [comment]
Could you show us those? Thank you.
1. reproducible code
2. contents of `/etc/os-release` and the result of `uname -a`
3. what if #1575 applied

**Comment by phuonganh2601** [comment]
Same problem when build project for Mipsle.
Temporarily downgrade to version v3.23.10 and problem solved.
