### ISSUE TITLE
docker container monitor host resource and usage

### ISSUE THREAD

**Issue by wade-liwei** [shirou/gopsutil#1613]
hi there

Can I run the project in docker container to monitor host resource and usage?

**Comment by davidnewhall** [comment]
You'll see whatever the host exposes to the container. We have many users that run [our app](https://github.com/Notifiarr/notifiarr) in a container and it reports host data without a problem.

Much of the data in the following screenshot comes from this package. The interface displayed is the built-in web UI for a Go app running in docker.
![Screenshot 2024-07-10 at 6 30 11 PM](https://github.com/shirou/gopsutil/assets/2402929/7dddfb80-aa7c-4248-86dc-05be42c62352)

**Comment by wade-liwei** [comment]
thank you.

**Comment by wade-liwei** [comment]
thank you.

**Comment by davidnewhall** [comment]
No prob. Hit up our Discord if you need any pointers.

**Comment by Lomanic** [comment]
Mount the host's `/proc` directory to some directory inside the container and have gopsutil use this mounted dir with the `HOST_PROC` environment variable, as described in [https://github.com/shirou/gopsutil#usage](https://github.com/shirou/gopsutil/blob/edff3add948e8e8e7815427468a6893afa38f2e7/README.md#usage)
