### ISSUE TITLE
runtime: program exceeds 10000-thread limit

### ISSUE THREAD

**Issue by RunningFaster** [shirou/gopsutil#1644]
**Describe the bug**

**runtime: program exceeds 10000-thread limit**

When I use the toolkit to get disk usage, I get an error at the top.

**To Reproduce**
```go
"github.com/shirou/gopsutil/disk"

parts, error := disk.Partitions(true)
	if error == nil {
		for _, v := range parts {
			diskInfo, _ := disk.Usage(v.Mountpoint)  // Error
			if diskInfo == nil {
				continue
			}
		}
	}
```

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Environment (please complete the following information):**
 - [ ] Windows: [paste the result of `ver`]
 - [*] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
 Linux s-6160 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - [ ] Mac OS: [paste the result of `sw_vers` and `uname -a`
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

**Additional context**
[Cross-compiling? Paste the command you are using to cross-compile and the result of the corresponding `go env`]

```shell
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/gopath/pkg/mod"
GONOPROXY="git.mycompany.com,github.com/my/private"
GONOSUMDB="git.mycompany.com,github.com/my/private"
GOOS="linux"
GOPATH="/home/gopath"
GOPRIVATE="git.mycompany.com,github.com/my/private"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.7"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
```

**Comment by davidnewhall** [comment]
Providing the length of `parts`, how far into that slice it gets before bombing out, and which partition caused the overload might be helpful.

**Comment by hitzhangjie** [comment]
maybe there's thread blocking, for example call this code block too many times.
