### ISSUE TITLE
linux: process.NewProcess() slow

### ISSUE THREAD

**Issue by cgilling** [shirou/gopsutil#166]
I was testing this library and found that (at least on linux) `process.NewProcess` ends up being pretty slow because it calls [p.fillFromStatus](https://github.com/shirou/gopsutil/blob/master/process/process_linux.go#L70) to check and see if its a valid process. It seems like simply stating the `/proc/[pid]` file would be enough to check and see if the pid is valid

It seems like the only function that depends on it having been called is [Name()](https://github.com/shirou/gopsutil/blob/master/process/process_linux.go#L70) which I would think could be managed differently (for example one could check to see if `p.name == ""` and if so then call `p.fillFromStatus`.

I'm not sure if this would be an acceptable change but would be helpful for me as I would like to use this library to scan running processes for a certain process with specific command line arguments, and having `p.fillFromStatus` every time slows this down quite a bit.

If this is acceptable I could write up a pull request.

**Comment by shirou** [comment]
Since #168 is merged, I close this issue. If you want to let me know something more, please feel free to re-open.

Thank you for your suggestion and great PR!

**Comment by cgilling** [comment]
thanks for the quick responses, makes working on the project even across timezones quite nice.
