### ISSUE TITLE
Issue with process.Percent Data: Erroneous Inclusion of iowait in CPU Utilization Calculation

### ISSUE THREAD

**Issue by TheBestLL** [shirou/gopsutil#1690]
Based on the operational logic defined in psutil, iowait should not be considered in the calculations for CPU utilization. However, it appears that process.Percent is still incorporating iowait, leading to potentially inaccurate assessments of CPU activity. This could affect performance monitoring and analysis where precise CPU usage metrics are critical. It's crucial to ensure that process.Percent reflects only the active CPU usage, excluding any idle/wait times associated with IO operations.

Could we examine the implementation to confirm if iowait is mistakenly included in the CPU usage calculation and rectify this if necessary? This adjustment would align with the intended functionality of accurately reflecting CPU usage metrics, essential for system performance evaluations.
[https://github.com/shirou/gopsutil/blob/master/process/process.go#L324](https://github.com/shirou/gopsutil/blob/edff3add948e8e8e7815427468a6893afa38f2e7/process/process.go#L324)

**Comment by TheBestLL** [comment]
https://github.com/shirou/gopsutil/issues/902

**Comment by TheBestLL** [comment]
https://github1s.com/giampaolo/psutil/blob/c034e6692cf736b5e87d14418a8153bb03f6cf42/psutil/__init__.py#L994

**Comment by TheBestLL** [comment]
The processing logic updates with the implementation logic of psutil

**Comment by Lomanic** [comment]
Fixed in #1692 it looks like
