### ISSUE TITLE
[process][unix] `err != nil` when calling process.Children() for a process without child processes

### ISSUE THREAD

**Issue by lichunqiang** [shirou/gopsutil#1698]
**Describe the bug**
Calling `Children()` on a process without child processes returns a non-nil err

the source code uses `common.CallPgrepWithContext` which [calls `pgrep -P $PID`](https://github.com/shirou/gopsutil/blob/74cb4037306917993ef750349472769e7c298e66/internal/common/common_unix.go#L45). If input pid is without child processes, `pgrep` exit code is `1`, the function call returns error with `exits status 1`

**To Reproduce**
```go
// paste example code reproducing the bug you are reporting
```

**Expected behavior**
The function should return ErrorNoChildren?

**Environment (please complete the following information):**
 - [ ] Windows: [paste the result of `ver`]
 - [ ] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
 - [ ] Mac OS: [paste the result of `sw_vers` and `uname -a`
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

**Additional context**
[Cross-compiling? Paste the command you are using to cross-compile and the result of the corresponding `go env`]

**Comment by Lomanic** [comment]
To me this was introduced in #1231 (meant to handle places where `pgrep` is missing).

As pgrep returns 1 (without any message in stderr/out) both when there's no child process found or the parent process doesn't exist (`pgrep -P $$; echo $?` vs `pgrep -P 3; echo $?`), gopsutil should get rid of pgrep and follow psutil, [like this on linux](https://github.com/giampaolo/psutil/blob/8d943015ffce86de31d9494ffa3a1eae7dd91719/psutil/_pslinux.py#L1687-L1706) ([calls ppid() on all processes on all other posix OSes](https://github.com/giampaolo/psutil/blob/8d943015ffce86de31d9494ffa3a1eae7dd91719/psutil/__init__.py#L259-L274)).

As an aside, I think this ErrorNoChildren error should not exist in the first place, the Children() function should simply return a nil error and an empty slice as this is not an error.
