### ISSUE TITLE
process.CPUPercent always return 0

### ISSUE THREAD

**Issue by tianlin** [shirou/gopsutil#172]
Hi, I find process.CPUPercent will always return 0 when interval > 0. Reason is here：
	cpuTimes, err := p.CPUTimes()
	if err != nil {
		return 0, err
	}
	now := time.Now()

	if interval > 0 {
		p.lastCPUTimes = cpuTimes
		p.lastCPUTime = now
		time.Sleep(interval)
		cpuTimes, err = p.CPUTimes()
		if err != nil {
			return 0, err
		}
	} else {
		if p.lastCPUTimes == nil {
			// invoked first time
			p.lastCPUTimes = cpuTimes
			p.lastCPUTime = now
			return 0, nil
		}
	}

	numcpu := runtime.NumCPU()
	delta := (now.Sub(p.lastCPUTime).Seconds()) * float64(numcpu)
	ret := calculatePercent(p.lastCPUTimes, cpuTimes, delta, numcpu)
	p.lastCPUTimes = cpuTimes
	p.lastCPUTime = now
	return ret, nil
when interval > 0, now & p.lastCPUTime is same.

**Comment by raviparimi** [comment]
Hi @shirou Are you actively working on this issue? I spent some time digging through the code and have an understanding of what needs to be fixed.

**Comment by shirou** [comment]
Thank you for reporting and sorry for late response.
I fixed it at 627d2a9. Could you check it out?

**Comment by tianlin** [comment]
thx, it's fixed

**Comment by shirou** [comment]
Thank you!
