### ISSUE TITLE
Plan to v2 and introduce Breaking Change 

### ISSUE THREAD

**Issue by shirou** [shirou/gopsutil#174]
After replacing lsof (#164) , I have a plan to use semantic versioning and use gopkg.in. Current will be tagged the `v1` at that time, and start  `v2` branch.

I will appreciate if you write some comments about this idea.
### list of (possible) breaking changes
- [x] change JSON key from snake_case to camlCase.
- <del>[ ] change types from int32/64 and so on, to just int and uint. </del>
- golint acceptable
  - [x] net.NetConnections -> net.Connections, disk.DiskPartitions -> disk.Partitions and so on
- [x] process.State() returns 'R' not 'running' in Linux (see #173)

... (add whenever we found something)
### When v2 is introduced?

Target is end of March, 2016. But it may postponed.

**Comment by shirou** [comment]
I have started migration to v2 on `v2` branch.

**Comment by shirou** [comment]
`change types from int32/64 to int` is deleted. I tried but I think it forces too many changes.

**Comment by shirou** [comment]
I decided to not use `gopkg.in`. When I use `github.com/shirou` in source code, using `gopkg.in` becomes trouble due to the internal package. Change to recommend vendoring.

**Comment by miniwark** [comment]
Hi !
* What about a `Godeps` file too ? This is used by [gpm](https://github.com/pote/gpm) and may be useful as this library is a bit "low level" and therefore may be used by system monitoring tools (who generally need API stability and dependencies version management)
* *change types from int32/64 to int is deleted* This would have been a good change... It would have been more easy to manage strings conversion for display by simply using always using strconv.Itoa() instead of strconv.FormatInt(i, 10) or strconv.FormatInt(int64(i), 10).

**Comment by shirou** [comment]
Thank you for this comments.

> `Godeps` or something

gopsutil itself depends only a few packages, for the Windows environment. I believe applications may use a vendoring, not library. And also, I always thinking about API stability. So if API is changed, I will introduce new major version like the v2.  (BTW, `Godeps` is introduced by [godep](https://github.com/tools/godep), I think)

> change types from int32/64 to int is deleted This would have been a good change...

Yah, I was very worried about this. But when I tried, I had to change so many codes, so I gave up. sigh.

**Comment by miniwark** [comment]
> so I gave up. sigh.
Don't give up! Code re-factoring is always a painful, but you will feel happy when done!

**Comment by codeskyblue** [comment]
So, when modify cpu.TimeStat type from float64 to uint64. Because float64 always loss precision

**Comment by Lomanic** [comment]
We are on v2 for a while now.
