### ISSUE TITLE
De-hardcode /etc in the similar way to /proc and /sys

### ISSUE THREAD

**Issue by zstyblik** [shirou/gopsutil#175]
Hello,

please, would it be possible to de-hardcode path to `/etc` in the similar way as to `/proc` and `/sys`, resp. through ENV similar to `HOST_PROC` and `HOST_SYS`?
Because you can mount `/etc` into Docker as well and (probably) get some LSB information. Currently, this isn't possible, although I haven't tried to mount Host's `/etc` over `/etc` in Docker. Still, the former would be cleaner way to do it.

Thank you.

**Comment by shirou** [comment]
@zstyblik I add `HOST_ETC` at fa3e1cc. Could you check it out? Thanks!

**Comment by zstyblik** [comment]
@shirou it seems to be working. Thanks!
