### ISSUE TITLE
cpu_linux.go return an empty value for VendorID

### ISSUE THREAD

**Issue by miniwark** [shirou/gopsutil#180]
My kernel version : 4.2.0
Distribution : Ubuntu 15.10

In *cpu_linux.go* c.VendorID is checked by looking at "vendorId" key in /proc/cpuinfo.
This may be a kernel version dependent key but on my system the key is "vendor_id".
Therefore, c.VendorID return an empty result in my case.

**Comment by shirou** [comment]
Thank you for the information. I have confirmed `vendor_id` on Ubuntu and fixed it at 5daf090513cd856198b04a3f65dd7539c7602112. Could you check it out?

**Comment by miniwark** [comment]
I confirm than it's working for me now.

Thanks!
