### ISSUE TITLE
Please document the 'all' argument of Partitions(all bool)

### ISSUE THREAD

**Issue by miniwark** [shirou/gopsutil#181]
Seem like this 'all' argument is for future usages (or psutils compatibility ?),
but what he is intended to check ?
Separate physical disks from system ones ? (like /proc, /sys etc...)

**Comment by shirou** [comment]
Thank you for reporting. I have forgotten about this feature.  I implemented at ca99d7dc3f8d9e794f89a0f398651896abf5fbde (currently, only linux). Could you check it is work same as psutil?

**Comment by miniwark** [comment]
Not sure if it's the same than *psutils*, but the 'false' arguments, listing only physicals disk, work for me now.

Thanks!

**Comment by shirou** [comment]
I am grad to hear that. Thank you for reporting!
