### ISSUE TITLE
cpu.Percent always return 0

### ISSUE THREAD

**Issue by evildecay** [shirou/gopsutil#182]
##### gopsuitl2.0
```
cpus, err := cpu.Percent(time.Duration(200) * time.Millisecond, true)
if err == nil {
	for i, c := range cpus {
		fmt.Printf("cpu%d : %f%%\n", i, c)
	}
}

// cpu0 : 0.000000%
// cpu1 : 0.000000%
// cpu2 : 0.000000%
// cpu3 : 0.000000%
```
why linux and windows always return 0.000000?

**Comment by evildecay** [comment]
because need root, closed!

**Comment by shirou** [comment]
On Linux, gopsutil read `/proc/stat` and mostly this file can be red from every users. So, I can not understand why root is required. Could you tell me a permission of `/proc/stat` ? 

Thanks!

**Comment by miniwark** [comment]
What about the results with ?
'''
cpus, err := cpu.Percent(time.Duration(200) * time.Millisecond, **false**)
'''

**Comment by evildecay** [comment]
@shirou I re-tested, not the root of the problem. The problem persists.
I write have a problem?

**Comment by evildecay** [comment]
@shirou  I set the time value is too small. not root problem.
```
changed
cpu.Percent(time.Duration(1) * time.Second, true)
```
I understand.
Thanks.

**Comment by shirou** [comment]
It's good to hear that. Reporting is always welcome.

**Comment by evildecay** [comment]
@miniwark total percent? You can test it.

**Comment by miniwark** [comment]
@evildecay 

Yes see here: https://github.com/miniwark/tyu/blob/master/cpu.go

The "problem", is than cpu.Percent() always return a slice, even if there is only one value. So to use the result you have tu use cpu.Percent()[0]. I may be mistaken, but this differ from the original psutils (because of Python duck-typing).
