### ISSUE TITLE
Document process Status() results

### ISSUE THREAD

**Issue by miniwark** [shirou/gopsutil#187]
Actually `Status()` give a status similar to `/proc/[pid]/stat` (one character from the string "RSDZTW") instead of strings similar to [psutil.STATUS_*](https://pythonhosted.org/psutil/#constants).

It's perfectly OK, but a bit of documentation on this point (and maybe also similar results) would be welcome (i was expecting a similar results than *psutils*, but of course you are not forced to be 100% similar).

**Comment by shirou** [comment]
Absolutely agree!

I have updated comments and [godoc.org ](https://godoc.org/github.com/shirou/gopsutil/process) is also updated. Thank you.
