### ISSUE TITLE
host_linux_arm64.go have variables redeclarations who brake the building of gopsutils

### ISSUE THREAD

**Issue by miniwark** [shirou/gopsutil#195]
See the fail build log from one of my projects using gopsutils: https://drone.io/github.com/miniwark/tyu/60

I do not understand why this is breaking now, this was working perfectly a few days ago maybe it's a drone.io problem only?

**Comment by shirou** [comment]
Sorry. It might be caused by #194. From your drone.io, your `linux/amd64` (not `arm64`) is failed? If so, our [CircleCI test](https://circleci.com/gh/shirou/gopsutil) was passed.

Or, do you use go 1.4.2? If you change to go 1.6.2, the problem still exists?

**Comment by miniwark** [comment]
drone.io default build architecture indeed use go 1.4.2 by & linux/amd64. I can build with no problems on my local machine with go 1.6 & linux/amd64. I will try to see if i can change the go version at drone.io. 

In any case, if not fixed, the minimal go version may be documented in the requirements docs.

**Comment by shirou** [comment]
You can change any version of golang to download tar.gz like [this](https://drone.io/github.com/shirou/gopsutil/admin). So, could you please update to 1.5 or 1.6? (And I found some tests failed on drone.io. Perhaps, drone.io environment problem)

> In any case, if not fixed, the minimal go version may be documented in the requirements docs.

Agreed. I will add minimal go version to README. And I don't want to support 1.4.

Thank you for your report!

**Comment by miniwark** [comment]
Thanks for the build setup link, it will be a great help!
