### ISSUE TITLE
Current Network utlizaiton

### ISSUE THREAD

**Issue by washraf** [shirou/gopsutil#198]
As far as I understood the type `IOCountersStat` contains information since the system start in terms of sent and received bytes and packets.
I want to get some sort of network usage in a time frame just like i can do with CPU Percent function.

**Comment by shirou** [comment]
You can invoke `IOCountersStat()` twice with your desired time frame like this.

```
	var current uint64
	c := time.Tick(1 * time.Second)
	for now := range c {
		s, _ := net.IOCounters(false)
		new := s[0].BytesSent
		fmt.Println(now, new-current)
		current = new
	}
```

**Comment by washraf** [comment]
Thanks it helped very much ... And I think this will work too for disk usage !!

**Comment by washraf** [comment]
@shirou  
How to get the size of a directory
I am using :
```
stat,err:= disk.Usage("/home/walid/xyz")
fmt.Println(stat.Total)
```
It prints the total of the disk.
I just need a specific folder

**Comment by washraf** [comment]
I have implemented this. sorry for disturbance :+1: 
```
func DirSize(path string) (int64, error) {
    cmd:=exec.Command("du","-sh")
    cmd.Dir = path
    res,err:=cmd.CombinedOutput()
    if (err!=nil){
        return 0,err
    }
    sarr:=strings.Split(string(res),"M")
    return strconv.ParseInt(sarr[0],10,64)
}
```

**Comment by shirou** [comment]
`disk.Usage()` retunes Disk usage, not directory. If you want to know usage of specific directory, you need scan that directory hierarchy by using `du` as you wrote or use `filepath.Walk()`.
