### ISSUE TITLE
cpu percent(0, true) fails to return expected results

### ISSUE THREAD

**Issue by vrecan** [shirou/gopsutil#202]
the output is always either this:
```
[]float64) (len=16 cap=16) {
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0
}
```
or this
```
[]float64) (len=16 cap=16) {
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 100,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0,
 (float64) 0
}
```

previously if I would make multiple calls it would give me the percentage used between the two calls. Now it seems like it's giving me whatever it see's right when I call it.

What I am after here is a simple call I can make multiple times and each time it gives me the difference between the two calls.

**Comment by vrecan** [comment]
looks like this pr: https://github.com/shirou/gopsutil/commit/2434a327b939deb4d98f22d3931c92410c0a1fec

is what broke it, the variables used for last / previous stats should be stored in a struct associated to the instance to not cause a data race

**Comment by vrecan** [comment]
to fix this correctly we really need to have a struct for this data for the cpu stats... would you be against me making the changes to add a struct that has the last *& lastpercpu stats and then changed the function to be required to be called on that struct?

I am fine making the change but I don't want to do it and then not get it accepted

**Comment by shirou** [comment]
`Percent(0, true)` means no delay between two call. so the result is always 100 or 0. Please specify more longer duration such as 200msec.

or if you want to calculate and store last stats by your own, you can use `Times`.

**Comment by vrecan** [comment]
I don't want that behavior because that makes the call a blocking call. Previously it wasn't.

**Comment by KenjiTakahashi** [comment]
+1 on this. I've originally made it this way exactly to allow non-blocking call without forcing users to do bookkeeping on their side (sorry for not handling the race, though). Generally, the helper is there to help people :-). This is the way it's done in `psutil` as well.

Thanks @vrecan for investigating this, now I know why my [osop](https://github.com/distatus/osop) instances suddenly started displaying 0 CPU usage all the time.

**Comment by shirou** [comment]
I forgot about original `psutil` behavior. I read psutil code and @vrecan and @KenjiTakahashi are correct.

I want to change back to check `interval == 0` and use `lastCPUTimes` defined in the `cpu.go`. But from #131, I think it needs some mutex lock to avoid race condition.

However, I have no time to implement for a few weeks. I appreciate if @vrecan make a PR. 

Thank you!

**Comment by vrecan** [comment]
@shirou  I plan on coding something up tomorrow. I will put up a pr. Would you be ok if you had to instance a CPU object instead? Then you wouldn't need to wrap it with a mutex. I can do it either way.

**Comment by shirou** [comment]
Thanks! But, could you write a PR without API modification?

**Comment by vrecan** [comment]
I put up a pr, I did not make any changes to the API. Let me know if it's acceptable.
