### ISSUE TITLE
host.BootTime()  host.Uptime() bug

### ISSUE THREAD

**Issue by lixiangzhong** [shirou/gopsutil#206]
on **windows**:host.BootTime()  return System has been running time
but 
on **linux**:host.Uptime() return System has been running time

so this is bug??

My English is very poor

**Comment by shirou** [comment]
You mean 
- Windows: `host.BootTime()` returns a system started time
- Linux: `host.BootTime()` returns something other.
?

If so, it may be a bug. I will try to investigate next week.

**Comment by lixiangzhong** [comment]
That's what I mean.
thank you for your reply!

**Comment by shirou** [comment]
- Windows
  - Uptime: Unix time(sec) of Boot time.
  - Boottime: Time since booted.

- Linux:
  - Uptime: Time seince booted.
  - Boottime: Unix time of Boot time(sec)

So, on 53406b283244bfe6ebf41a1c4b38b4fac57e6201, Windows `Uptime` and `Boottime` have been swapped. 

Thank you for reporting!

**Comment by shirou** [comment]
I believe this issue is solved. Feel free to reopen if something wrong. Thank you.
