### ISSUE TITLE
[host] alpine linux not detected properly

### ISSUE THREAD

**Issue by client9** [shirou/gopsutil#208]
Hello!

Alpine Linux http://alpinelinux.org is the popular with many embedded systems developers and with the docker community.  It's becoming the default OS with docker, I believe, as well.

On a alpine linux host,

```
     serveros := fmt.Sprintf("%s/%s/%s/%s",
                hostinfo.OS, // linux, windows, freebsd
                hostinfo.Platform,
                hostinfo.PlatformFamily,
                hostinfo.PlatformVersion,
        )
       log.Printf("SERVEROS: %s", serveros)

```

returns

```
SERVEROS: linux///
```

should return

`linux/alpine/alpine/VERSION`  where `_VERSION_` is the contents of  `/etc/alpine-release`

```
# cat /etc/alpine-release 
3.3.3
```

Looks easy enough to do a PR for this.

**Comment by shirou** [comment]
Indeed. alpine is brand new distribution. I add it at c0d118580967206d87b2d3e0adf9d36b08c6de38, could you check it works?

**Comment by client9** [comment]
Wow!  This is one less thing I have to do today.  Thank you.

Confirmed it works.

```
	sniff_test.go:40: Platform = linux/alpine/alpine/3.3.3
	sniff_test.go:41: Virtualization = docker
```

correct!
