### ISSUE TITLE
%2Fbin%2Fps-x-opid_fail is an invalid filename

### ISSUE THREAD

**Issue by aramadia** [shirou/gopsutil#210]
The file gopsutil/process/expected/darwin/%2Fbin%2Fps-ax-opid_fail doesn't play nicely in some systems (the % symbol is the main culprit).  Is there a way to use more conventional filename characters?

**Comment by shirou** [comment]
Thanks. I also think this format is not so good and plan to change. But could you tell me what system does not work? Windows?

**Comment by shirou** [comment]
Sorry to very very late response. #332 fixes. Thank you for your patience.

**Comment by urosgruber** [comment]
Hm, not sure if this is the same issue but from 2.17.03 this fails on FreeBSD with the error
Unable to access file `/ports/sysutils/gopsutil/work/stage/usr/local/share/go/src/github.com/shirou/gopsutil/process/expected/darwin/%2Fbin%2Fps-ax-opid_fail`
