### ISSUE TITLE
Support for i386?

### ISSUE THREAD

**Issue by kevinpostal** [shirou/gopsutil#211]
Any plans to support i386 as well as 64 bit?

**Comment by shirou** [comment]
What kind of OS do you want to support? FreeBSD and Linux are supported (yes, it may have a bug). But darwin and Windows are not supported, because I don't have i386 OSes and could not run on VM.

**Comment by shirou** [comment]
Thanks for the @sean- , #308 is merged. Perhaps it helps you.

I close this issue. If you have a problem, feel free to re-open or open new issue. Thank you.
