### ISSUE TITLE
Improve documentation for disk.GetDiskSerialNumber()

### ISSUE THREAD

**Issue by zstyblik** [shirou/gopsutil#212]
Hello,

please, improve documentation for disk.GetDiskSerialNumber(), resp. documentation should state that `name` means block device, eg. `/dev/sda`.
If pointed in the right direction, I can do a PR :)

Thanks.

**Comment by shirou** [comment]
Thanks! [godoc](https://godoc.org/github.com/shirou/gopsutil/disk#GetDiskSerialNumber) comes from [disk/disk_linux.go](https://github.com/shirou/gopsutil/blob/master/disk/disk_linux.go#L339). If you write some documents, I am very appreciate.
