### ISSUE TITLE
InfoStat.PlatformFamily and InfoStat.VirtualizationSystem empty at CoreOS

### ISSUE THREAD

**Issue by zstyblik** [shirou/gopsutil#214]
Hello,

for reason unknown to me, it seems that InfoStat.PlatformFamily and InfoStat.VirtualizationSystem are empty at CoreOS v1010.3.0 with Linux kernel v4.5.0. gopsutil v2.0.0.
If I have time, I'll try to dig into code and see where these two attributes come from and what could be the reason for them being empty.

Thanks.

**Comment by zstyblik** [comment]
`InfoStat.VirtualizationSystem` is empty, because neither of modules(kvm, xen, vbox) are loaded. This probably isn't bug per se, thinking about in reasonable way :)

I'm not sure about `InfoStat.PlatformFamily` yet. `/etc/os-release` and `/etc/lsb-release` do exist, although they're symbolic links. Also, given the following code:

```
	} else if lsb.ID != "" {
		platform = strings.ToLower(lsb.ID)
		version = lsb.Release
	}
```

I would expect to get back something. I will try to investigate a bit further.

**Comment by shirou** [comment]
I added coreos on dd9b50926cadc8ce84e8436d628018c7978b076c about `Info()` and `Virtualization()`. I don't know returning "rkt" for virtualization system is true, but I can change other like `coreos`.

**Comment by zstyblik** [comment]
@shirou, I don't know either about rkt. But I did research on CoreOS and family and to have "coreos" family seems to be correct. It doesn't have any ties to other families. :)

I think this issue can be closed as fixed now.

Thanks.

**Comment by shirou** [comment]
Thanks. If coreos people want to change something, I will fix it.
