### ISSUE TITLE
Missing license for "internal/common/binary.go"

### ISSUE THREAD

**Issue by onlyjob** [shirou/gopsutil#221]
[internal/common/binary.go](../blob/master/internal/common/binary.go#L3-L5) refers to missing license.

**Comment by shirou** [comment]
Thanks. It is a copy from [go/encoding/binary.go](https://github.com/golang/go/blob/master/src/encoding/binary/binary.go). so I don't want to change this part.

**Comment by onlyjob** [comment]
You just need to commit corresponding LICENSE file to comply.

**Comment by shirou** [comment]
I added golang licence to LICENSE file at 2728d81cdef579d6ed88d2fd5c71e85aa83eaba8.

**Comment by onlyjob** [comment]
Excellent, thank you very much. :)
