### ISSUE TITLE
process.PidExists(0) return False on Linux

### ISSUE THREAD

**Issue by Gnouc** [shirou/gopsutil#223]
With current version of `gopsutil`:

```
$ cat test.go
cat test.go 
package main

import (
    "fmt"

    "github.com/shirou/gopsutil/process"
)

func main() {
    fmt.Println(process.PidExists(0))
}
$ go run test.go
false <nil>
```

On any POSIX system, PID 0 means all process and that check should return True. At least with FreeBSD 9.3, `process.PidExists(0)` will report `true`.

python `psutil` also has the same [issue](https://github.com/giampaolo/psutil/issues/844).

I have made a [quick fix](https://github.com/Gnouc/gopsutil/commit/0c5c7ec45623efc659a854744070acbc2f7349c6) for this issue, though I'm not sure it will work on Windows.

**Comment by Lomanic** [comment]
I agree with @giampaolo's point of view in giampaolo/psutil#844, `process.PidExists(X)` should return true only if a given process with a pid X exists. That's not the case for 0 according to procfs.

**Comment by giampaolo** [comment]
To further elaborate on the decision I took in psutil, regardless on whether the platforms has PID 0 or not, `ppid()` can still return 0. On Linux:
```python
>>> psutil.Process(1).ppid()
0
```
...so basically this means that kernel uses `0` as a value to express "there's no parent pid". In Python terms (not sure about Go language), one may argue to return `None / NULL` instead, but I consider this a case where practicality should beat purity.
