### ISSUE TITLE
Definition of "IOTime"

### ISSUE THREAD

**Issue by grindthemall** [shirou/gopsutil#229]
In the disk module what exactly does "IOTime" indicate?  

Is this a total amount of time spent in disk IO (i.e. read time + write time)?

**Comment by shirou** [comment]
on Linux, that value comes from `/proc/diskstats` and iotime is `time spent doing I/Os`.  see [here](https://www.kernel.org/doc/Documentation/iostats.txt) . It includes read and write, I think.

(IOTime is not implemented on other platform)

**Comment by phemmer** [comment]
> (IOTime is not implemented on other platform)

I've opened #232 which adds the metric for FreeBSD.

**Comment by shirou** [comment]
Since #232 is merged, I close this issue. Thank you for your contribution!
