### ISSUE TITLE
Some support for nacl

### ISSUE THREAD

**Issue by razvanm** [shirou/gopsutil#234]
I have some code that depends on _gopsutil_ that is used for both for real OSs like `linux` and `darwin` but also for `nacl` (as a Chroma app/extension). The code doesn't take any decisions on the values it reads so reporting some dummy values is perfectly fine. The pull request #233 is doing that for the code I am dealing now. Is there anything else that should be included?

**Comment by lfittl** [comment]
@razvanm I've actually run into this same problem with Solaris - I don't need the gopsutil support there (at least for now), but the fact that there is no build tags for it make it cumbersome to build my project.

Adding dummy files for that specific architecture would be one approach (like you've done in #233, I've done so here for Solaris: https://github.com/lfittl/gopsutil/commit/362880bb685ac54ed21206922efd4732a143defd)

But how about a different idea: We introduce a `_fallback.go` file for each data source (e.g. `cpu_fallback.go`), that has a build tag of `// +build !windows !freebsd !linux !darwin` and returns the NotImplemented errors.

The Go documentation also seems to hint at this being the suggested approach ("Such a file is usually paired with another file implementing the default functionality for other systems, which in this case would carry the constraint" on https://golang.org/pkg/go/build/).

This way we only take the hit once, and this issue should be solved for all future architectures as well. If someone does end up adding e.g. NaCL support they just add `!nacl` to the `_fallback.go` file.

@shirou Thoughts on this approach? (happy to make a PR)

**Comment by shirou** [comment]
Thank you for the suggestion. I feel introduce `_fallback.go` is a very good idea at start point and incremental development. (Perhaps, gopsutil will support [Fuchsia](https://github.com/fuchsia-mirror) in the future :laughing: )

@lfittl if @razvanm agree, could you make a initial PR?

**Comment by razvanm** [comment]
The `_fallback.go` sounds a great idea. :-)

**Comment by lfittl** [comment]
@shirou @razvanm Excellent!

I think I should be able to get a PR going for that today or tomorrow.

**Comment by lfittl** [comment]
@razvanm @shirou With a bit of a delay, I pushed up a PR now at https://github.com/shirou/gopsutil/pull/247

@razvanm I couldn't get cross-compilation to nacl working on my OSX machine - could you give the PR a test and verify that this works for you as intended?

**Comment by shirou** [comment]
@razvanm Could you test #247 on your nacl environment? Thank you.

**Comment by razvanm** [comment]
I'll try it today and report back. Sorry for the slowness.

**Comment by razvanm** [comment]
I confirm that #247 works fine for my nacl environment. Thanks for fix! :-)

**Comment by shirou** [comment]
Thanks, @lfittl and @razvanm! I merged #247 then close this issue automatically. If you want to discuss more, please re-open or open new issue.
