### ISSUE TITLE
IO counters for bytes read and write all zero

### ISSUE THREAD

**Issue by ncabatoff** [shirou/gopsutil#235]
At least on my Ubuntu 14.04 system, proc(5) specifies that /proc/[pid]/io contains these fields:

              rchar: characters read
              wchar: characters written
              syscr: read syscalls
              syscw: write syscalls
              read_bytes: bytes read
              write_bytes: bytes written
              cancelled_write_bytes:

However Process.fillFromIO() looks for the fields syscr, syscw, readBytes, and writeBytes.  Googling suggests that this is a simple error/typo and not something they changed in some version of the kernel.

**Comment by shirou** [comment]
Thank you for your contrition! Your great PR #236 fixes it. So I close this issue.
