### ISSUE TITLE
disk_linux.go's func of 'Usage' cause NaN value

### ISSUE THREAD

**Issue by brucelin-cn** [shirou/gopsutil#244]
func Uage(path string)(*UsageStat, error){

...
ret.InodesUsed = (ret.InodesTotal - ret.InodesFree)
ret.InodesUsedPercent = (float64(ret.InodesUsed) / float64(ret.InodesTotal)) * 100
...
}
/*
when I use UsageStat to json.MarshalIndent(), it return errors say about  "NaN".
I think reason is the "ret.InodesUsed == 0" and compute '(float64(ret.InodesUsed) / float64(ret.InodesTotal)) '
*/

**Comment by shirou** [comment]
Thanks. I fix the code at  08a6ab66b0a8779b25f1b9a7427d790752225b48 . if could not get inode correctly, leave empty and can Marshal().

**Comment by shirou** [comment]
I will close this issue. If there are any problem, feel free to re-open or create new issue. Thank you for your contribution.
