### ISSUE TITLE
[FEATURE] Handling CPU frequency scaling

### ISSUE THREAD

**Issue by dvusboy** [shirou/gopsutil#249]
With modern CPUs that support variable clock speed for the purpose of power efficiency, it would be nice for `cpu.InfoStat` to return minimum, maximum and current frequencies if they are available. AFAIK, these are available on Linux as well as Darwin.

On Linux, these are available under `sysfs` at `/sys/devices/system/cpu/cpuX/cpufreq/cpuinfo_{min,max,cur}_freq`. On Darwin, besides the `hw.cpufrequency` key already in use, we also have `hw.cpufrequency_{min,max}`. As for FreeBSD, the picture seems to be more complicated and I don't have the resource to investigate.

Specifically, the importance of having access to the maximum CPU frequency is made apparent in resource management frameworks. For example, in this [Nomad issue](https://github.com/hashicorp/nomad/issues/1392), because the reported MHz in `cpu.InfoStat` is the value from `/proc/cpuinfo`, it is actually the current CPU frequency, typically when the machine is idle. It means Nomad CPU fingerprinting will not reflect the true CPU resource available, because the idle frequency is often substantially lower than the one at full blast.

**Comment by shirou** [comment]
hmm,  I understand.

So, how about to add `MaxFreq` and `MinFreq` to `cpu.InfoStat` ? `MaxFreq` and current `MHz` become a same value but it does not break compatibility. And we can  remove for future release.

**Comment by dvusboy** [comment]
I actually think the values returned by `sysctl` on Darwin isn't reflecting the actual `SpeedStep` values on an Intel processor. It's just reporting the nominal clock frequency across all 3 values. That said, having `MaxFreq` would be helpful to schedulers like Nomad. In the case where it isn't reported, maybe we can use the same value as `cpu.MHz`. In the case of `MinFreq`, I'm less certain of its usefulness other than for the sake of completeness. I can take a stab at creating a PR for this feature, but I don't really have resource to test it across the platforms you're supporting right now.

Now, I'm not sure I understand what you mean by "remove for future release". `cpu.MHz` will keep its current meaning, on Linux hosts, of reporting the value of `cpuinfo_cur_freq/1000`.

**Comment by dvusboy** [comment]
@dadgar @shirou: As I worked on the PR, I notice `cpu_windows.go` actually has `cpu.Mhz` means `Win32_Processor.MaxClockSpeed`.

So, instead of introducing `MinFreq` and `MaxFreq`, I can adjust the Linux version to also have the same meaning. That is, we standardize on `Mhz` to mean maximum frequency/clock speed of the CPU. I'm not sure how this would affect Nomad's run-time statistics.

This also has a nice side-effect of making `cpu.Mhz` CPU-architecture independent on Linux, as the current implementation of reading from `cpuinfo_max_freq` stems from a different `/proc/cpuinfo` format on ARM (#88).

What do you think, Shirou?

**Comment by shirou** [comment]
From my understanding, there are two problems.
(forget about my *"remove for future release"* word. I was misunderstanding)

1. current `Mhz` is not enough because modern CPU have Min/Current/Max freq.
2. current `Mhz` shows different meaning among platforms.

So, your latest suggestion is,

a. `Mhz` shows the CPUs Max freq in all of platform and CPU architecture.

If my understanding is correct, I agree. If you make a PR, very appreciate and I can check all supported platform.

And As you said, it affects Nomad but I don't know Nomad's code...

**Comment by dvusboy** [comment]
In that case, I'll start with a PR to standardize the meaning to `Mhz` to refer to the maximum clock speed the CPU supports, if that metric is available. As for having the different kind of frequency/clock speed, I can supply a subsequent PR.
