### ISSUE TITLE
Question: network bandwidth utlilization?

### ISSUE THREAD

**Issue by geekdave** [shirou/gopsutil#252]
Sorry if this is a n00b question, but can I use the network features described in the readme to monitor upload/download bandwidth utilization in bits/bytes-per-second?  Thanks!

**Comment by shirou** [comment]
I think bandwidth, that means how many bytes can transfer to a target, can not be measured only one host. You need correspondent node. How about to use [iperf](https://iperf.fr/) or there are many detecting bandwidth services.

**Comment by geekdave** [comment]
Oh I guess I didn't mean bandwidth capacity. But rather how many bytes are
currently being uploaded and downloaded. Basically how much is being
utilized on the machine. Is that possible? We are trying to understand when
a machine is using lots of network vs when it's not using much.

**Comment by shirou** [comment]
You can use `PacketsSent` and `PacketsRecv`.

1. get `PacketsSent` and/or `PacketsRecv`
2. sleep significant time, such as 1 sec or 1 day
3. get the values again
4. calculate difference between 1. and 3.

**Comment by shirou** [comment]
I close this issue. If you have any other question, please re-open or open new issue. Thank you.
