### ISSUE TITLE
CPU Percentage in Windows is correct ? 

### ISSUE THREAD

**Issue by frostarun** [shirou/gopsutil#257]
Its based on WMIC and it should be right .. Please put a mark in your table that CPU percentage for windows is fine .. Also you can add same type of feature to find OS - architecture for windows using WMIC , It could be usefull.

**Comment by shirou** [comment]
Sorry, I found `Current Status` table is broken and not rendered. I fixed it. Thank you very match.
And I think a mark is already put CPU percentage for Windows. 

> architecture for windows using WMIC , It could be usefull.

We already use [Win32_OperatingSystem](https://msdn.microsoft.com/en-us/library/aa394239(v=vs.85).aspx) to get OS related information for windows. I am not familiar with Windows, but is there any other information to complement current `host.InfoStat` ?

**Comment by frostarun** [comment]
And Thanks for the reply.
