### ISSUE TITLE
process: determine page sizes via function

### ISSUE THREAD

**Issue by monstermunchkin** [shirou/gopsutil#258]
The current implementation for linux uses constants for the page sizes which is not ideal, as some architectures support different sizes.
A better solution would be to use Go's [`Getpagesize`](https://golang.org/pkg/os/#Getpagesize) function to determine the used page size. This is already being used in `mem_darwin_*.go`.

If there are no objections, I'll gladly write a patch for this.

**Comment by shirou** [comment]
Thank you ! [mem/darwin](https://github.com/shirou/gopsutil/blob/master/mem/mem_darwin_nocgo.go#L30) use `syscall.Getpagesize`, [FreeBSD get pagesize](https://github.com/shirou/gopsutil/blob/master/mem/mem_freebsd.go#L15) via syscall, and processes are statically defined.  These are inconsistent and I agree to use `Getpagesize`. 

However, currently I have a few time to develop, so I will really appreciate if you make a PR.
