### ISSUE TITLE
process: move `ClockTicks` to `process_linux.go`

### ISSUE THREAD

**Issue by monstermunchkin** [shirou/gopsutil#260]
From what I can see, the Linux kernel uses a fixed value (100) for the clock ticks on all architectures currently supported by Go, and so do all the `process_linux_*.go` files here.

Therefore, I propose we move the constant `ClockTicks` to `process_linux.go`. This should then also fix the remaining compile errors on ppc64le (#230 and #225).

I'll gladly write a patch for this, provided there are no objections.

**Comment by shirou** [comment]
Sorry for late response.

>  the Linux kernel uses a fixed value (100) for the clock ticks on all architectures currently supported by Go,  

Good news! Could you show me the source code or something about all architectures have fixed value? I can not confirm ppc64le has same value.

**Comment by monstermunchkin** [comment]
The Linux kernel defines `CLOCKS_PER_SEC` [here](http://lxr.free-electrons.com/ident?i=CLOCKS_PER_SEC) (`CLK_TCK` has the same value but is considered obsolete). As you can see, all architectures, besides `xtensa`, `alpha`, and `ia64`, share the same [value](http://lxr.free-electrons.com/source/include/asm-generic/param.h#L9).

**Comment by shirou** [comment]
Thanks a lot ! As you say, all architecutre [only alpha has different](http://lxr.free-electrons.com/source/arch/alpha/include/asm/param.h#L9`) has same value. 

Would you mind making a PR to eliminate arch-dependent files? If so, I will accept quickly!
