### ISSUE TITLE
Disk average queue lenght

### ISSUE THREAD

**Issue by DigitalMarc** [shirou/gopsutil#262]
Hi Shirou,

Thanks a lot for you awesome library.
I was wondering if you plan to implement avgqu-sz provided by iostat?

# sudo iostat -x

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
                   5,48    0,14    4,16    0,20    0,00   90,01

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0,03     0,85    1,77    0,68    36,89    34,70    58,50     0,02    8,89    6,88   14,10   1,91   0,47

Regards,
Marc

**Comment by shirou** [comment]
I have not well reserached yet, but I think `avgqu-sz`, average queue length can be calculated from `IOCountersStat.IopsInProgress`. 

http://www.xaprb.com/blog/2010/01/09/how-linux-iostat-computes-its-results/

**Comment by DigitalMarc** [comment]
Thanks a lot for your quick reply, I'll take a look.

**Comment by DigitalMarc** [comment]
From what I've read from iostat source, it uses the last field in mtab (weighted time spent doing I/Os (ms))
I've added that on your sources. I'm nearly done reproducing the same value as iostat but something is weird in the math.
