### ISSUE TITLE
CPUTimes per cpu on windows

### ISSUE THREAD

**Issue by DavidGamba** [shirou/gopsutil#266]
I know that CPUTimes per cpu is marked as a [TODO](https://github.com/shirou/gopsutil/blob/14eb7acb2355d760c7cc114df03042b3cb630d67/cpu/cpu_windows.go#L26) for windows.
How can I add this functionality? Can you give me a pointer of where to start searching so I can try and submit a PR.

Thanks!

**Comment by shirou** [comment]
Sorry, since I am not familiar with Windows, I can not show a pointer.

**Comment by Lomanic** [comment]
This has been fixed for a while.
