### ISSUE TITLE
how to get used and total storage for each partition in linux 

### ISSUE THREAD

**Issue by shageeth** [shirou/gopsutil#272]
I was trying to get file system information using the following code but it didn't work for linux , can anyone help me for this ?   @shirou 
p, _ := disk.Partitions(true)
for i := 0; i < len(p); i++ {
        d, _ := disk.Usage(p[i].Device)
        var total1 string = strconv.FormatUint(d.Total, 10)
        var used1 string = strconv.FormatUint(d.Used, 10)
        a.Drive[i] = strings.Replace(d.Path, ":", "", -1)  //a => constructor reference
        a.TotalStorage[i] = total1
        a.Usedstorage[i] = used1
    }

**Comment by shirou** [comment]
something like this?

```
package main

import (
	"fmt"
	"log"
	"strconv"
	"strings"

	"github.com/shirou/gopsutil/disk"
)

func main() {
	partitions, err := disk.Partitions(true)
	if err != nil {
		log.Fatal(err)
	}

	for _, p := range partitions {
		d, err := disk.Usage(p.Device)
		if err != nil {
			if err.Error() == "no such file or directory" {
				continue
			}
			log.Fatal(err)
		}

		total1 := strconv.FormatUint(d.Total, 10)
		used1 := strconv.FormatUint(d.Used, 10)
		fmt.Printf("path: %s\n", strings.Replace(d.Path, ":", "", -1))
		fmt.Printf("  Total: %v\n", total1)
		fmt.Printf("  Used: %v\n", used1)
	}
}
```

```
path: /dev/vda1
  Total: 377835520
  Used: 12288
```

**Comment by shirou** [comment]
I think you could get desired information by that code. I close this issue. If you have other issue, please re-open or create other issue. Thank you.
