### ISSUE TITLE
 mips compile

### ISSUE THREAD

**Issue by dnascimento** [shirou/gopsutil#273]
When compling with MIPS, we get the following error:

```
gopsutil/host/host_linux.go:116: undefined: sizeOfUtmp
gopsutil/host/host_linux.go:121: undefined: sizeOfUtmp
gopsutil/host/host_linux.go:123: undefined: utmp
```

**Comment by umataro** [comment]
+1

**Comment by maddie** [comment]
Any news on this issue?

**Comment by shirou** [comment]
I'm sorry, but I don't have a MIPS machine, so I can not work on it. Contribution is always welcome!

**Comment by shirou** [comment]
finally I can understand why this failed, it is mips64. I could confirm
```
GOOS=linux GOARCH=mip64 go test .
```
failed. So, I copied `host_linux_mips.go` to `host_linux_mips64.go` on fc04d2dd9a512906a2604242b35275179e250eda. it is just a copy so perhaps it has a problem. If you met problem, please open an issue. Thank you.
