### ISSUE TITLE
Stop exporting methods that aren't implemented yet.

### ISSUE THREAD

**Issue by natdm** [shirou/gopsutil#276]
See title.

**Comment by shirou** [comment]
gopsutil supports various kind of platforms. So, if one of platform is not implemented yet, other platform is implemented.

**Comment by sparrc** [comment]
I completely disagree @natdm, not exporting different methods on different platforms would be a terrible idea and make it impossible to develop cross-platform applications

**Comment by shirou** [comment]
I close this issue. If you have enough reason to remove "not implemented method", please re-open. Thanks.
