### ISSUE TITLE
Darwin CPU info: C.GoBytes: cgo argument has Go pointer to Go pointer

### ISSUE THREAD

**Issue by lowjoel** [shirou/gopsutil#279]
For macOS, the CPU times are read via a cgo call to host_processor_info. The result of the operation is a chunk of memory allocated by the kernel, which the Go code needs to copy to its own GC-ed memory for access.

Sometimes, the memory that is allocated by the system falls in a range which will cause a panic. C.GoBytes is itself a cgo call, which means that its arguments are validated by the Go runtime. If the memory that the kernel allocates is within a region which the Go runtime believes that it may be used by the GC, the call to C.GoBytes will panic with "cgo argument has Go pointer to Go pointer". This happens fairly regularly for me when running a binary with gopsutil linked in under the Delve debugger.

One workaround (works for me, but untested in production; macOS only for development) is to create a slice which is directly backed by the system memory (which is freed by C code), as described in https://github.com/golang/go/wiki/cgo#turning-c-arrays-into-go-slices

So https://github.com/shirou/gopsutil/blob/74541ba4a5bcb36e393d549c11f32048c9e4934c/cpu/cpu_darwin_cgo.go#L60 will read:
```go
buf := (*[1 << 30]byte)(unsafe.Pointer(cpuload))[:size:size]
```

**Comment by shirou** [comment]
Thanks! I have created #280. On my Mac environment, this works fine and seems no difference old implementation. Could you check it out?

**Comment by lowjoel** [comment]
Thanks! That seems to work for me; I didn't use that exact branch because of our vendoring policy, but I have changed the equivalent line in an earlier version and it seems to be working much better so far.

**Comment by shirou** [comment]
Thank you for your contribution!
