### ISSUE TITLE
Adding support for SunOS

### ISSUE THREAD

**Issue by hush-hush** [shirou/gopsutil#292]
Hello,

gopsutil does not support SunOS for now. This is something my company is going to need at some point. I'm ready to invest time to add it to the project, but I wanted to check how you felt about it before.

Is this something you would merge upstream if it was available. I would start with memory check and move forward to other check as we need them.

Thanks !

**Comment by shirou** [comment]
Actually, I had tried to implement on Solaris(illumos), but I don't have enough experimental, I gave up. If you send a PR, I would be greatly appreciated.

**Comment by hush-hush** [comment]
OK, great !
I'll see internally when we might have time to get on it.

Closing the issue.

**Comment by jen20** [comment]
:+1: Happy to help contribute and/or review this as necessary on Illumos.
