### ISSUE TITLE
RlimitStat struct implementation

### ISSUE THREAD

**Issue by smith3v** [shirou/gopsutil#295]
Hi,

I'm implementing func (p *Process) Rlimit() ([]RlimitStat, error) for Linux and stumbled upon the question.
The RlimitStat struct has the following definition:

```
type RlimitStat struct {
	Resource int32 `json:"resource"`
	Soft     int32 `json:"soft"`
	Hard     int32 `json:"hard"`
}
```

And here's a regular contain of the limits file:

```
$ cat /proc/9478/limits
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             31442                31442                processes 
Max open files            4096                 4096                 files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       31442                31442                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us        
```

Sorry, but I'm missing the idea how to encode limit name into Resource int32? I'm new to Go, let me know it it's a common practice.

Kind regrads,
Vyacheslav.

**Comment by smith3v** [comment]
Seems like I should use the codes from Glibc's sys/resource.h

http://man7.org/linux/man-pages/man2/setrlimit.2.html

I'm going to add them as constants to process_linux.go. Let me know if there's a better place.

**Comment by shirou** [comment]
Thank you for interested in rlimit. gopsutil is a port of the [python psutil](https://github.com/giampaolo/psutil), and psutil use [these](https://github.com/giampaolo/psutil/blob/3bf8bc8dcd3202594b9e03a6527bba270a631b76/psutil/_psutil_linux.c#L636). I think it is same as your suggested url, but you can check using psutil and type `print(psutil.RLIMIT_NOFILE)`

Since FreeBSD/Darwin have rlimit, could you defined these constants at `process.go`, not `process_linux.go` ?

**Comment by smith3v** [comment]
Thank you for the reply.
I'll add the constants to `process.go`.
