### ISSUE TITLE
s390x support

### ISSUE THREAD

**Issue by tychoish** [shirou/gopsutil#297]
gopsutil doesn't compile/support (in its current form) s390x systems (zLinux). I will look into this, but wanted to open this as a marker for others if someone runs into this or has the fix before I have time to get to this.

**Comment by shirou** [comment]
I don't have a zLinux and can not confirm it works, but if you contribute, I will merge it with thanks.

**Comment by tychoish** [comment]
Will do.

**Comment by shirou** [comment]
By #305, this issue is fixed I think. So I close it. Thank you.
