### ISSUE TITLE
open /proc/stat: errno 530

### ISSUE THREAD

**Issue by yjbdsky** [shirou/gopsutil#298]
os: Red Hat Enterprise Linux AS release 4:
err: index out of range 
at: cpu_linux.go  line 201

because: 
common.go:
func ReadLinesOffsetN 
f, err := os.Open(filename)
err: errno 530

**Comment by yjbdsky** [comment]
/proc/loadavg also errno 530

**Comment by shirou** [comment]
sorry, I don't have a `Red Hat Enterprise Linux AS release 4` system, but probably is it a RHEL4/5 bug?

See: 
- https://groups.google.com/forum/#!topic/golang-nuts/7riGUCIbbkA
- https://bugzilla.redhat.com/show_bug.cgi?id=426890
- https://github.com/golang/go/issues/2640
- https://github.com/golang/go/issues/146

**Comment by shirou** [comment]
Any updates? I close this issue. If you find something, feel free to re-open. Thank you
