### ISSUE TITLE
use golang.org/x/sys instead of syscall

### ISSUE THREAD

**Issue by shirou** [shirou/gopsutil#30]
From go 1.4, syscall is frozen and requested to use golang.org/x/sys
https://golang.org/doc/go1.4

Should move to sys package.

**Comment by stevenh** [comment]
Be careful about that as its not maintained very well, with lots of missing fixes as I found out today :(

**Comment by shirou** [comment]
Thank you for the information. syscall is just frozen, not deprecated. I will wait until it become more mature.

**Comment by kardianos** [comment]
@shirou syscall is still actively used today and will continue. /x/sys is just where any exposed new functionality will be added. /x/sys augments, but will never replace, syscall. I recommend closing this issue as invalid.

**Comment by shirou** [comment]
Thank you for the comment!
Hmm. yah, it seems `syscall` and `/x/sys` are both active as you said.

Currently, `/x/sys` new functionality is not required, so I close this issue temporally.
When `/x/sys` can replace syscall entirely or new function is required, I will reopen this issue.

**Comment by shirou** [comment]
refs #380.
