### ISSUE TITLE
Mhz copied to CPU on FreeBSD

### ISSUE THREAD

**Issue by urosgruber** [shirou/gopsutil#304]
I noticed CPU outputs value of MHz instead of number on CPUs. I thought CPU is used to output number of physical CPUs.

I think dmesg might help here to get the right number. Here are a few examples from our servers

- (2phys CPUs no HT) FreeBSD/SMP: 2 package(s) x 4 core(s)  `hw.ncpu=8`
- (1 phys CPUs) FreeBSD/SMP: 1 package(s) x 2 core(s) x 2 hardware threads  `hw.ncpu=4`
- (1 phys CPUs) FreeBSD/SMP: 1 package(s) x 4 core(s) x 2 SMT threads  `hw.ncpu=8`
- (1 phys CPUs) FreeBSD/SMP: 1 package(s) x 6 core(s) x 2 SMT threads  `hw.ncpu=12`

**Comment by shirou** [comment]
Thank you! You are right.
Currently, `CPU.Cores` is a value from the `hw.ncpu`, and `CPU.CPU` is same as MHz as you mentioned. 

In the linux, `CPU.CPU` is a number of CPUs and `CPU.Info()` returns multiple `InfoStats{}`. However, FreeBSD returns only one CPU, because it is hard to get information from `/var/run/dmesg.boot`.

At 7783018b9dc3110d3d667f9a1714b67e6a8e66fd, I change the CPU.CPU to number of CPU. But it is not complete to get multiple CPU information. (Because I do not have multiple CPU FreeBSD machine... I will try to use VirtualBox)

**Comment by urosgruber** [comment]
There is another way you can reliable get number of physical CPUs. `sysctl kern.sched.topology_spec`

It will return XML but I think it's easier to parse xml than plain text

1. 2 CPU (you can see two group tags on 2nd level)
```
<groups>
 <group level="1" cache-level="0">
  <cpu count="8" mask="0xff">0, 1, 2, 3, 4, 5, 6, 7</cpu>
  <children>
   <group level="2" cache-level="2">
   </group>
   <group level="2" cache-level="2">
   </group>
  </children>
 </group>
</groups>
```

2. 1 CPU have only one group on 2nd level
```
<groups>
 <group level="1" cache-level="0">
  <cpu count="4" mask="f,0,0,0">0, 1, 2, 3</cpu>
  <children>
   <group level="2" cache-level="3">
   </group>
  </children>
 </group>
</groups>
```

3. again 1 CPU
```
<groups>
 <group level="1" cache-level="0">
  <cpu count="8" mask="ff">0, 1, 2, 3, 4, 5, 6, 7</cpu>
  <children>
   <group level="2" cache-level="2">
   </group>
  </children>
 </group>
</groups>
```

Hope this helps a bit and thanks for all the effort. At least I can give you some help with testing.

**Comment by shirou** [comment]
Thanks. However, it seems `sysctl kern.sched.topology_spec` can not get `Origin` or `Features` in the `/var/run/dmesg.boot`.

**Comment by urosgruber** [comment]
You're right.  The only way for this is through dmesg file.

**Comment by shirou** [comment]
Could you give me some of (a part of ) your dmesges? (gist is best)
I will try to parse these and get individual CPUs.

**Comment by urosgruber** [comment]
Sure!

https://gist.github.com/urosgruber/58a592dc09e8eb76c70d5398f5a54cf5
https://gist.github.com/urosgruber/d89894d2b61fdda972256cdbf3806b01
https://gist.github.com/urosgruber/557432c70940d3ee9cfd239f73713631

Let me know if you need more. This is just top part of 3 different servers.

**Comment by shirou** [comment]
Thank you!

It seems a little bit different from I was thinking about. I was thinked `CPU: Intel(R) Core(TM) i3 CPU` line were multiple if multi-cpu, but just one line. I am looking for what is the best parse strategy. please wait.

**Comment by shirou** [comment]
reading [ruby ohai library](https://github.com/chef/ohai/blob/master/lib/ohai/plugins/freebsd/cpu.rb),  and found

- total: getting from `FreeBSD/SMP: Multiprocessor System Detected`
- real and cores: getting from `FreeBSD/SMP: 2 package(s) x 4 core(s) x 2 SMT threads`

And returns only one CPU information. Same as [facter](https://github.com/puppetlabs/facter/blob/master/lib/src/facts/freebsd/processor_resolver.cc#L27).

So, I am thinking about coping same CPU values until `hw.ncpu`. For example, if `hw.ncpu=4`, 

```
[
  {"cpu":0,"family":"0x6 ","cores":4,"modelName":"Intel(R) Core(TM)2 Duo CPU T7700 @ 2.40GHz","mhz":2133, (snip...)},
  {"cpu":1,"family":"0x6 ","cores":4,"modelName":"Intel(R) Core(TM)2 Duo CPU T7700 @ 2.40GHz","mhz":2133, (snip...)},
  {"cpu":2,"family":"0x6 ","cores":4,"modelName":"Intel(R) Core(TM)2 Duo CPU T7700 @ 2.40GHz","mhz":2133, (snip...)},
  {"cpu":3,"family":"0x6 ","cores":4,"modelName":"Intel(R) Core(TM)2 Duo CPU T7700 @ 2.40GHz","mhz":2133, (snip...)}
]
```

What do you think?

**Comment by urosgruber** [comment]
I think it's fine, because I don't think motherboards support different kind of physical CPUs installed. The only issue in your case is number of CPUs is wrong. So you have 2 physical and 4 core per CPU, so I guess only 2 items should be in final output?

**Comment by shirou** [comment]
> So you have 2 physical and 4 core per CPU, so I guess only 2 items should be in final output?

I think yes. In addition, these two items both have `cores: 4`.

**Comment by urosgruber** [comment]
Agree and `hw.ncpu=8`

**Comment by shirou** [comment]
ah, [my comment](https://github.com/shirou/gopsutil/issues/304#issuecomment-275388516) was wrong. Thank you.

Then, I will implement these until this weekend.

**Comment by shirou** [comment]
I created #307. Could you check it out? 
And, thank you for your boot messages. I put these files as fixtures. If you don't want to include in this repository, please let me know. I will delete quickly.

**Comment by urosgruber** [comment]
It looks nice and sample messages are ok for fixtures.

**Comment by shirou** [comment]
Thank you for confirmation!

**Comment by urosgruber** [comment]
When do you plane to make new release. I will then try with gohai fix I'm working to support FreeBSD

**Comment by shirou** [comment]
gopsutil has [monthly release schedule](https://github.com/shirou/gopsutil#tag-semantics). So, please wait until end of month... oh, tomorrow!

**Comment by shirou** [comment]
gopsutil v2.17.01 released(tagged).
