### ISSUE TITLE
exit status 1 on Mac OS X, go test fails

### ISSUE THREAD

**Issue by kiwih** [shirou/gopsutil#31]
When calling CPUPercent on OS X (Darwin) I get an error returned with the message "Exit status 1". 
Tracing it through gopsutil reveals that doSysctrl() with argument "kern.cp_time" is throwing an error.
This is because OS X doesn't have "kern.cp_time" in /usr/sbin/sysctl

As a result, go test fails on OS X.
```
--- FAIL: TestCpu_times (0.00 seconds)
	cpu_test.go:13: error exit status 1
	cpu_test.go:16: could not get CPUs  exit status 1
--- FAIL: TestCPUPercent (0.00 seconds)
	cpu_test.go:64: error exit status 1
	cpu_test.go:68: wrong number of entries from CPUPercent: []
--- FAIL: TestCPUPercentPerCpu (0.00 seconds)
	cpu_test.go:64: error exit status 1
	cpu_test.go:68: wrong number of entries from CPUPercent: []
```

**Comment by jcooklin** [comment]
+1

**Comment by AaronO** [comment]
:+1: Experiencing this error too

**Comment by shirou** [comment]
Sorry to keep you waiting, I just implement CPUTimes on darwin, by adhoc compiling the tiny c program which can output cpu times. This is very hacky way, but it works, I think.

**Comment by shirou** [comment]
Due to the #57 (thanks for pquerna), it only enabled when `ALLLOW_INSECURE_CPU_HELPER` set to "yes". 
This behavior is temporary. When I find another way, it will be changed completely. 

Thank you

**Comment by shirou** [comment]
Since I change to use CGO on darwin, close this issue. If you find something, please re-open. Thank you.
