### ISSUE TITLE
proc.Percent()

### ISSUE THREAD

**Issue by adityacs** [shirou/gopsutil#318]
I am trying to get cpu usage for a process. However, I am getting 0 as the value always. 
Below is my sample code. I am using telegraf procstat plugin. Even there it's returning 0 value

`
func main() {

    var pid int32
    pid = 10172
    proc, _ := process.NewProcess(pid)
    p, err := proc.Percent(time.Duration(0))
    if err != nil {
       fmt.Println(err)
    }
}`

Thanks

**Comment by adityacs** [comment]
I feel there is a small bug in the code. In calling "ret := calculatePercent(p.lastCPUTimes, cpuTimes, delta, numcpu)". p.lastCPUTimes and cpuTimes both are same and hence delta_proc := t2.Total() - t1.Total() returns 0 value.

`func (p *Process) Percent(interval time.Duration) (float64, error) {
        cpuTimes, err := p.Times()
        fmt.Println(cpuTimes)
        if err != nil {
                return 0, err
        }
        now := time.Now()

        if interval > 0 {
                p.lastCPUTimes = cpuTimes
                p.lastCPUTime = now
                time.Sleep(interval)
                cpuTimes, err = p.Times()
                now = time.Now()
                fmt.Println("hi")
                if err != nil {
                        return 0, err
                }
        } else {
                if p.lastCPUTimes == nil {
                        // invoked first time
                        p.lastCPUTimes = cpuTimes
                        p.lastCPUTime = now
                        return 0, nil
                }
        }

        numcpu := runtime.NumCPU()
        delta := (now.Sub(p.lastCPUTime).Seconds()) * float64(numcpu)
        ret := calculatePercent(p.lastCPUTimes, cpuTimes, delta, numcpu)
        p.lastCPUTimes = cpuTimes
        p.lastCPUTime = now
        //fmt.Println(ret)
        return ret, nil
}

func calculatePercent(t1, t2 *cpu.TimesStat, delta float64, numcpu int) float64{
         fmt.Println(delta)
        if delta == 0 {
                return 0
        }
        delta_proc := t2.Total() - t1.Total()
        fmt.Println("bye")
        fmt.Println(t2.Total())
        fmt.Println(t1.Total())
        overall_percent := ((delta_proc / delta) * 100) * float64(numcpu)
        //fmt.Println(overall_percent)
        return overall_percent
}
`

**Comment by adityacs** [comment]
if interval > 0:
   time.Sleep(interval) 
doesn't seem to be working. If I add 5 seconds sleep I can see some value

Below is the change I made 
` if interval > 0 {
                p.lastCPUTimes = cpuTimes
                p.lastCPUTime = now
                time.Sleep(10 * time.Second)
                cpuTimes, err = p.Times()
                now = time.Now()
                fmt.Println("hi")
                if err != nil {
                        return 0, err
                }
`

Also, 
 if p.lastCPUTimes == nil {
                        // invoked first time
                        p.lastCPUTimes = cpuTimes
                        p.lastCPUTime = now
                         fmt.Println(p.lastCPUTimes)
                        return 0, nil
                }
why the code is returning 0 here?

**Comment by sparrc** [comment]
@adityacs do you have proof that the CPU usage of your process is not 0?

**Comment by adityacs** [comment]
I have verified this on many processes. It will show 0 value. However, if I do sleep for 3 to 5 secs then I can get the value.

**Comment by sparrc** [comment]
I think this issue can be closed,

@adityacs  in this comment you are only collecting the process information once: https://github.com/shirou/gopsutil/issues/318#issue-209248488

CPU usage requires TWO data points in order to be calculated (and there needs to be measurable time between the two collections). So your first collection will always be 0.

Try sleeping for a few hundred milliseconds between two collections and you should see a usage reading.

**Comment by adityacs** [comment]
@sparrc sleeping is handled by this part of the code right?. line `time.Sleep(interval) `
```
if interval > 0 { 
p.lastCPUTimes = cpuTimes 
p.lastCPUTime = now 
time.Sleep(interval) 
cpuTimes, err = p.Times() now = time.Now()
 if err != nil {
   return 0, err 
}

```
what will be the use of the else part?


```
else {
                if p.lastCPUTimes == nil {
                        // invoked first time
                        p.lastCPUTimes = cpuTimes
                        p.lastCPUTime = now
                        return 0, nil
                }
```

**Comment by sparrc** [comment]
Where is that code from exactly? I was referring to your `main()` function that you pasted above.

Would help if you could try formatting your code a bit better, use "\`\`\`" to surround either side of a single block of code.

**Comment by adityacs** [comment]
in https://github.com/shirou/gopsutil/blob/master/process/process.go
```
func (p *Process) Percent(interval time.Duration) (float64, error) {
	cpuTimes, err := p.Times()
	if err != nil {
		return 0, err
	}
	now := time.Now()

	if interval > 0 {
		p.lastCPUTimes = cpuTimes
		p.lastCPUTime = now
		time.Sleep(interval)
		cpuTimes, err = p.Times()
		now = time.Now()
		if err != nil {
			return 0, err
		}
	} else {
		if p.lastCPUTimes == nil {
			// invoked first time
			p.lastCPUTimes = cpuTimes
			p.lastCPUTime = now
			return 0, nil
		}
	}

	numcpu := runtime.NumCPU()
	delta := (now.Sub(p.lastCPUTime).Seconds()) * float64(numcpu)
	ret := calculatePercent(p.lastCPUTimes, cpuTimes, delta, numcpu)
	p.lastCPUTimes = cpuTimes
	p.lastCPUTime = now
	return ret, nil
}
```

**Comment by adityacs** [comment]
Some sleep is required for calculating cpu_percent. For processes which use low cpu(just running in background without high usage of the process), /proc/pid/stat show same values over the time as shown in below scrreenshot
![splunk-pid](https://cloud.githubusercontent.com/assets/7681197/23225718/ea40cdae-f958-11e6-8753-3cb3c6707167.PNG)

For processes which are constantly in use, cpu usage will be updated frequently as shown in below screenshot
![influx-pid](https://cloud.githubusercontent.com/assets/7681197/23225824/5058b228-f959-11e6-9ff7-1432dc7055e9.PNG)

If we don't add a sleep of at least 100ms we will be getting 0% cpu for processes consuming less cpu, which is not correct.  Also, cpu usage may be 0 in the current millisecond and and 0.2% in next millisecond. So, on the average of 1-3 seconds we can get the cpu_percent.

I may be wrong. At least that is how i see other systems implementing the calculation of cpu_usage.

**Comment by adityacs** [comment]
Any update on this?

**Comment by sparrc** [comment]
@adityacs so what are you saying is the bug? proc.Percent already provides a way to call it with a sleep. Are you asking that the default behavior be changed?

**Comment by adityacs** [comment]
@sparrc  If we don't change the implementation here, then in telegraf procstat plugin we will have to add some sleep instead of time.Duration(0).

**Comment by sparrc** [comment]
no it won't, proc.Percent() caches the previous call and uses that if time.Duration == 0

**Comment by adityacs** [comment]
some references below
https://github.com/Leo-G/DevopsWiki/wiki/How-Linux-CPU-Usage-Time-and-Percentage-is-calculated
http://stackoverflow.com/questions/23367857/accurate-calculation-of-cpu-usage-given-in-percentage-in-linux

**Comment by adityacs** [comment]
@sparrc In telegraf my interval is 10s. However, I always receive "0"% for cpu_usage.

**Comment by adityacs** [comment]
@sparrc "no it won't, proc.Percent() caches the previous call and uses that if time.Duration == 0". Caching is working for me absolutely fine when I try from a sample code. I am not sure why from telegraf I am getting "0" value.

**Comment by sparrc** [comment]
@adityacs I think you are confusing a telegraf issue with a gopsutil issue. The problem is a recently merged PR on the master branch of Telegraf. I am reverting that commit here: https://github.com/influxdata/telegraf/pull/2479

@shirou I think you can close this issue.

**Comment by adityacs** [comment]
@sparrc Sorry for the confusion. In my first comment of this issue itself I mentioned I am using procstat telegraf pluign. 
NP. 
Thanks for fixing this.

**Comment by shirou** [comment]
@sparrc Thank you for your replying.

@adityacs If you find some other problem related to gopsutil, feel free to open a new issue.

**Comment by adityacs** [comment]
@shirou Sure

Thanks
