### ISSUE TITLE
net_linux.go getProcInodes() function may lead open too many files error

### ISSUE THREAD

**Issue by RingXu999** [shirou/gopsutil#321]
os:linux ubuntu 16.04
line 406: f, err := os.Open(dir) and never close it . 
i don't know if this code will lead some resource problem?
is it the file will close only when gc collect it ? so if call the Connections function many times in seconds will open too many file?
sry about my weak english ^ ^! and thx u

**Comment by shirou** [comment]
Thanks for @toshipiazza, `Close` is added by #319.
But thank you for reporting. I close this issue, if you find something, feel free to re-open or create new issue.
