### ISSUE TITLE
getMachineGuid() function return a empty value in x86 windows builds

### ISSUE THREAD

**Issue by molecul** [shirou/gopsutil#322]
getMachineGuid() function return a empty value in x86 windows builds.

Test file: https://gist.github.com/molecul/550c9655f5006a37c06227b44b421f9a

Results
x86: http://pastebin.com/qYiUNJcC
amd64: http://pastebin.com/RcRF7TBW

**Comment by shirou** [comment]
close via #323 and #324. Thank a lot!
