### ISSUE TITLE
Adding temperature measures

### ISSUE THREAD

**Issue by dotpy3** [shirou/gopsutil#329]
This is a proposition for an additional feature for gopsutil.

I've noticed **CPU temperature measures** were not available in gopsutil. I need such measures in one of my projects for macOS and Linux where I use gopsutil, so I started looking into a possible implementation of this.

## Linux

The python psutil exposes a [`sensors_temperatures()`](http://pythonhosted.org/psutil/#sensors) function, that returns the current temperatures of multiple sensors. It is, however, only available for Linux for the moment. The way it is implemented is detailed [in the source code](https://github.com/giampaolo/psutil/blob/1922a7674011852b64f3405e47113ba540a86c77/psutil/_pslinux.py): they use the `/sys/class/hwmon` interface. The drawback with this implementation is that it isn't explicitly indicated which sensors measure CPU temperature - which means it is up to the user to determinate it.

## macOS

Even though their implementation doesn't support macOS, I've started to look if there were pieces of software that allowed the same thing. There is a Ruby program, called [iStats](https://github.com/Chris911/iStats), that shows system stats, including CPU temperature:

```
$ iStats
--- CPU Stats ---
CPU temp: 55.0°C ▁▂▃▅▆▇

--- Fan Stats ---
Total fans in system: 1
Fan 0 speed: 0.0 RPM  ▁▂▃▅▆▇

[...]
```

The way it is implemented in the package is through a C library, [`smc.c`](https://github.com/Chris911/iStats/blob/master/ext/osx_stats/smc.c), that acts as an interface to the Apple System Management Control tool (that has such information).

## Implementation proposition

Given that we would like a platform-agnostic implementation, what we could do is provide a global `get_sensors_temperatures()` function, that would:
+ In the case of a Linux machine, return all the sensors' temperatures as a list
+ In the case of a macOS, return only the CPU's temperature, but as a list, to match the types of the Linux implementation (unless there are other temperature sensors that could be interesting to expose?).

Information retrieval would be trivial on Linux, considering the source code of the python version of `psutil`, but the macOS implementation would either require to import `smc.c` through Cgo, or using a full-Go version. It seems there is a [Go port of smc](https://github.com/hnw/go-smc), that is built with Cgo.

What do active contributors think? Do you think it could be worth it to implement this? If so, what approach should we take into implementing this?

**Comment by shirou** [comment]
Thank you for suggestion. I agree CPU temperature is important information and since psutil supports it, gopsutil either.

## Mac OS

gopsutil already has some cgo functions. `cpu_darwin_cgo.go` and `cpu_darwin_nocgo.go` are in the `cpu` modules. We can implement in the `cpu_darwin_cgo.go` file and add empty function to the `cpu_darwin_nocgo`.

## FreeBSD

```
% sysctl dev.cpu | grep temperature
dev.cpu.0.temperature: 60.0C
dev.cpu.1.temperature: 60.0C
dev.cpu.2.temperature: 59.0C
dev.cpu.3.temperature: 58.0C
```
But, `kldload coretemp` is needed. if not loaded, nothing returns.

## Windows

I did not checked yet, but [this](http://stackoverflow.com/questions/24004300/batch-file-get-cpu-temperature-in-c-and-set-as-variable) can be worked.

```
wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CurrentTemperature
```

I can implement freebsd and windows. If you can make PR on linux or mac, I appreciate it very much.

**Comment by dotpy3** [comment]
I would be interested in implementing it for Linux and Mac, yes. Regarding the macOS version, what approach do you think we should take in interfacing with the SMC? I figured we can either copy the [`smc.c` file](https://github.com/hnw/go-smc/blob/master/smc/_smc.c) in the repo, but that means we will have a C file in the repo (furthermore, not written by a contributor) ; or, we can translate in Go, although expensive in terms of time. What do you think? Would you prefer a complete rewrapping in Go of the interface with the Cocoa interface?

**Comment by shirou** [comment]
I understand what you concern. I search how to use *IOKit* via native golang function such as syscall. But I can not. So it seems porting to pure golang is very difficult.

We don't have a policy to not include C files yet, so I think you can add some C files. However, since [go-smc](https://github.com/hnw/go-smc) does not have a explicit LICENSE, we can not include. [iStat](https://github.com/Chris911/iStats) is a MIT LICENSE, so we should use this file, I think.

**Comment by shirou** [comment]
Sorry for late response. Thank you for your delight contribution #334, it seems fixed. If you have any other problem, feel free to re-open or create new issue. Thank you!

**Comment by soilSpoon** [comment]
> Thank you for suggestion. I agree CPU temperature is important information and since psutil supports it, gopsutil either.
> 
> ## Mac OS
> gopsutil already has some cgo functions. `cpu_darwin_cgo.go` and `cpu_darwin_nocgo.go` are in the `cpu` modules. We can implement in the `cpu_darwin_cgo.go` file and add empty function to the `cpu_darwin_nocgo`.
> 
> ## FreeBSD
> ```
> % sysctl dev.cpu | grep temperature
> dev.cpu.0.temperature: 60.0C
> dev.cpu.1.temperature: 60.0C
> dev.cpu.2.temperature: 59.0C
> dev.cpu.3.temperature: 58.0C
> ```
> But, `kldload coretemp` is needed. if not loaded, nothing returns.
> 
> ## Windows
> I did not checked yet, but [this](http://stackoverflow.com/questions/24004300/batch-file-get-cpu-temperature-in-c-and-set-as-variable) can be worked.
> 
> ```
> wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CurrentTemperature
> ```
> I can implement freebsd and windows. If you can make PR on linux or mac, I appreciate it very much.

Windows does not support depending on the motherboard or cpu. Is it supportable?

**Comment by Lomanic** [comment]
Yes but with some work, see https://github.com/shirou/gopsutil/issues/472#issuecomment-405033594.
