### ISSUE TITLE
Flatten() returns empty slice while reusing Set.

### ISSUE THREAD

**Issue by szyhf** [shirou/gopsutil#337]
find a bug while using set, I'll make a PR late.

``` go
set := set.New()
set.Add(1)
set.Add(2)
fmt.Println(set.Flatten()) // console: [1 2]
set.Dispose()
newSet := set.New(1)
fmt.Println(set.Flatten()) // console:[] expect:[1]
```

Reason:

While dispose an set, the `flattened` was just set to `set.flattened[:0]` in order to save the alloc for slice.

Every time calling updating function such like `Add(...)` or `Remove(...)` will reset `flattened` to nil.

And while calling `Flatten()`, if the `flattened` equals `nil`, will not recreate slice.

But while calling `New(...)` with init items, the `flattened` won't set to nil and next time to call `Flatten()` will got `flattened != nil` and return empty slice.

**Comment by shirou** [comment]
Hi, this is `gopsutil` repository, no `set`, `Add`, `Remove`, or `Flatten` function is proposed. I wonder if I think you are making a PR to wrong repository.

**Comment by szyhf** [comment]
Oh sorry ... I made a mistake Orz
