### ISSUE TITLE
No go-native disk structs for darwin/i386 

### ISSUE THREAD

**Issue by t0xicCode** [shirou/gopsutil#348]
While `gopsutil/host` has an implementation of the go-native disk structs for _darwin/i386_, `gopsutil/host` does not have a similar implementation. This makes it so that cross compilation without a cgo cross-compiler is not feasible for that package.

**Comment by shirou** [comment]
You mean `gopsutil/host` has , but `gopsutil/disk` has not? If so, you are right. But I have not a darwin/i386 environment, so I can not support. If you have such an environment, could you send a PR? Thanks!

**Comment by Lomanic** [comment]
Closing as per https://github.com/shirou/gopsutil/issues/407#issuecomment-939314422 and this kind of hardware is quite hard to come by to generate the necessary files (with mktypes.sh).
