### ISSUE TITLE
too many errors in openbsd  GOARCH=386

### ISSUE THREAD

**Issue by yanghuxiao** [shirou/gopsutil#349]
I build on openbsd amd64, then set GOARCH=386,show the error like : 
```github.com/shirou/gopsutil/disk
src/github.com/shirou/gopsutil/disk/disk_openbsd.go:19: undefined: MNT_WAIT
src/github.com/shirou/gopsutil/disk/disk_openbsd.go:24: undefined: Statfs
src/github.com/shirou/gopsutil/disk/disk_openbsd.go:25: undefined: MNT_WAIT
src/github.com/shirou/gopsutil/disk/disk_openbsd.go:29: undefined: MNT_RDONLY
src/github.com/shirou/gopsutil/disk/disk_openbsd.go:32: undefined: MNT_SYNCHRONO                                        US
src/github.com/shirou/gopsutil/disk/disk_openbsd.go:35: undefined: MNT_NOEXEC
src/github.com/shirou/gopsutil/disk/disk_openbsd.go:38: undefined: MNT_NOSUID
src/github.com/shirou/gopsutil/disk/disk_openbsd.go:41: undefined: MNT_NODEV
src/github.com/shirou/gopsutil/disk/disk_openbsd.go:104: undefined: Statfs
src/github.com/shirou/gopsutil/disk/disk_openbsd.go:119: undefined: Diskstats
src/github.com/shirou/gopsutil/disk/disk_openbsd.go:41: too many errors
# github.com/shirou/gopsutil/mem
src/github.com/shirou/gopsutil/mem/mem_openbsd.go:15: undefined: CTLVm
src/github.com/shirou/gopsutil/mem/mem_openbsd.go:15: undefined: VmUvmexp
src/github.com/shirou/gopsutil/mem/mem_openbsd.go:20: undefined: sizeOfUvmexp
src/github.com/shirou/gopsutil/mem/mem_openbsd.go:23: undefined: Uvmexp
src/github.com/shirou/gopsutil/mem/mem_openbsd.go:33: undefined: CTLVm
src/github.com/shirou/gopsutil/mem/mem_openbsd.go:33: undefined: VmUvmexp
src/github.com/shirou/gopsutil/mem/mem_openbsd.go:38: undefined: sizeOfUvmexp
src/github.com/shirou/gopsutil/mem/mem_openbsd.go:41: undefined: Uvmexp
src/github.com/shirou/gopsutil/mem/mem_openbsd.go:62: undefined: CTLVfs
src/github.com/shirou/gopsutil/mem/mem_openbsd.go:62: undefined: VfsGeneric
src/github.com/shirou/gopsutil/mem/mem_openbsd.go:62: too many errors
```

**Comment by shirou** [comment]
Currently, OpenBSD/amd64 is only supported.

**Comment by shirou** [comment]
I close this issue. I am not familiar with OpenBSD/i386 (yet), if you want to support, please send PR. Thank you.

**Comment by araujobsd** [comment]
It doesn't support OpenBSD/amd64, too many errors on that arch too:

src/github.com/shirou/gopsutil/process/process.go:135:15: undefined: Pids
src/github.com/shirou/gopsutil/process/process.go:156:20: p.Times undefined (type *Process has no field or method Times)
src/github.com/shirou/gopsutil/process/process.go:166:20: p.Times undefined (type *Process has no field or method Times)
src/github.com/shirou/gopsutil/process/process.go:209:25: p.MemoryInfo undefined (type *Process has no field or method MemoryInfo)
src/github.com/shirou/gopsutil/process/process.go:224:20: p.CreateTime undefined (type *Process has no field or method CreateTime)
src/github.com/shirou/gopsutil/process/process.go:229:16: p.Times undefined (type *Process has no field or method Times)
src/github.com/shirou/gopsutil/process/process_posix.go:128:16: p.Uids undefined (type *Process has no field or method Uids, but does have uids)
*** Error code 2

Stop.
make: stopped in /z/go/bhyve-vm-goagent
