### ISSUE TITLE
Reading temperature results in a panic (file not found)

### ISSUE THREAD

**Issue by rollcat** [shirou/gopsutil#352]
The library is trying to access the file path:

> panic: open /sys/class/hwmon/hwmon0name: no such file or directory

This is most probably the result of paths being concatenated (which is Evil):

https://github.com/shirou/gopsutil/blob/master/host/host_linux.go#L546

Using [`path/filepath.Join`](https://golang.org/pkg/path/filepath/#Join) would fix this.

**Comment by shirou** [comment]
Definitely. Could you check #353 ? Thank you.

**Comment by shirou** [comment]
#353 is merged. Thank you.
