### ISSUE TITLE
Wrong type for cpu.CPUTimesStat

### ISSUE THREAD

**Issue by codeskyblue** [shirou/gopsutil#37]
The code is
```
type CPUTimesStat struct {
    CPU       string  `json:"cpu"`
    User      float32 `json:"user"`
    System    float32 `json:"system"`
    Idle      float32 `json:"idle"`
    Nice      float32 `json:"nice"`
    Iowait    float32 `json:"iowait"`
    Irq       float32 `json:"irq"`
    Softirq   float32 `json:"softirq"`
    Steal     float32 `json:"steal"`
    Guest     float32 `json:"guest"`
    GuestNice float32 `json:"guest_nice"`
    Stolen    float32 `json:"stolen"`
}
```

But shouldn't the type Nice Idle, User, System be the type of `uint64` ?

**Comment by shirou** [comment]
because it is divided by CLOCK_TICKS. please read the original psutil code 
https://github.com/giampaolo/psutil/blob/master/psutil/_pslinux.py#L233

...oh

I found current gopsutil code is not divided. sorry. will be fixied very soon.

**Comment by codeskyblue** [comment]
I try to implement Process. CPUPercent, but found that float32 will lose some precision.

**Comment by codeskyblue** [comment]
This is my implementation of Process.CPUPercent. Hope can help a little.
<https://gist.github.com/codeskyblue/46588b03d73cd440d11c>

**Comment by shirou** [comment]
Thank you. Is using float64 instead of float32 resolves precision problem?

**Comment by codeskyblue** [comment]
Maybe OK. I think.

**Comment by shirou** [comment]
I changed to float64 at b8dc51929a36660ce6fb18774e7baba65348d9e6. If still you have problem, feel free to reopen this issue.
