### ISSUE TITLE
Windows OS - Plan to include Performance Metrics for each core and processor

### ISSUE THREAD

**Issue by RajGupta-Continuum** [shirou/gopsutil#373]
gopsutil provides overall cpu performance metrics for Windows OS using GetSystemTimes Win32 API.
In case of multiprocessor (and multicore) system, we want performance metrics for each core and processor. 
Can we have this capability?
I can add this capability and propose to use [Win32_PerfFormattedData_Counters_ProcessorInformation](http://library.wmifun.net/cimv2/win32_perfformatteddata_counters_processorinformation.html) WMI class.

**Comment by shirou** [comment]
SInce I am not good at Windows, if you can make a PR for enhance, I will very appreciate.

(#266 might be related)

**Comment by RajGupta-Continuum** [comment]
Thanks for prompt response, I will make a PR for the same.

**Comment by shirou** [comment]
#376 is merged. Thank you so much!
