### ISSUE TITLE
Find top processes by their resource consumption

### ISSUE THREAD

**Issue by mrLSD** [shirou/gopsutil#374]
How to get top processes utilization CPU, Mem, Disk?
Currently via process.Pids() we can fetch all processes. Is it another way?

Additionally how to calculate CPU percentage for process?
For example memory: MemoryPercent()

**Comment by miton18** [comment]
I try to get top 5 process too. Actually, I can get mem usage, but I can't find a good way for CPU usage, process.Percent(0) is equal to 0 because I call it in short times, and set a duration to 1 s for example, make me wait 1s * process count, and it's not possible....
```
for _, pid := range pids {
    prcs, err := processTool.NewProcess(pid)
    if err != nil {
	return err
    }
    ram, err := prcs.MemoryPercent()
    if err != nil {
	return err
    }
    cpu, err := prcs.Percent(0)
    if err != nil {
	return err
    }
    name, err := prcs.Name()
    if err != nil {
        return err
    }
}
```

**Comment by Lomanic** [comment]
psutil doesn't include such kind of (specialized) helper neither. Here is a simple tutorial that shows how to get the 5 processes with highest memory consumption on the system with psutil. https://thispointer.com/python-get-list-of-all-running-processes-and-sort-by-highest-memory-usage/
