### ISSUE TITLE
Does not parse /proc/net/dev correctly on Centos 5 systems

### ISSUE THREAD

**Issue by danielnelson** [shirou/gopsutil#377]
On Centos 5 systems a minor difference in the `/proc/net/dev` file is causing it to not be parsed fully.  

Thanks to the research of @Fiery-Fenix I traced it back to #317.  To add support for interface aliases, we began parsing until `": "`, but on Centos 5 there is no space.  I think a suitable fix would be to parse until the last index of ":".

```
[root@hostA ~]# cat /proc/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
    lo:32108095  555355    0    0    0     0          0         0 32108095  555355    0    0    0     0       0          0
  eth0:5019464820 14784542    0    0    0     0          0     34733 8907551793 12498214    0    0    0     0       0          0
```

**Comment by danielnelson** [comment]
I can work on a fix.

**Comment by danielnelson** [comment]
Nevermind you already fixed this in https://github.com/shirou/gopsutil/pull/357.

**Comment by shirou** [comment]
Roger.

Thanks @ablagoev. Your information and PR save the people.
