### ISSUE TITLE
On Mac OSX (Yosemite) sysctl swap is sometimes 0/0/0

### ISSUE THREAD

**Issue by afinkenstadt** [shirou/gopsutil#38]
```
vm.swapusage: total = 0.00M  used = 0.00M  free = 0.00M  (encrypted)
```

This causes a divide-by-zero result into NaN, and the JSON encoder (rightly) chooses not to serialize it.

**Comment by shirou** [comment]
Thank you for reporting. Since I don't have Yosemite, I will ask my friend who has Yosemite to try sysctl. please be patient.

**Comment by afinkenstadt** [comment]
I was going to suggest that the fix is: if swap space is (all 0's), then return swap-free = swap-used = 0.0%.

**Comment by shirou** [comment]
Ah, now I got it. I add zero check on  cea341c690955299b0cd52f301ea25244db76ab7 .
