### ISSUE TITLE
Retrieve more hardware/asset information

### ISSUE THREAD

**Issue by RajGupta-Continuum** [shirou/gopsutil#383]
As part of retrieving system information, need to extend functionality to capture more hardware/asset information such as bios, baseboard, OS, system, processor, networks and disk. Some attributes are already being captured for OS, network and disk. 

I can provide additional list of attributes if you agree. I am targeting windows implementation first then other platforms (mac, linux).

**Comment by shirou** [comment]
What kind of attributes you want to add? I agree adding attributes itself, however, since gopsutil aim to be platform independent, I don't want to add attributes which can get only one platform.

**Comment by RajGupta-Continuum** [comment]
We need additional hardware information attributes for all three major platforms (windows, linux, mac) though my immediate requirement is for windows but will need them for linux and mac too. I totally agree with you on platform independent aim of this package, so additional attributes can be added/updated in common struct and collected for all platforms. Below is some addtional attributes.

BaseBoard:
	-	Product Name
	-	Manufacturer
	-	SerialNumber
	-	Version
	
BIOS
	-	Product Name
	-	Manufacturer
	-	Version
	-	SerialNumber
	-	SmbiosVersion

Disk
	-	Product
	-	Manufacturer
	-	MediaType
	-	LogicalName
	-	SerialNumber
	-	Partitions
	-	SizeBytes

Let me know your feedback on this.

**Comment by shirou** [comment]
On Disk, we already have some of values.

-	MediaType   -> disk.Usage has `Fstype`
-	SerialNumber -> same as disk.IOCounters
-	Partitions -> same as disk.Partition
-	SizeBytes -> same as disk.Usage has

LogicalName, Product, Manufacturer are not. And some of `BaseBoard` and `BIOS` values are included in `cpu.InfoStat`.

I understand current implementation is not enough. But is it really required such a too detail hardware information for this library? I think it is not suite for this `ps` util. I think now is a time about someone build a new library which can get such a *HardWare* information.

**Comment by RajGupta-Continuum** [comment]
Thanks @shirou for the response. I agree with you and suggestion to create new library for HardWare specific information.

**Comment by blacklat** [comment]
> On Disk, we already have some of values.
...
> * SerialNumber -> same as disk.IOCounters
map[C::{"readCount":803928,"mergedReadCount":0,"writeCount":331464,"mergedWriteCount":0,"readBytes":14406151680,"writeBytes":8491837440,"readTime":335,"writeTime":36,"iopsInProgress":0,"ioTime":0,"weightedIO":0,"name":"C:","**_serialNumber_**":"","label":""}]

**Comment by sundarv85** [comment]
If you land up here, you can check out the following hw specific library

https://github.com/jaypipes/ghw
