### ISSUE TITLE
MacOS cpu.Percent causes cpu.a: no such file or directory

### ISSUE THREAD

**Issue by ibrokemypie** [shirou/gopsutil#385]
On MacOS Sierra with go 1.8.3 installed through homebrew and gopsutil installed ``go get -u github.com/shirou/gopsutil``, ``p, _ := cpu.Percent(time.Duration(1)*time.Second, false)
	return p`` fails to compile with 
```
# command-line-arguments
/usr/local/Cellar/go/1.8.3/libexec/pkg/tool/darwin_amd64/link: cannot open file /usr/local/Cellar/go/
1.8.3/libexec/pkg/darwin_amd64/github.com/shirou/gopsutil/cpu.a: open /usr/local/Cellar/go/1.8.3/libe
xec/pkg/darwin_amd64/github.com/shirou/gopsutil/cpu.a: no such file or directory
```

**Comment by Lomanic** [comment]
It should be `go get -u github.com/shirou/gopsutil/cpu` instead of `go get -u github.com/shirou/gopsutil`
