### ISSUE TITLE
Add to awesome-go list?

### ISSUE THREAD

**Issue by shurcooL** [shirou/gopsutil#39]
This package looks useful, but it's not on the [awesome-go](https://github.com/avelino/awesome-go) list. Perhaps you should add it there so more people can discover it?

**Comment by shirou** [comment]
Thank you. As you know, I am shy Japanese, I'd like to thank if you add on it :wink:

**Comment by shirou** [comment]
Due to my carelessness, I send PR and merged. https://github.com/avelino/awesome-go#miscellaneous

**Comment by shurcooL** [comment]
Awesome! :)
