### ISSUE TITLE
Wrong boot time in lxc containers

### ISSUE THREAD

**Issue by kirgizz** [shirou/gopsutil#390]
In package "host" func BootTime() use btime in /proc/stat to counting host uptime. This behavior a little wrong because in lxd containers btime - it is a hoster boot time, but not container. 
Maybe better get uptime metric in /proc/uptime

**Comment by liquidox** [comment]
Any chance to get this fixed? Quite annoying.

**Comment by shirou** [comment]
Sorry for late response. I open a PR #441 . Could you check this PR is working? Thank you!

**Comment by shirou** [comment]
I think this is solved. if any, feel free to re-open.

**Comment by HeChuanXUPT** [comment]
@shirou 
The same problem when system == "docker" and role == "guest",

**Comment by HeChuanXUPT** [comment]
I check the PR #441 , find some problems
Even read from /proc/uptime, there is no "btime" keyword. You have to change if conditions
```
	for _, line := range lines {
		if strings.HasPrefix(line, "btime") {
			f := strings.Fields(line)
```

**Comment by shirou** [comment]
@HeChuanXUPT 
I created a PR #496 which add docker. Could you check it ?

And, Could you tell me more detail about `Even read from /proc/uptime, there is no "btime" keyword. You have to change if conditions` ? current master is already same code as you described.

**Comment by HeChuanXUPT** [comment]
@shirou 
On docker guest
test code:
```
package main
import (
	"fmt"
	"github.com/shirou/gopsutil/host"
)
func main() {
	fmt.Println(host.Uptime())
}

```
run result:
>  0 could not find btime

strings in /proc/uptime not contain 'btime'
```
	for _, line := range lines {  // lines here like '12345 0' in /proc/uptime
		if strings.HasPrefix(line, "btime") {  // condition is always false 
			f := strings.Fields(line)
			if len(f) != 2 {
				return 0, fmt.Errorf("wrong btime format")
			}
			b, err := strconv.ParseInt(f[1], 10, 64)
			if err != nil {
				return 0, err
			}
			t = uint64(b)
			atomic.StoreUint64(&cachedBootTime, t)
			return t, nil
		}
	}
```
I create a PR #501
