### ISSUE TITLE
OS X: Why `ps` instead of syscalls + libc?

### ISSUE THREAD

**Issue by tejasmanohar** [shirou/gopsutil#397]
I was wondering why you decided to use `ps`, `lsof`, etc. instead of libproc, syscall, libc, etc. like one would do in C and like `ps` and whatnot use under the hood. Did you experiment with the other strategy? It is what `psutils` (python) does.

When PR'ing new methods is it ok to use the other strategy? It feels cleaner.

**Comment by shirou** [comment]
gopsutil aim to be pure golang, not using cgo. Currently cgo is used for some of MacOSX methods only.

**Comment by tejasmanohar** [comment]
@shirou This makes sense. Did you read some documentation on parsing things like `parseKinfoProc` from syscalls in OSX? I am curious to learn more about this :)

**Comment by shirou** [comment]
https://developer.apple.com/
