### ISSUE TITLE
CreateTime() Method for Process returns time in milliseconds and not seconds

### ISSUE THREAD

**Issue by manavgarg** [shirou/gopsutil#400]
The CreateTime() Method for Process returns the Unix timestamp in milliseconds and not seconds. This is a bug in the documentation and the comment listed process_linux.go.

**Comment by Aditya267** [comment]
yes, it's return time in milliseconds, whereas in comments it's mention in seconds

**Comment by shirou** [comment]
Thanks. I fixed it at 5329f8ba79fc14ad7238a3c2e89f776621a35b85
