### ISSUE TITLE
disk IO counter not the same meaning on Linux and Windows ?

### ISSUE THREAD

**Issue by HeChuanXUPT** [shirou/gopsutil#401]
IOCountersStat fields on Linux and Windows are not the same meaning ?

### disk/disk_linux.go
get from /proc/diskstats

### disk/disk_windows.go
get from wmi
```
type Win32_PerfFormattedData struct {
	Name                    string
	AvgDiskBytesPerRead     uint64
	AvgDiskBytesPerWrite    uint64
	AvgDiskReadQueueLength  uint64
	AvgDiskWriteQueueLength uint64
	AvgDisksecPerRead       uint64
	AvgDisksecPerWrite      uint64
}

...

		ret[d.Name] = IOCountersStat{
			Name:       d.Name,
			ReadCount:  uint64(d.AvgDiskReadQueueLength),
			WriteCount: d.AvgDiskWriteQueueLength,
			ReadBytes:  uint64(d.AvgDiskBytesPerRead),
			WriteBytes: uint64(d.AvgDiskBytesPerWrite),
			ReadTime:   d.AvgDisksecPerRead,
			WriteTime:  d.AvgDisksecPerWrite,
		}
```

1. The ReadBytes on Linux is a total number, but on Windows is an average number.
2. no need to cast type of AvgDiskReadQueueLength to uint64, already defined above.

**Comment by shirou** [comment]
Ah, We can not get total number of ReadBytes via WMI interface, so I choose `AvgDiskBytesPerRead`.

However, I checked [sys/windows](https://github.com/golang/sys/blob/master/windows/zsyscall_windows.go#L1693), there are `DeviceIoControl` and perhaps can get [DISK_PERFORMANCE](https://msdn.microsoft.com/ja-jp/library/windows/desktop/aa363991(v=vs.85).aspx). So we should use this instead of WMI.

**Comment by HeChuanXUPT** [comment]
I think the increment number or rate is more useful than the total number.
So how about add more fields ?
If is not easy to get the total num on Windows. it can be 0.

**Comment by sunshinelym** [comment]
On Windows we use AvgDiskBytesPerRead to get ReadBytes. How about this data's delt time? I have tried to fin the documentation but get no answer.

**Comment by sunshinelym** [comment]
@HeChuanXUPT  on Linux I use ReadBytes(t2)-ReadBytes(t1)/t2-t1 to get disk readbytes per second , but on windows  AvgDiskBytesPerRead is already an average value,do you know AvgDiskBytesPerRead's collect delt time?

**Comment by HeChuanXUPT** [comment]
@sunshinelym 
AvgDiskBytesPerRead :
Average number of bytes transferred from the disk during read operations
(https://msdn.microsoft.com/en-us/library/aa394308(v=vs.85).aspx)

**Comment by Lomanic** [comment]
We are now aligned with psutil with #850 being merged.
