### ISSUE TITLE
host.KernelVersion() not implemented for Darwin

### ISSUE THREAD

**Issue by docktermj** [shirou/gopsutil#409]
Although host.KernelVersion() is implemented in Linux,  compiling in a Darwin fails because host.KernelVersion() is not defined in https://github.com/shirou/gopsutil/blob/master/host/host_darwin.go

https://github.com/shirou/gopsutil/blob/d97b1c368aa68169699a4f36a86d560ed361aa0b/host/host_linux.go#L373

**Comment by shirou** [comment]
Thanks for information. I also have fixed at 114c78c777eb86b58e40910cbd3fc451829c366d.
