### ISSUE TITLE
process cpu_percentage is incorrect (centos 7)

### ISSUE THREAD

**Issue by vrecan** [shirou/gopsutil#41]
I was getting unusually high numbers for a proc that was consuming 0.3% of a cpu in top Process.CPUPercent() was giving me between 3% - 7%. So I gave it a pid of a process that was consuming consistently 467% according to top and it gives me 4556.54044031905... How does this number compare to top? Should I be able to do something simple to get close to top numbers?

**Comment by shirou** [comment]
hmm. Could you show me your code?

When I run this code (26671 is some pid), 
```
package main

import(
        "fmt"
        "time"

        "github.com/shirou/gopsutil/process"
)

func main(){
        p, err := process.NewProcess(26671)
        if err != nil{
                fmt.Println(err)
        }
        fmt.Println(p.CPUPercent(time.Second))
}
```

Result is
```
 31.991242461358688 <nil>
```
In same time top said

```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                        
26671 shirou    20   0  105764   2004   1012 R 33.0  0.3   0:11.67 sshd 
```

I tried other process, top said 0.3%, gopsutil said 0.6.

**Comment by vrecan** [comment]
cpuPercent, err := sys.proc.CPUPercent(time.Second)
        if nil != err {
                log.Error(err)
                return
        }
       fmt.Println(cpuPercent)

TOP
```
2834 persist+  20   0  628140   5896   4788 S   0.3  0.0   0:00.38 Vitals
```
Result
```
13.395245461338618
```


The only way I get stats that look right is to divide by 10. Then it's actually really close to correct. This system has 8 cores and 16 virtual cores running centos 7.

**Comment by vrecan** [comment]
actually I have to do this:
```
    cpuPercent, err := sys.proc.CPUPercent(5 * time.Second)
    if nil != err {
            log.Error(err)
            return
    }
   fmt.Println(cpuPercent/10)
```

which makes no sense but seems to be really good.

**Comment by shirou** [comment]
I found my understanding about time delta in CPU percent. I fixed and tested using AWS instance. Could you try it again after `go get -u`?

**Comment by vrecan** [comment]
That seems to have fixed it! Thanks. I really appreciate your library, making my life a lot easier. :)
