### ISSUE TITLE
host.Virtualization() not implemented for Windows

### ISSUE THREAD

**Issue by docktermj** [shirou/gopsutil#411]
Although host.Virtualization() is implemented in Linux, compiling in a Windows fails because host.Virtualization() is not defined in https://github.com/shirou/gopsutil/blob/master/host/host_windows.go

https://github.com/shirou/gopsutil/blob/d97b1c368aa68169699a4f36a86d560ed361aa0b/host/host_linux.go#L432

**Comment by shirou** [comment]
Thanks for information. I have fixed at 114c78c777eb86b58e40910cbd3fc451829c366d.
