### ISSUE TITLE
use of internal package not allowed

### ISSUE THREAD

**Issue by vijaygiri10** [shirou/gopsutil#427]
I am getting this error after replacing  gopsutil PKG, Go version 1.9 64-bit

github.com/shirou/gopsutil/host/host.go:6:2: use of internal package not allowed
github.com/shirou/gopsutil/host/host_darwin.go:18:2: use of internal package not allowed

**Comment by vijaygiri10** [comment]
yes OS is Darwin.
But I don't have sample Code 
Sorry

**Comment by Lomanic** [comment]
If you don't provide any test-case to see what happens or tell us what you are trying to do we won't be able to help diagnose anything and will close this as [invalid](https://github.com/shirou/gopsutil/labels/invalid) unfortunately.

**Comment by vijaygiri10** [comment]
sure
