### ISSUE TITLE
process.NetIOCounters is pointless on Linux

### ISSUE THREAD

**Issue by disq** [shirou/gopsutil#429]
process.NetIOCounters reads data from the `/proc/<pid>/net/dev` file. The contents of this file is the same across all pids, and also equal to the contents of the `/proc/net/dev` file. So the results returned from this function is the same across all processes, and reflects the overall interface metrics.

**Comment by shirou** [comment]
Thank you for your comment. and also psutil process class does not have `net_io_counter`, I will remove it at v3 since it broke current API. I have filed on #362.

**Comment by AtakanColak** [comment]
@shirou @Lomanic is it not possible to gather network usage by process in any way? I was looking for implementing this in windows but turns out even linux method is not giving process specific values...

**Comment by buglloc** [comment]
`process.NetIOCounters` isn't pointless on Linux. It's useful, for example, when we want to get network statistics for nested net ns which process was attached.
Maybe bring back `process.NetIOCounters`? :)

**Comment by AtakanColak** [comment]
@buglloc could you elaborate please? Or perhaps provide links that do so?

**Comment by AtakanColak** [comment]
@shirou @Lomanic Also why is the method still visible if it is removed? I know it doesn't work the way we want it to but was it reintroduced at some point? [Link](https://pkg.go.dev/github.com/shirou/gopsutil@v3.20.11+incompatible/process#Process.NetIOCounters)

**Comment by Lomanic** [comment]
This is removed if you have v3 in the import path. https://pkg.go.dev/github.com/shirou/gopsutil/v3@v3.20.11/process#Process.NetIOCounters (notice how this link/version doesn't have the `+incompatible` suffix as it's now modules-compliant). We didn't change anything on the "v2" non-module aware packages as not to break existing users on v2.
