### ISSUE TITLE
net.Connections("all") returns error if permission denied opening pid directory

### ISSUE THREAD

**Issue by danielnelson** [shirou/gopsutil#433]
When upgrading from v2.17.04 to v2.17.08 we found that it is no longer possible to call `net.Connections("all")` on Linux unless you have permission to read all pid directories in /proc.

```go
func main() {
        res, err := net.Connections("all")
        if err != nil {
                fmt.Println(err)
                return
        }

        for _, item := range res {
                fmt.Println(item)
        }
}
```

With this code the output is `cound not get pid(s), 0`.  It looks like the error is originally from here: https://github.com/shirou/gopsutil/blob/master/net/net_linux.go#L419 and the error string `open /proc/1/fd: permission denied`.  When using the v2.17.04 the `[]net.ConnectionStat` are returned for directories that can be read.

As expected, if ran with root permissions items are returned correctly without erro.

**Comment by shirou** [comment]
Thank you for reporting.
Any error includes permission error stops getting file. 
e01a14e318951de4782908fbdb2b66a652a22065 skip if permission error. It can run on my environment.

Note: you still can not get net information if permission denied.

If this can not fixes your problem, feel free to re-open.

**Comment by danielnelson** [comment]
This fixed the problem, thank you.
