### ISSUE TITLE
go dep save deletes CGO c dependency files

### ISSUE THREAD

**Issue by sakeven** [shirou/gopsutil#437]
host/include has some c source code, but they are deleted when using go tools like godep.
It makes it's hard that the use of vendoring files like godep.
See https://github.com/tools/godep/issues/422 .

**Comment by muratsplat** [comment]
I have some issue too. I can not find any way to use golang `dep` tool  with `gopsutil` library.

**Comment by Lomanic** [comment]
That's the same thing as #832 where a PR will soon be merged to fix this, closing in favor of that issue.
