### ISSUE TITLE
pkg host bug!

### ISSUE THREAD

**Issue by imkos** [shirou/gopsutil#445]
import (
   gohost github.com/shirou/gopsutil/host
)

uses:
gohost.GetOSInfo()

my app use winsvc on windows 7.
Restart the machine, my service process cannot start automatically

**Comment by imkos** [comment]
but...
```go
type Win32_OperatingSystem struct {
	Version        string
	Caption        string
	ProductType    uint32
	BuildNumber    string
	LastBootUpTime time.Time
}

func GetOSInfo() (Win32_OperatingSystem, error) {
	var dst []Win32_OperatingSystem
	q := wmi.CreateQuery(&dst, "")
	err := wmi.Query(q, &dst)
	if err != nil {
		return Win32_OperatingSystem{}, err
	}
	return dst[0], nil
}
```
import "github.com/StackExchange/wmi"  is OK!

**Comment by Lomanic** [comment]
This is not clear, can you please tell us what you are trying to do (a sample code?), what  is the error you are seeing (copy pasting the error message)?

**Comment by Lomanic** [comment]
No news in months from issue opener. Closing.
