### ISSUE TITLE
hang on package import on older-than-2016 windows platforms

### ISSUE THREAD

**Issue by leafnunes** [shirou/gopsutil#451]
We have a golang service uses gopsutil to gather metrics and cpu usage. The first time the binary runs, it hangs forever on a WMI query that never returns (called from the init in `cpu/cpu.go`, Times).

Most of the queries in gopsutil should probably return pretty quickly or timeout.

I have a working change that wraps just the hanging call, but could extend it to every wmi.Query call if that seems reasonable.

**Comment by shirou** [comment]
I close this issue. But the fundamental problem is not solved yet, if you find something, please re-open or create a new issue. Thank you!
