### ISSUE TITLE
window kill process

### ISSUE THREAD

**Issue by jiuker** [shirou/gopsutil#457]
ps, err := process.Processes()
	if err != nil {
		fmt.Println(err)
		return
	}
	for _, v := range ps {
		if vName, err := v.Name(); err == nil && vName == "QQBrowser.exe" {
			p, err := os.FindProcess(int(v.Pid))
			if err != nil {
				fmt.Println(err)
				break
			}
			err = p.Kill()
			if err != nil {
				fmt.Printf("process: %s killed failed\n", vName)
			} else {
				fmt.Printf("process: %s killed success\n", vName)
			}
		}
	}

**Comment by jiuker** [comment]
it will work！

**Comment by Lomanic** [comment]
It should be checked if python's psutil does the same, but feel free to open a PR.

Please [format](https://guides.github.com/features/mastering-markdown/) your code by surrounding it with <code>```</code>.

**Comment by jiuker** [comment]
`package main

import (
	"fmt"
	"os"
	"github.com/shirou/gopsutil/process"
)

func main() {
	ps, err := process.Processes()
	if err != nil {
		fmt.Println(err)
		return
	}
	for _, v := range ps {
		if vName, err := v.Name(); err == nil && vName == "QQBrowser.exe" {
			p, err := os.FindProcess(int(v.Pid))
			if err != nil {
				fmt.Println(err)
				break
			}
			err = p.Kill()
			if err != nil {
				fmt.Printf("process: %s killed failed\n", vName)
			} else {
				fmt.Printf("process: %s killed success\n", vName)
			}
		}
	}
}`
package os provided the way to kill process by Pid,I think it can work out!
You said need be checked,I think so.

**Comment by shirou** [comment]
How about #459 on your environment?
