### ISSUE TITLE
Undocumented time unit in TimesStat structure

### ISSUE THREAD

**Issue by medzin** [shirou/gopsutil#460]
The `TimeStruct` structure is quite undocumented, and its fields have `float64` type which does not help you to guess in what time unit the values are. I can add missing documentation, but I have to know the unit.

**Comment by shirou** [comment]
Thanks! I suppose you mean `cpu.TimesStat` struct, it is based linux `/proc/stat` file format. so, Time unit is `USER_HZ`. to get USER_HZ, type `/usr/bin/getconf CLK_TCK`. mostly 100, 10 milli second. but some systems might have other value.
(FYI: http://www.linuxhowtos.org/System/procstat.htm) .
