### ISSUE TITLE
How can process module filter the processes used by system and return the left used by user?

### ISSUE THREAD

**Issue by baolinCloud** [shirou/gopsutil#463]
Hi, 

I try to use process module to monitor all the processes used by user. 

process.Pids List all the process id, but I can not distinguish between the system processes and the user processes.

Just like the following process list, I am just interested in the processes like "httpd", "redis-server","redis-sentinel", "mysqld" and so on which are not system.

{'pid':1, 'name': "init"}
{'pid':2, 'name': "kthreadd"}
{'pid':3, 'name': "migration/0"}
{'pid':4, 'name': "ksoftirqd/0"}
{'pid':5, 'name': "migration/0"}
{'pid':6, 'name': "watchdog/0"}
{'pid':7, 'name': "migration/1"}
{'pid':8, 'name': "migration/1"}
{'pid':9, 'name': "ksoftirqd/1"}
{'pid':10, 'name': "watchdog/1"}
{'pid':11, 'name': "events/0"}
{'pid':12, 'name': "events/1"}
{'pid':13, 'name': "cgroup"}
{'pid':14, 'name': "khelper"}
{'pid':15, 'name': "netns"}
{'pid':16, 'name': "async/mgr"}
{'pid':17, 'name': "pm"}
{'pid':18, 'name': "sync_supers"}
{'pid':19, 'name': "bdi-default"}
{'pid':20, 'name': "kintegrityd/0"}
{'pid':21, 'name': "kintegrityd/1"}
{'pid':22, 'name': "kblockd/0"}
{'pid':23, 'name': "kblockd/1"}
{'pid':24, 'name': "kacpid"}
{'pid':25, 'name': "kacpi_notify"}
{'pid':26, 'name': "kacpi_hotplug"}
{'pid':27, 'name': "ata_aux"}
{'pid':28, 'name': "ata_sff/0"}
{'pid':29, 'name': "ata_sff/1"}
{'pid':30, 'name': "ksuspend_usbd"}
{'pid':31, 'name': "khubd"}
{'pid':32, 'name': "kseriod"}
{'pid':33, 'name': "md/0"}
{'pid':34, 'name': "md/1"}
{'pid':35, 'name': "md_misc/0"}
{'pid':36, 'name': "md_misc/1"}
{'pid':37, 'name': "linkwatch"}
{'pid':38, 'name': "khungtaskd"}
{'pid':39, 'name': "kswapd0"}
{'pid':40, 'name': "ksmd"}
{'pid':41, 'name': "khugepaged"}
{'pid':42, 'name': "aio/0"}
{'pid':43, 'name': "aio/1"}
{'pid':44, 'name': "crypto/0"}
{'pid':45, 'name': "crypto/1"}
{'pid':50, 'name': "kthrotld/0"}
{'pid':51, 'name': "kthrotld/1"}
{'pid':52, 'name': "pciehpd"}
{'pid':54, 'name': "kpsmoused"}
{'pid':55, 'name': "usbhid_resumer"}
{'pid':85, 'name': "kstriped"}
{'pid':169, 'name': "mpt_poll_0"}
{'pid':170, 'name': "mpt/0"}
{'pid':171, 'name': "scsi_eh_0"}
{'pid':174, 'name': "scsi_eh_1"}
{'pid':175, 'name': "scsi_eh_2"}
{'pid':278, 'name': "jbd2/sda3-8"}
{'pid':279, 'name': "ext4-dio-unwrit"}
{'pid':364, 'name': "udevd"}
{'pid':415, 'name': "bash"}
{'pid':550, 'name': "vmmemctl"}
{'pid':604, 'name': "flush-8:0"}
{'pid':666, 'name': "jbd2/sda1-8"}
{'pid':667, 'name': "ext4-dio-unwrit"}
{'pid':721, 'name': "kauditd"}
{'pid':916, 'name': "auditd"}
{'pid':932, 'name': "rsyslogd"}
{'pid':981, 'name': "sshd"}
{'pid':1050, 'name': "sshd"}
{'pid':1252, 'name': "bash"}
{'pid':1328, 'name': "master"}
{'pid':1335, 'name': "qmgr"}
{'pid':1338, 'name': "crond"}
{'pid':1351, 'name': "mingetty"}
{'pid':1353, 'name': "mingetty"}
{'pid':1355, 'name': "mingetty"}
{'pid':1356, 'name': "udevd"}
{'pid':1358, 'name': "udevd"}
{'pid':1359, 'name': "mingetty"}
{'pid':1361, 'name': "mingetty"}
{'pid':1363, 'name': "mingetty"}
{'pid':1893, 'name': "sshd"}
{'pid':2038, 'name': "bash"}
{'pid':3393, 'name': "go"}
{'pid':3460, 'name': "gopsutil"}
{'pid':4015, 'name': "httpd"}
{'pid':4016, 'name': "httpd"}
{'pid':4017, 'name': "httpd"}
{'pid':4018, 'name': "httpd"}
{'pid':4019, 'name': "httpd"}
{'pid':4020, 'name': "httpd"}
{'pid':4021, 'name': "httpd"}
{'pid':4022, 'name': "httpd"}
{'pid':7487, 'name': "httpd"}
{'pid':7533, 'name': "redis-server"}
{'pid':9092, 'name': "pickup"}
{'pid':14423, 'name': "httpd"}
{'pid':15081, 'name': "sshd"}
{'pid':15426, 'name': "bash"}
{'pid':15948, 'name': "redis-cli"}
{'pid':22268, 'name': "sshd"}
{'pid':22392, 'name': "bash"}
{'pid':24213, 'name': "httpd"}
{'pid':24288, 'name': "httpd"}
{'pid':24302, 'name': "httpd"}
{'pid':25168, 'name': "redis-server"}
{'pid':25527, 'name': "redis-server"}
{'pid':25630, 'name': "netcast-dashboa"}
{'pid':26258, 'name': "redis-server"}
{'pid':26305, 'name': "redis-sentinel"}
{'pid':26330, 'name': "sshd"}
{'pid':26382, 'name': "sftp-server"}
{'pid':30660, 'name': "mysqld_safe"}
{'pid':30864, 'name': "mysqld"}
{'pid':32494, 'name': "sshd"}

**Comment by Lomanic** [comment]
Use [process.Username()](https://godoc.org/github.com/shirou/gopsutil/process#Process.Username) or [process.Uids()](https://godoc.org/github.com/shirou/gopsutil/process#Process.Uids).

**Comment by baolinCloud** [comment]
@Lomanic, thank you for your reply.

 I have tested , but it does not work in Ubuntu 14.04.


part of the code:
`username, _ := p.Username()
uids, _ := p.Uids()
fmt.Printf("username is %v, uids is %v\n", username, uids)`


And Out put is `username is , uids is [0 0 0 0]`

**Comment by Lomanic** [comment]
Please check if the returned error is not `nil`, the following example works for me on openSUSE x64.

```go
package main

import (
        "fmt"

        "github.com/shirou/gopsutil/process"
)

func main() {
        procs, err := process.Processes()
        if err != nil {
                fmt.Println(err)
                return
        }
        for _, proc := range procs {
                username, err := proc.Username()
                if err != nil {
                        fmt.Println(err)
                        return
                }
                uids, err := proc.Uids()
                if err != nil {
                        fmt.Println(err)
                        return
                }
                fmt.Println("pid", proc.Pid, "username", username, "uids", uids)
        }
}
```

**Comment by shirou** [comment]
@baolinCloud if you can not get Username or Uids, please open another issue with appropriate title.

Thank you @Lomanic .

**Comment by baolinCloud** [comment]
Maybe I used an outdated version of the gopsutil library, after I upgrade the lib to the latest version, I successfully get the username and the uids, But I still don't know how to distinguish between the system processes and the user processes.


The following list the output:

pid 239 username root uids [0 0 0 0]
pid 240 username root uids [0 0 0 0]
pid 249 username root uids [0 0 0 0]
pid 254 username root uids [0 0 0 0]
pid 275 username root uids [0 0 0 0]
pid 312 username root uids [0 0 0 0]
pid 374 username root uids [0 0 0 0]
pid 385 username root uids [0 0 0 0]
pid 390 username root uids [0 0 0 0]
pid 400 username root uids [0 0 0 0]
pid 461 username root uids [0 0 0 0]
pid 472 username root uids [0 0 0 0]
pid 494 username root uids [0 0 0 0]
pid 506 username root uids [0 0 0 0]
pid 509 username root uids [0 0 0 0]
pid 521 username root uids [0 0 0 0]
pid 711 username root uids [0 0 0 0]
pid 713 username root uids [0 0 0 0]
pid 892 username root uids [0 0 0 0]
pid 1047 username root uids [0 0 0 0]
pid 1114 username root uids [0 0 0 0]
pid 1147 username root uids [0 0 0 0]
pid 1177 username root uids [0 0 0 0]
pid 1238 username syslog uids [101 101 101 101]
pid 1267 username messagebus uids [102 102 102 102]
pid 1286 username root uids [0 0 0 0]
pid 1302 username root uids [0 0 0 0]
pid 1322 username root uids [0 0 0 0]
pid 1326 username root uids [0 0 0 0]
pid 1340 username root uids [0 0 0 0]
pid 1345 username root uids [0 0 0 0]
pid 1348 username root uids [0 0 0 0]
pid 1349 username root uids [0 0 0 0]
pid 1353 username root uids [0 0 0 0]
pid 1363 username root uids [0 0 0 0]
pid 1364 username root uids [0 0 0 0]
pid 1367 username root uids [0 0 0 0]
pid 1372 username root uids [0 0 0 0]
pid 1398 username root uids [0 1 1 1]
pid 1399 username root uids [0 0 0 0]
pid 1419 username root uids [0 0 0 0]
pid 1421 username root uids [0 0 0 0]
pid 1445 username root uids [0 0 0 0]
pid 1458 username root uids [0 0 0 0]
pid 1475 username whoopsie uids [118 118 118 118]
pid 1477 username root uids [0 0 0 0]
pid 1480 username avahi uids [108 108 108 108]
pid 1485 username avahi uids [108 108 108 108]
pid 1500 username root uids [0 0 0 0]
pid 1512 username root uids [0 0 0 0]
pid 1518 username root uids [0 0 0 0]
pid 1541 username root uids [0 0 0 0]
pid 1544 username root uids [0 0 0 0]
pid 1558 username root uids [0 0 0 0]
pid 1576 username cntlm uids [105 105 105 105]
pid 1595 username root uids [0 0 0 0]
pid 1601 username kernoops uids [116 116 116 116]
pid 1637 username root uids [0 0 0 0]
pid 1638 username tomcat uids [1002 1002 1002 1002]
pid 1895 username root uids [0 0 0 0]
pid 1931 username root uids [0 0 0 0]
pid 1933 username root uids [0 0 0 0]
pid 1971 username root uids [0 0 0 0]
pid 1990 username root uids [0 0 0 0]
pid 2031 username xrdp uids [120 120 120 120]
pid 2033 username root uids [0 0 0 0]
pid 2045 username root uids [0 0 0 0]

**Comment by baolinCloud** [comment]
OK,  sorry about that. Thank you!
