### ISSUE TITLE
How to get the CPU usage of the background process on the windows platform.

### ISSUE THREAD

**Issue by ArnoldFu** [shirou/gopsutil#466]
The 'process.CPUPercent()' method works for front process, but it does not works for background process. The program prompts 'could not get CreationDate: Access is denied'.
How to get the CPU usage of the background process on the windows platform.

**Comment by Lomanic** [comment]
I can reproduce, it occurs for processes run by `NT AUTHORITY\SYSTEM`, `NT AUTHORITY\NETWROK`, `NT AUTHORITY\LOCAL` and [it looks like](https://stackoverflow.com/q/28708/2583075) it has to do with SeDebugPrivilege. With admin rights it seems doable to port [this C# program](http://hintdesk.com/c-how-to-enable-sedebugprivilege/) to enable SeDebugPrivilege for the current process with windows syscalls. Python's psutil indeed has a function [psutil_set_se_debug](https://github.com/giampaolo/psutil/blob/f2607defff6313a1acecaf5e59d8b27ce5b63855/psutil/arch/windows/security.c#L161-L195) called [here](https://github.com/giampaolo/psutil/blob/34fb3666859bda349afdc9b4397b0b7a715f08de/psutil/_psutil_windows.c#L3809).

I can work on this during the weekend if nobody takes this task.

**Comment by shirou** [comment]
@Lomanic Thank you! Since I can not work this weekend, I would very appreciate if you can work on this issue.

**Comment by ArnoldFu** [comment]
@Lomanic 
Yes, the processes run by `NT AUTHORITY\SYSTEM`. 
I have already run the program as an administrator, but it doesn't works.
I would very grateful if you could help me solve this problem.

**Comment by Lomanic** [comment]
So far I have the above commit, but it is currently not functional (Access Denied even as admin), I don't know what the problem is, maybe I will look at it in the future. Anybody can take this task in the mean time.

**Comment by fanlw0816** [comment]
I have also encountered this problem, Is this problem solved?

**Comment by onkarbanerjee** [comment]
Is this solved. I dont think it is yet.

**Comment by Lomanic** [comment]
This was fixed by the commit that closed this issue, as usual on Github.
