### ISSUE TITLE
[Windows] cpu.Info() timing out

### ISSUE THREAD

**Issue by FlorinAsavoaie** [shirou/gopsutil#469]
In `github.com/shirou/gopsutil/internal/common`, there is a Timeout hardcoded for the WMI queries. When the CPU is busy, `cpu.Info()` (and maybe other stuff as well) is failing as the WMI is taking too long to respond to the query. I would expect to be able to pass this Timeout from my code.

**Comment by vrecan** [comment]
I've run into this a few times as well. It would be nice to be able to pass in the context timeouts or set them in some way.

**Comment by shirou** [comment]
I have added plan to v3 (#362) about `WithContext` method.

**Comment by sadag** [comment]
Please review PR #488

**Comment by Lomanic** [comment]
Closing as a duplicate of #394 (as always, WMI calls should be avoided)
