### ISSUE TITLE
FAIL: TestUsers

### ISSUE THREAD

**Issue by nicolasStevenin** [shirou/gopsutil#476]
Hello
When I try to test the repository host, it fails with
```
#host :  FAIL: TestUsers (0.00s)
#        host_test.go:53: error open /var/run/utmp: no such file or directory
#        host_test.go:57: Users is empty
```
Thank you for your help

**Comment by Lomanic** [comment]
Which OS are you using? What is the command you use to try to run these failing tests?

**Comment by nicolasStevenin** [comment]
I'm using CentOS 7 and it fails when i run 
go test -compiler gc -ldflags ' -extldflags '\''-Wl,-z,relro  '\'''

**Comment by stapelberg** [comment]
I’m running into the same issue when running the tests in a Docker container, where /var/run/utmp is empty.

I think we should add a utmp file to `host/testdata/` and use that instead of the host’s utmp file.

**Comment by shirou** [comment]
On CentOS7 machine, t2.micro, this works.
```
go test -compiler gc -ldflags ' -extldflags '''-Wl,-z,relro ''''
```
I close this issue, feel free to re-open if problem stil exists.

@stapelberg 
Inside docker, there utmp is empty. So please volume mount it and set `HOST_VAR` environment variable like `HOST_VAR=/host_mounted/var`.
