### ISSUE TITLE
FAIL: Test_Children

### ISSUE THREAD

**Issue by nicolasStevenin** [shirou/gopsutil#477]
Hello,

When I try to test the repo process, it fails with 
```
process : pushd /builddir/build/BUILD/gopsutil-2.17.11/_build/src/github.com/shirou/gopsutil/process
+ go test -compiler gc -ldflags ' -extldflags '\''-Wl,-z,relro  '\'''
--- FAIL: Test_Children (0.00s)
        process_test.go:360: error process does not have children
```
Thank you for your help

**Comment by Lomanic** [comment]
Which OS are you using? What is the command you use to try to run these failing tests?

**Comment by nicolasStevenin** [comment]
I'm using CentOS 7 and it fails when i run
go test -compiler gc -ldflags ' -extldflags '''-Wl,-z,relro ''''

**Comment by Lomanic** [comment]
This test was recently changed so it doesn't rely on process with PID 1 being the init process and having children, I couldn't reproduce your issue using `centos:centos7` docker image, can you try again?

**Comment by saurabhghumnar** [comment]
Hi, 
just a quick query, this test seems to work perfectly fine on Centos but it produces the below error on Rhel or UBI containers.
Can you please spare a minute to elaborate why this issue occurs.

=== RUN   Test_Children
    process_test.go:525: error process does not have children
--- FAIL: Test_Children (0.10s)

Thank you !
