### ISSUE TITLE
Passing the device name to IOCounters

### ISSUE THREAD

**Issue by verticelo** [shirou/gopsutil#479]
Hi there,

System: Ubuntu 16.04

partitions, err := disk.Partitions(false)

We get partitions.Device == "/dev/sda1"

Passing this to disk.IOCounters(partitions.Device) yields an empty map.

Reason is /proc/diskstats has the following format:
8       1 sda1 56476 31 1956637 155620 35171 66896 4245728 985412 0 76604 1141648

So, one should pass "sda1" rather than "/dev/sda1".

Is this a known / wanted behavior? Do other OSs /proc/diskstats list the disk as "sda1" or "/dev/sda1"?

If other OSs uses the /dev/* format perhaps we could change IOCounters to split the strings passed to it and utilize the last portion of the string only when doing the lookup for a match. This way it becomes more intuitive and hides the formatting of device names.

**Comment by Lomanic** [comment]
This looks like the same issue as https://github.com/giampaolo/psutil/issues/942 (notice that [`psutil.disk_io_counters(perdisk=True)`](https://psutil.readthedocs.io/en/latest/#psutil.disk_io_counters) returns `sda1` where [`psutil.disk_partitions()`](https://psutil.readthedocs.io/en/latest/#psutil.disk_partitions) returns `/dev/sda3` in their respective examples).

I'm not familiar with this part of the code and will wait for @shirou's input on this, but this seems a good catch @verticelo.

**Comment by shirou** [comment]
Yes, good catch! I created #481 for both `/dev/sda1` and `sda1`. If you confirm this PR works, I will merge it. Thank you!

**Comment by verticelo** [comment]
@shirou Sorry for late reply here. I haven't been working on this for a couple of weeks and haven't had time to check it yet. Thank you for your work!
