### ISSUE TITLE
cpu#TimesStat should be more precise, may be time.Duration

### ISSUE THREAD

**Issue by Herobs** [shirou/gopsutil#482]
I need more precise time process#Times() return, second is too rough. time.Duration may be a better choice.

**Comment by Herobs** [comment]
PR will be welcomed?

**Comment by shirou** [comment]
`process.Times()` just return a process CPU times information at that invoked time. Could you tell me what meaning of `precise time`?

Perhaps PR is more easy to understand what you want and it always welcome.

**Comment by Herobs** [comment]
I need the millisecond in my project.

**Comment by shirou** [comment]
`TimesStat` just holds an amount of times the CPU spent and it is calculated the value from `/proc/stat` and divided by `ClockTicks`. No duration is used. If you want to know how much that process spent CPU times in millisecond, you just call twice in milliseconds and calculate the difference.

**Comment by Herobs** [comment]
I got the problem, I am seeing the windows process#Times https://github.com/shirou/gopsutil/blob/7ec06ec280df1dd1f08befc535049d49d63ae18a/process/process_windows.go#L300-L310

Another problem appear, different behavior show on different platform.

**Comment by Herobs** [comment]
I seem all my bad, misunderstanding the jeffies unit. All platforms are in second, but it is float64, no precise lose. Thanks anyway.
