### ISSUE TITLE
docker.CgroupDockerStat has no field or method String

### ISSUE THREAD

**Issue by sundarv85** [shirou/gopsutil#483]
I am having this code, that I would like to compile and run it 

```
	ds, err := docker.GetDockerStat()
	if err != nil {
		fmt.Printf("DockerStat Failed: %s\n", err.Error())
	} else {
		fmt.Printf("Docker Stat List\n")
		for i := range ds {
			fmt.Printf("%s\n", ds[i].String())
		}
	}
```

The compilation fails in OSX, with the message
```
ds[i].String undefined (type docker.CgroupDockerStat has no field or method String)
```

Could you please add

```
func (c CgroupDockerStat) String() string {
	s, _ := json.Marshal(c)
	return string(s)
}
```
also to `docker_notlinux.go` file.

**Comment by shirou** [comment]
I moved `String()` to `docker.go` which used on all platforms at 231815dfeab1ddac1419fcaf564eea078fdf9bfc. Perhaps it fan fix your problem.

I close this issue. But feel free to reopen if you still have problem. Thank you!
