### ISSUE TITLE
[net] Unexpected traffic rise (packets / bytes)

### ISSUE THREAD

**Issue by tonobo** [shirou/gopsutil#489]
I do something like that:

```go
	nic_name := fmt.Sprintf("virt%d-nic", d.ID)
	iocounters, err := net.IOCounters(true)
	if err != nil {
		d.ErrorL(err, "Fetching interface stats failed.")
		return nil
	}
	for _, iocounter := range iocounters {
		if iocounter.Name == nic_name {
			return &Networkstat{
				ReceivedBytes:      iocounter.BytesRecv,
				TransmittedBytes:   iocounter.BytesSent,
				ReceivedPackets:    iocounter.PacketsRecv,
				TransmittedPackets: iocounter.PacketsSent,
			}
		}
	}
	return nil
```

and sometimes there are invalid values are parsed. 
Please take a look at the following traffic bump.

![image](https://user-images.githubusercontent.com/6775896/36342369-e661fd82-13fd-11e8-9f3f-e2e187f706fd.png)

**Comment by shirou** [comment]
What is your environment? os, distribution and arch.

**Comment by tonobo** [comment]
Hi, the codes runs on ubuntu, amd64. I'm not sure how this can happen, your code just reads a single file exposed from netlink. All seems legit :/

**Comment by shirou** [comment]
I created sample code and check for 30min (ubuntu 16.04 amd64), but there is no such a gap.

https://gist.github.com/shirou/97cdcb2175215d64751490532d8e3299

![image](https://user-images.githubusercontent.com/177213/37250001-e11d2326-2535-11e8-8cd8-27a3be62ebde.png)

I close this issue. If you find some more information, feel free to re-open. Thank you.
