### ISSUE TITLE
fillFromStat causes significant CPU usage.

### ISSUE THREAD

**Issue by maihde** [shirou/gopsutil#492]
While using Nomad I observed that CPU usage to monitor processes was significant in certain situations.  Using this [application](https://gist.github.com/maihde/30cacbc40003f6c59f625e6c0f901cb3) I profiled the calls to `process.Times()` and determined that a significant amount of the CPU usage was due to the calls by `getTerminalMap()` within the `fillFromStat()` method.  Given that the `terminal` return value is usually thrown away it's better if `getTerminalMap()` is only called within the `process.Terminal()` method itself. 

See this [Nomad PR](https://github.com/hashicorp/nomad/pull/3883) for resolution and this [Nomad Issue](https://github.com/hashicorp/nomad/issues/3881) for more details.

**Comment by shirou** [comment]
Thank you for reporting. I agree with your [PR on Nomad](https://github.com/hashicorp/nomad/pull/3883/files) . Could you make a PR to this repository? Thank you!
