### ISSUE TITLE
Request connection info on windows

### ISSUE THREAD

**Issue by 5A4B48** [shirou/gopsutil#495]
I'm currently writing a tool that will require gathering connection info based on pids. This may be a bit beyond what I'm capable of doing but if you point me in the right direction I sure will give it a try.

**Comment by pytimer** [comment]
windows netstat? I write a tool that get windows netstat by process pid, like it?
https://github.com/pytimer/win-netstat

**Comment by Lomanic** [comment]
No news from issue reporter and might be now implemented in gopsutil thanks to #549.
