### ISSUE TITLE
process.ErrorNoChildren is only defined for linux

### ISSUE THREAD

**Issue by aajtodd** [shirou/gopsutil#500]
On Windows this fails to compile

```go
children, err := myprocess.Children()
if err != nil && err != process.ErrorNoChildren {
    ...
}
```

Looks like it's defined in https://github.com/shirou/gopsutil/blob/master/process/process_linux.go#L27

Should probably be in the root `process.go` file. Also windows implementation should probably return this error when there are no children.

**Comment by shirou** [comment]
Sorry for late response and good catch! I have moved it to platform independent part on 26a4a2f995ce72e0f735d539fb767291a71f04af .
