### ISSUE TITLE
Compilation failure on 32bit OSX

### ISSUE THREAD

**Issue by cjbassi** [shirou/gopsutil#505]
Hi, I'm getting a bunch of undefined errors when trying to cross compile for 32bit OSX:
```
vendor/github.com/shirou/gopsutil/disk/disk_darwin.go:21:31: undefined: MntWait
vendor/github.com/shirou/gopsutil/disk/disk_darwin.go:25:15: undefined: Statfs_t
vendor/github.com/shirou/gopsutil/disk/disk_darwin.go:26:25: undefined: MntWait
vendor/github.com/shirou/gopsutil/disk/disk_darwin.go:29:17: undefined: MntReadOnly
vendor/github.com/shirou/gopsutil/disk/disk_darwin.go:32:17: undefined: MntSynchronous
vendor/github.com/shirou/gopsutil/disk/disk_darwin.go:35:17: undefined: MntNoExec
vendor/github.com/shirou/gopsutil/disk/disk_darwin.go:38:17: undefined: MntNoSuid
vendor/github.com/shirou/gopsutil/disk/disk_darwin.go:41:17: undefined: MntUnion
vendor/github.com/shirou/gopsutil/disk/disk_darwin.go:95:22: undefined: Statfs_t
vendor/github.com/shirou/gopsutil/disk/disk_darwin.go:99:54: undefined: Statfs_t
vendor/github.com/shirou/gopsutil/disk/disk_darwin.go:41:17: too many errors
```
Been working fine for 32/64 bit linux and 64 bit OSX.
It seems to be caused by a lack of `disk_darwin_386.go` file. Looks like we just need to make one?

**Comment by Lomanic** [comment]
You can try copying `disk/disk_darwin_amd64.go` to `disk/disk_darwin_386.go` and changing the second line of this new file from `// +build amd64` to `// +build 386`to make the build succeed. I don't have a 32bit darwin machine anymore to test (or even a darwin 64bit), can you test your 32bit darwin build properly runs, either on a 32bit or 64bit host?

**Comment by cjbassi** [comment]
Doing what you said fixed the build errors, but I'm not sure whether the build actually works correctly since I don't have a 32bit darwin machine available to test it, although I might at some point.

**Comment by shirou** [comment]
I checked https://github.com/golang/go/blob/master/src/syscall/ztypes_darwin_386.go#L82 and `Statfs_t` is same as amd64. So I created `disk_darwin_386.go` on 837fc76f6885d42127f79a0e974eb17ae3cb0a6e. It could fix this problem. If not, please re-open this issue.

Note: I have changed the struct name to `Statfs` in darwin. it affects`Getfsstat()`. This change breaks API compatibility, but it had been broken compatibility between freebsd, openbsd, and darwin. So I change to same name.
