### ISSUE TITLE
Redhat Machines Returns Error in searching the /proc files

### ISSUE THREAD

**Issue by kgrvamsi** [shirou/gopsutil#51]
Problem

        [root@compute ~]# ./testing
	-1 open /proc/917/stat: no such file or directory
 	<nil>
 	readlink /proc/917/exe: no such file or directory
	0 open /proc/917/stat: no such file or directory
 	readlink /proc/917/cwd: no such file or directory
	<nil> not implemented yet
 	<nil>
 	open /proc/917/stat: no such file or directory
	<nil> <nil>
	<nil> open /proc/917/statm: no such file or directory
	true not implemented yet
	{"hostname":"compute","uptime":1435308047,"procs":0,"os":"linux","platform":"redhat","platform_family":"rhel","platform_version":"7.1","virtualization_system":"","virtualization_role":""}
	1435308047
	[{"user":"reboot","terminal":"~","host":"3.10.0-229.el7.x86_64","started":1435308054} {"user":"LOGIN","terminal":"tty1","host":"","started":1435308063} {"user":"runlevel","terminal":"~","host":"3.10.0-229.el7.x86_64","started":1435308066} {"user":"root","terminal":"pts/0","host":"115.249.70.178","started":1435309212} {"user":"root","terminal":"pts/1","host":"115.249.70.178","started":1435312674}]
	redhat rhel 7.1 <nil>
  	<nil>

Code for this

    package main
 
    import (
	"fmt"
	"github.com/shirou/gopsutil/host"
	"github.com/shirou/gopsutil/process"
	_ "time"
    )

    func Testing() {
	h, _ := host.HostInfo()
	b, _ := host.BootTime()
	v, _ := process.NewProcess(917)
	u, _ := host.Users()

	fmt.Println(v.Ppid())
	fmt.Println(v.Name())
	fmt.Println(v.Exe())
	fmt.Println(v.CreateTime())
	fmt.Println(v.Cwd())
	fmt.Println(v.Parent())
	fmt.Println(v.Status())
	fmt.Println(v.Terminal())
	fmt.Println(v.MemoryInfo())
	fmt.Println(v.MemoryInfoEx())
	fmt.Println(v.IsRunning())
	fmt.Println(h)
	fmt.Println(b)
	fmt.Println(u)
	fmt.Println(host.GetPlatformInformation())
	fmt.Println(host.GetVirtualization())
    }

    func main() {
	Testing()
    }

**Comment by shirou** [comment]
Great report!
Unfortunately, I have no rhel machine and knowledge. The rhel 7.1 doesn't have process information in the proc filesystem? Could you show me some reference about proc filesystem in rhel7 if you know.

Thanks

**Comment by kgrvamsi** [comment]
Sure will check if i can get some info on this @shirou

**Comment by shirou** [comment]
Thanks for the AWS, I run your code with replaced 917 to other process id.

Then get this result.

```
[ec2-user@ip-172-30-0-60 ~]$ go run main.go 
10683 <nil>
bash <nil>
/usr/bin/bash <nil>
1435408445 <nil>
/home/ec2-user <nil>
<nil> not implemented yet
sleeping <nil>
/pts/0 <nil>
{"rss":2134016,"vms":118120448,"swap":0} <nil>
{"rss":2134016,"vms":118120448,"shared":1699840,"text":905216,"lib":0,"data":0,"dirty":491520} <nil>
true not implemented yet
{"hostname":"ip-172-30-0-60.ec2.internal","uptime":1435408350,"procs":0,"os":"linux","platform":"redhat","platform_family":"rhel","platform_version":"7.1","virtualization_system":"xen","virtualization_role":"guest"}
1435408350
[{"user":"reboot","terminal":"~","host":"3.10.0-229.el7.x86_64","started":1435408355} {"user":"LOGIN","terminal":"ttyS0","host":"","started":1435408368} {"user":"LOGIN","terminal":"hvc0","host":"","started":1435408368} {"user":"LOGIN","terminal":"tty1","host":"","started":1435408368} {"user":"runlevel","terminal":"~","host":"3.10.0-229.el7.x86_64","started":1435408398} {"user":"ec2-user","terminal":"pts/0","host":"h101-111-210-221.catv02.itscom.jp","started":1435408445}]
redhat rhel 7.1 <nil>
xen guest <nil>
```

I think it looks like gopsutil/process works. Could you tell me the difference between us? or, How about using process id 1(systemd) instead 917 in your code?

Thank you!

**Comment by kgrvamsi** [comment]
Aww,Wrong Code i'm really sorry for this and i have checked the code again and seems its working fine now and i just have copied the binary from one server to another and obviously the PID's wont be same so i go this error.

Thanks and will keep a eye on this
