### ISSUE TITLE
cpu.Percent returns empty slice on 64bit Darwin

### ISSUE THREAD

**Issue by cjbassi** [shirou/gopsutil#510]
Some OSX users are having an issue with a project of mine [here](https://github.com/cjbassi/gotop/issues/16) and [here](https://github.com/cjbassi/gotop/issues/9) due to cpu.Percent(time.Second, true) returning an empty slice. Relevant code [here](https://github.com/cjbassi/gotop/blob/08e981218d8efd83d515ba482e6b2e7934b84f46/widgets/cpu.go#L52)

**Comment by cjbassi** [comment]
It turns out the issue goes away when they build the binary themselves instead of downloading a prebuild binary that I've crosscompiled on linux.

**Comment by shirou** [comment]
Getting CPU on darwin requires cgo. So you need real darwin machine to build binary.

**Comment by cjbassi** [comment]
Thanks for the info. Doesn't the readme say that cgo isn't used tho? Should that be changed?

**Comment by Lomanic** [comment]
Indeed, gopsutil aims to be pure go and not to rely on cgo, darwin is the only exception currently. I don't have a Mac OS computer anymore unfortunately (same as shirou too as reported in https://github.com/shirou/gopsutil/issues/513#issuecomment-381453703) to try implementing with syscalls.

**Comment by cjbassi** [comment]
Can we update the README about cgo then? Currently it says cgo is not used, but I think it would be good to say that it's used for Darwin currently.
