### ISSUE TITLE
How to list processes?

### ISSUE THREAD

**Issue by ericrange** [shirou/gopsutil#514]
Everywhere i see:
process.Processes()

but this function does not exists (anymore?)

Is this right?

**Comment by dfilion** [comment]
You don't mention the OS, but it certainly exists for Linux. Take a look at [https://github.com/shirou/gopsutil/blob/master/process/process_linux.go#L1211](https://github.com/shirou/gopsutil/blob/master/process/process_linux.go#L1211).

**Comment by shirou** [comment]
@dfilion thanks

and also [godoc](https://godoc.org/github.com/shirou/gopsutil/process) will help.
