### ISSUE TITLE
gopsutil contains some GPL-licensed code

### ISSUE THREAD

**Issue by mrostecki** [shirou/gopsutil#518]
gopsutil is licensed under BSD 3-clause license https://github.com/shirou/gopsutil/blob/master/LICENSE

However, its code contains two files which are licensed under GPL and are most probably just copied from some project:

https://github.com/shirou/gopsutil/blob/master/host/include/smc.c#L1-L35
https://github.com/shirou/gopsutil/blob/master/host/include/smc.h#L1-L35

Can somebody explain how that code was introduced there? I think that we should get rid of it and (if possible) use something released under BSD/MIT/Apache or anything other license with is compatible with BSD.

I discovered that issue when I tried to package https://github.com/google/gops in openSUSE and our infra detected that there is some GPL-licensed code, despite the fact, that the whole project is licensed under more "liberal" licenses.

/cc @shirou

**Comment by mrostecki** [comment]
The only source file which actually uses the GPL-licensed content:

https://github.com/shirou/gopsutil/blob/master/host/host_darwin_cgo.go

**Comment by shirou** [comment]
I am really apologize about include GPL files. These files are introduced by #344 and I have not notice those are under GPL.

I removed those on c95755e4bcd7a62bb8bd33f3a597a7c7f35e2cf3 and released  `v2.18.04`. (usually release is end of month, but this problem is emergency)

**Comment by mrostecki** [comment]
Thanks a lot!
