### ISSUE TITLE
Windows services 

### ISSUE THREAD

**Issue by pytimer** [shirou/gopsutil#524]
Hi,
I already use gopsutil to gather vm metrics, such as memory and cpu. But now want to get windows services, but gopsutl currently not supported. I see https://github.com/giampaolo/psutil already support windows services. Whether consider this feature to the project?

**Comment by shirou** [comment]
Interesting. But I don't have a time to do, currently. PR is always welcome!

**Comment by pytimer** [comment]
Thanks for your reply. I don't know about more windows, but i will try to implement it.

**Comment by pytimer** [comment]
@shirou 
I have implement about windows service package,  i hope you can check it if you have free.thanks

**Comment by pytimer** [comment]
Hi, @shirou ,Thank you for merge this PR. :-) 

I think this issue can close.

**Comment by shirou** [comment]
Thank you for your great contribution!
