### ISSUE TITLE
swap memory percent get NAN when swap memory total is zero

### ISSUE THREAD

**Issue by geekerlw** [shirou/gopsutil#525]
``` go
func SwapMemoryWithContext(ctx context.Context) (*SwapMemoryStat, error) {
	var perfInfo performanceInformation
	perfInfo.cb = uint32(unsafe.Sizeof(perfInfo))
	mem, _, _ := procGetPerformanceInfo.Call(uintptr(unsafe.Pointer(&perfInfo)), uintptr(perfInfo.cb))
	if mem == 0 {
		return nil, windows.GetLastError()
	}
	tot := perfInfo.commitLimit * perfInfo.pageSize
	used := perfInfo.commitTotal * perfInfo.pageSize
	free := tot - used
	ret := &SwapMemoryStat{
		Total:       tot,
		Used:        used,
		Free:        free,
		UsedPercent: float64(used) / float64(tot),
	}

	return ret, nil
}
```

My windows machine has no swap memory configured, so get a swap memory total is zero, which make the `UsedPercent: 0/0`, final get a NAN out of the function.

I don't known why the `procGetPerformanceInfo`  function not return an error or mem is not none.

**Comment by shirou** [comment]
Thank you report! I added a check on 0f1576d63c939651ce16e972dc444a2f7017a34d, please check it again? Thanks!

**Comment by geekerlw** [comment]
I think the total and used swap memory maybe current to 0, just set usedPercent to 0 when the total is zero is enough.
I add a judgement in my program,an it’s fixed, but the commit will make me lose the total and others.

**Comment by shirou** [comment]
So, you mean #526? it return empty if total or used is 0.

**Comment by geekerlw** [comment]
I create a pull request at #527
