### ISSUE TITLE
Windows Process Net Connection support

### ISSUE THREAD

**Issue by wkleinhenz** [shirou/gopsutil#531]
Currently im working on converting some python code to Go. The code heavily uses psutil and is mainly windows focused. i am fairly new to Go but would be willing to help add process individual network connections and other windows functionality to this project.

I was wondering if any work has been started and if you could point me in the direction of some information to get me started

Thanks

**Comment by pytimer** [comment]
Hi @wkleinhenz 

I write [win-netstat](https://github.com/pytimer/win-netstat) to get windows process connections, similar `gopsutil` linux net package, you can read. If it is helpful to you, you can reference to it. Or you can tell me, and i will submit PR to `gopsutil` implements it.

**Comment by Lomanic** [comment]
Implemented in #549
