### ISSUE TITLE
Build on MIPS platform fails in disk_linux.go

### ISSUE THREAD

**Issue by maddie** [shirou/gopsutil#533]
The error is as below:

```
/go/src/github.com/shirou/gopsutil/disk/disk_linux.go:394:26: cannot use stat.Rdev (type uint32) as type uint64 in argument to unix.Major
/go/src/github.com/shirou/gopsutil/disk/disk_linux.go:395:26: cannot use stat.Rdev (type uint32) as type uint64 in argument to unix.Minor
```

It seems these are introduced in commit f03124bf

**Comment by maddie** [comment]
Is it possible to just cast `stat.Rdev` as `uint64`?

**Comment by shirou** [comment]
#535 can fix?

**Comment by jsoriano** [comment]
Oh sorry, I didn't see this issue, @shirou's PR lgtm.

**Comment by maddie** [comment]
This would at least let the build pass. I'm not sure if it's right way though, I guess we'll see.

Thanks!

**Comment by maddie** [comment]
I think it works, please merge the PR.

Thanks!

**Comment by shirou** [comment]
merged. Thank you for your report!
