### ISSUE TITLE
Please allow specifying of wtmp file in host.Users()

### ISSUE THREAD

**Issue by scudette** [shirou/gopsutil#536]
Currently the utmp file is hard coded here:
https://github.com/shirou/gopsutil/blob/master/host/host_linux.go#L182

I would like to be able to specify the path and in particular specify wtmp file so I can see the historic logins.

**Comment by Lomanic** [comment]
First, Python psutil does not support this option, then it's a Linux-only issue so we can't add this option in the function definition as it only makes sense on Linux. Maybe we could create a new function `HistoricUsers` (`PreviousUsers`?), but then we would have to implement this on all the other platforms…
This might be an issue to be resolved in another package downstream (there is [github.com/neko-neko/utmpdump](https://github.com/neko-neko/utmpdump) with a [Read function](https://godoc.org/github.com/neko-neko/utmpdump/utmp#Read) taking a *io.Reader as input, liberal MIT licence, in pure Go).

**Comment by shirou** [comment]
or you can copy any other place and set `HOST_VAR` environment variable.

**Comment by scudette** [comment]
Thanks - you are right this goes beyond the functionality offered by gopsutil.
