### ISSUE TITLE
add additional meminfo fields for linux virtual memory stat

### ISSUE THREAD

**Issue by shrug42** [shirou/gopsutil#539]
PR: https://github.com/shirou/gopsutil/pull/538

We use gopsutil for a plugin to report memory metrics in telegraf (https://github.com/influxdata/telegraf)

In my project, I need additional fields to be reported by telegraf, thus this PR.
Let me know what you think about it.
Cheers.

**Comment by Lomanic** [comment]
#538 was merged, thank you for your contribution.
