### ISSUE TITLE
TestVirtualization: fails in machines not having virtualization support (?)

### ISSUE THREAD

**Issue by onlyjob** [shirou/gopsutil#547]
As reported in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902563
`TestVirtualization` seems to fail in machines without virtualization support:

~~~~
--- FAIL: TestVirtualization (0.00s)
        host_test.go:137: Virtualization() retuns empty system or role:  , 
        host_test.go:140: Virtualization(): , 
~~~~

**Comment by shirou** [comment]
Thank you for your report! That empty check confirms there is an return value. But as you suggested, if a machine does not support virtualization, it failed. And we already has `err` check, so I have removed that check on 4923bd298a8342a588f2118587b7f7d668868a42
