### ISSUE TITLE
cpu.Percent on Windows shows incorrect number of cores

### ISSUE THREAD

**Issue by peterfraedrich** [shirou/gopsutil#551]
When running a Windows VM and inspecting the CPU with `gopsutil`, the `cpu` module returns incorrect and inconsistent core information.

`cpu.Percent()` shows 6 cores, which is the number of the virtualization host
```go
package main

import (
	"encoding/json"
	"fmt"
	"time"
	"github.com/shirou/gopsutil/cpu"
)

func main() {
	i, _ := time.ParseDuration("1s")
	v, _ := cpu.Percent(i, true)
	j, _ := json.MarshalIndent(v, "", "    ")
	fmt.Println(string(j))
}
```
output =>
```
[
    0,
    0,
    0,
    0,
    0,
    0
]
```
`cpu.Info()` shows 4 cores, the number exposed to the VM
```go
package main

import (
	"encoding/json"
	"fmt"

	"github.com/shirou/gopsutil/cpu"
)

func main() {
	v, _ := cpu.Info()
	j, _ := json.MarshalIndent(v, "", "    ")
	fmt.Println(string(j))
}
```
output =>
```
[
    {
        "cpu": 0,
        "vendorId": "AuthenticAMD",
        "family": "2",
        "model": "",
        "stepping": 0,
        "physicalId": "178BFBFF00600F20",
        "coreId": "",
        "cores": 4,
        "modelName": "AMD FX(tm)-6300 Six-Core Processor             ",
        "mhz": 3516,
        "cacheSize": 0,
        "flags": [],
        "microcode": ""
    }
]
```

**Comment by Lomanic** [comment]
Thanks for this detailed report, are you using VMware, HyperV, VirtualBox ?

**Comment by peterfraedrich** [comment]
VMWare Workstation 12 on Windows 7 Ultimate 64 bit


On Jul 9, 2018, at 5:12 PM, Lomanic <notifications@github.com> wrote:

Thanks for this detailed report, are you using VMware, HyperV, VirtualBox ?

**Comment by shirou** [comment]
I confirmed [Win32_PerfFormattedData_Counters_ProcessorInformation](https://github.com/shirou/gopsutil/blob/master/cpu/cpu_windows.go#L127) returns 6 length structs, but [Win32_Processor](https://github.com/shirou/gopsutil/blob/master/cpu/cpu_windows.go#L91) return 1 with 4 cores, on my Windows10 native. But I don't know why.

**Comment by Lomanic** [comment]
Still investigating how to get rid of these unreliable wmi calls, but it's cpu.Percent that returns a wrong number of cores, not cpu.Info, as found in the registry and via Get(Native)SystemInfo.

**Comment by Lomanic** [comment]
Indeed you are right, I will try this weekend to filter out the totals in the wmi query as in [this SO answer](https://stackoverflow.com/a/11325409). Thanks for the heads up. 👍

**Comment by Lomanic** [comment]
Here is the diff, implementing the filtering in the wmi call
<details>
  <summary>Click to expand</summary>
  ```diff
diff --git a/cpu/cpu_windows.go b/cpu/cpu_windows.go
index 8aa691c..f8a89ca 100644
--- a/cpu/cpu_windows.go
+++ b/cpu/cpu_windows.go
@@ -126,7 +126,7 @@ func PerfInfo() ([]Win32_PerfFormattedData_Counters_ProcessorInformation, error)
 func PerfInfoWithContext(ctx context.Context) ([]Win32_PerfFormattedData_Counters_ProcessorInformation, error) {
        var ret []Win32_PerfFormattedData_Counters_ProcessorInformation

-       q := wmi.CreateQuery(&ret, "")
+       q := wmi.CreateQuery(&ret, "WHERE NOT Name LIKE '%_Total'")
        err := common.WMIQueryWithContext(ctx, q, &ret)
        if err != nil {
                return []Win32_PerfFormattedData_Counters_ProcessorInformation{}, err
```
</details>

This is functional but the problem is it modifies the exported function PerfInfoWithContext, which should never have been exported  in the first place, would you be OK @shirou to unexport PerfInfo(WithContext) while fixing this issue?
