### ISSUE TITLE
net.IOCountersWithContext() returning inconsistent received data volume over time

### ISSUE THREAD

**Issue by 32782770** [shirou/gopsutil#554]
你好，我在使用IOCountersWithContext函数取网卡流量时row.InOctets 这个值应该是一直累加的，为什么会突然断掉然后在累加呢 ？
![image](https://user-images.githubusercontent.com/20390401/42679967-39376260-86b6-11e8-9ab3-6d833cd974d0.png)

**Comment by Lomanic** [comment]
Automatic translation

> Hello, when I use the IOCountersWithContext function to take the network card traffic, the value of row.InOctets should be accumulated all the time. Why is it suddenly broken and then accumulated?

Please write in English (even use automatic translation so your readers don't have to).

Give us more information (OS version, sample code, some context) so we might try to reproduce the issue to fix it.

**Comment by Lomanic** [comment]
Closing in favour of #693 that has more details.
