### ISSUE TITLE
common.StringContains() is exactly equal compare, but used for "contains".

### ISSUE THREAD

**Issue by gwind** [shirou/gopsutil#56]
For example: https://github.com/shirou/gopsutil/blob/master/host/host_linux.go#L340

In Linux:

    $ grep kvm /proc/modules
    kvm_intel 143109 6 - Live 0x0000000000000000
    kvm 451552 1 kvm_intel, Live 0x0000000000000000

in the following code to test contains would be fail:

    contents, err := common.ReadLines("/proc/modules")
    common.StringContains(contents, "kvm")

The common.StringContains() is : 

    // Check the target string slice containes src or not
    func StringContains(target []string, src string) bool {
    	for _, t := range target {
    		if strings.TrimSpace(t) == src {
    			return true
    		}
    	}
    	return false
    }

This is a common func in gopsutil, but it has a confused name. "String" can not display a "string list" mean, and "Contains" can not display a "contain this sub str" mean.

**Comment by shirou** [comment]
Hmm, I am not so good at English. Could you tell me what kind of Function name is better for the purpose?

**Comment by gwind** [comment]
You are too modest. :-)

a poor example:

    package main
    
    import (
    	"fmt"
    	"strings"
    )
    
    // Check the target string slice containes src or not
    func StringsHas(target []string, src string) bool {
    	for _, t := range target {
    		if strings.TrimSpace(t) == src {
    			return true
    		}
    	}
    	return false
    }
    
    // Does src in any string of the target string slice
    func StringsFind(target []string, src string) bool {
    	for _, t := range target {
    		if strings.Index(t, src) >= 0 {
    			return true
    		}
    	}
    	return false
    }
    
    func main() {
    	v := []string{
    		"hello, c",
    		"hello, unix",
    		"hello, gnu",
    		"hello, linux",
    		"hello, go",
    	}
    
    	test_data := []string{
    		"hello, c",
    		"unix",
    		"Java",
    	}
    	for _, s := range test_data {
    		fmt.Printf("StringsHas(\"%s\", v) = %t\n", s, StringsHas(v, s))
    		fmt.Printf("StringsFind(\"%s\", v) = %t\n", s, StringsFind(v, s))
    	}
    }

**Comment by shirou** [comment]
Thank you for the suggestion!

golang has the method called [strings.Contains](http://golang.org/pkg/strings/#Contains) to check strings has the substr or not.

If I change your `StringsFind` to use `strings.Contains`,  changing the name to `StringsContains`  is acceptable? 

Sorry for annoying you. But I can not understand well such a nuances. Really.

**Comment by gwind** [comment]
Yes, it's good. I'm miss the  strings.Contains .

**Comment by shirou** [comment]
I commit the change at b5ffc220a671e8ed5eb2c0136b24524f708ea361. If I have miss understanding, please re-open this issue.

I am very appriciate to have discussion with you. Thank you.

**Comment by gwind** [comment]
It's a nice job, thanks for your share.
