### ISSUE TITLE
UsageStats.UsedPercent is different than df command output Use%

### ISSUE THREAD

**Issue by tomekkolo** [shirou/gopsutil#562]
https://github.com/shirou/gopsutil/blob/d9d9688f3d20a6b7942c5222607c29b32b69d15e/disk/disk_unix.go#L53

Current way how UsageStats.UsedPercent is calculated differs from what df command does. UsedPercent in gopsutil is calculated as (used/total)*100, while in df command it is (used/(used+available))*100. 

UsageStats.Free is set as Bavail, and to be consistent UsageStats.UsedPercent should be calculated for available memory.

**Comment by Lomanic** [comment]
We don't care especially about `df` but it's the same formula in python's psutil, so we will calculate this way to be consistent with the original. Thanks for the report @tomekkolo :+1:

**Comment by tomekkolo** [comment]
I've created pull request to address this: https://github.com/shirou/gopsutil/pull/563

**Comment by shirou** [comment]
#563 was merged. Thank you for your report!
