### ISSUE TITLE
cpu.Percent() returns empty on EPYC/ZEN processor

### ISSUE THREAD

**Issue by cjbassi** [shirou/gopsutil#568]
cjbassi/gotop#34

**Comment by Lomanic** [comment]
`cpu.Percent` gets its data from `/proc/stat` ([via](https://github.com/shirou/gopsutil/blob/3ec50d2876a36047b2ca39f955ba88fb7a455e92/cpu/cpu.go#L153) [cpu.Times()](https://github.com/shirou/gopsutil/blob/3ec50d2876a36047b2ca39f955ba88fb7a455e92/cpu/cpu_linux.go#L38)), can @abucodonosor paste its content here? Thanks in advance.

**Comment by abucodonosor** [comment]
@Lomanic 

paste in here would look somewhat strange :)

There a file with the output  :
https://crazy.dev.frugalware.org/stat-2-EPYC-7281-16-Core-Processor.txt

**Comment by Lomanic** [comment]
Thanks for the file @abucodonosor, I investigated but I could not find anything special in it, can you tell me the result of the following maybe?

```go
package main

import (
	"fmt"
	"os/exec"
	"time"

	"github.com/shirou/gopsutil/cpu"
)

func main() {
	cmd := exec.Command("sh", "-c", "while true; do true; done")
	cmd.Start()

	fmt.Println("cpu.Percent(false)")
	percent, err := cpu.Percent(time.Second, false)
	if err != nil {
		fmt.Println(err)
		return
	}
	for _, p := range percent {
		fmt.Println(p)
	}

	fmt.Println("cpu.Percent(true)")
	percent, err = cpu.Percent(time.Second, true)
	if err != nil {
		fmt.Println(err)
		return
	}
	for _, p := range percent {
		fmt.Println(p)
	}
	fmt.Println("len", len(percent))
	cmd.Process.Kill()
}
```

There should be one core reported at 100% (or almost) usage.

**Comment by abucodonosor** [comment]
sure , here it is:

```
$ ./cpu
cpu.Percent(false)
1.6081186574174324
cpu.Percent(true)
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0.99009901009357
0
0
99.99999999909951
0
0
0
0
0
0
0
0
0
0.99009901009357
0
0
0
0
0
0
0
0
0
0
0
0
len 64

```

**Comment by cjbassi** [comment]
Seems like things are working here and also on my end too so I think we can close this. I'm not sure what changed, or if we/I just overlooked something, but thanks for the help @Lomanic. I'll also make sure to investigate issues more thoroughly in the future too.

**Comment by Lomanic** [comment]
No problem @cjbassi, glad I could help.
