### ISSUE TITLE
Linux kernel 4.19 has changed /proc/diskstats

### ISSUE THREAD

**Issue by lpic10** [shirou/gopsutil#571]
New fields have been added to /proc/diskstats with this [commit](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=bdca3c87fb7ad1cc61d231d37eb0d8f90d001e0c), not sure that breaks something but it will be interesting to add them.

**Comment by shirou** [comment]
Thank you for your information! I think this commit just add these values, it may not break compatibility.

```
+		15 - discards completed successfully
+		16 - discards merged
+		17 - sectors discarded
+		18 - time spent discarding
```

Since it takes a time until 4.19 released and widely used, so I have close this PR currently. But this issue is very useful for our future. Thank you!
