### ISSUE TITLE
[process] get invalid pid by Processes in darwin_amd64

### ISSUE THREAD

**Issue by lrita** [shirou/gopsutil#573]
When I run code:
```
	all, err := process.Processes()
	if err != nil {
		panic(err)
	}
	for _, p := range all {
		fmt.Println("pid", p.Pid)
	}
```
It will show some invalid pid, such as
```
pid 1531858944
```

using gopsutil:  [ef54649](https://github.com/shirou/gopsutil/commit/ef54649286408053c0620d366dc06ead7d7cae5a)

**Comment by Lomanic** [comment]
Is it reproducible? Do you have the same issue with `process.Pids()`?

What's the result of the following?

```go
package main

import (
	"fmt"

	"github.com/shirou/gopsutil/process"
)

func main() {
	fmt.Println("##### process.Processes() #####")
	procs, err := process.Processes()
	if err != nil {
		panic(err)
	}
	for _, p := range procs {
		fmt.Println(p.Pid)
	}
	fmt.Println("##### process.Pids() #####")
	pids, err := process.Pids()
	if err != nil {
		panic(err)
	}
	for _, p := range pids {
		fmt.Println(p)
	}
}

```

process.Pids() simply uses the ps command to get its results and might be more reliable than using syscall+k_info in process.Processes() while we try to fix this.

**Comment by lrita** [comment]
Hi @Lomanic ,

`process.Pids()` works fine. The result of the gist you given is [gopsutil_issue_573.txt](https://lrita.github.io/images/posts/issue/gopsutil_issue_573.txt)

When I modify it to:
```
package main

import (
	"fmt"

	"github.com/shirou/gopsutil/process"
)

func main() {
	pids, err := process.Pids()
	if err != nil {
		panic(err)
	}
	for _, p := range pids {
		fmt.Println(p)
	}
}
```

and run `go run test.go |xargs ps -p`, shell works fine.

Thanks.

**Comment by Lomanic** [comment]
Darwin's process.Processes() originates from a199f2d8544fd955d87326758c7cf6ad8d738407, do you have an idea about this issue @shirou?

**Comment by shirou** [comment]
I forget about it but I was trying to get Proceses from `KinfoProc` but it was not successed. I think we should change to use `Pid()`, same as linux.
