### ISSUE TITLE
Darwin (MacOs) - host.KernelVersion() returns OS version not Kernel version

### ISSUE THREAD

**Issue by Setheck** [shirou/gopsutil#574]
This starts out as a question as I'm wondering if it's by design since Apple doesn't always follow convention. But maybe it's a bug?

On a vm of RHEL calling host.KernelVersion() appropriately returns 
`3.10.0-862.el7.x86_64` which matches the response from `$ uname -r`

However, on MacOs the returned string is
`10.13.6` however, 
`$ uname -r` returns `17.7.0`
`$ uname -a` returns 
`Darwin localhost 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64`

I would have expected `17.7.0` as the appropriate Darwin Kernel Version.

**Comment by Lomanic** [comment]
Currently `host.KernelVersion()` uses `sw_vers -productVersion` on darwin (PlatformInformation version), you can get the proper value with the following until we fix this issue 

```go
info, _ := host.Info()
fmt.Println(info.KernelVersion)
```
