### ISSUE TITLE
Error while running command go get -u github.com/shirou/gopsutil/...

### ISSUE THREAD

**Issue by subbu05** [shirou/gopsutil#578]
go get -u github.com/shirou/gopsutil/...
# cd /Users/sumalepa/go/src/github.com/shirou/gopsutil; git pull --ff-only
error: Your local changes to the following files would be overwritten by merge:
	Makefile
	README.rst
	cpu/cpu.go
	cpu/cpu_darwin.go
	cpu/cpu_fallback.go
	cpu/cpu_freebsd.go
	cpu/cpu_linux.go
	cpu/cpu_openbsd.go
	cpu/cpu_solaris.go
	cpu/cpu_solaris_test.go
	cpu/cpu_windows.go
	disk/disk.go
	disk/disk_darwin.go
	disk/disk_darwin_amd64.go
	disk/disk_darwin_arm64.go
	disk/disk_darwin_cgo.go
	disk/disk_darwin_nocgo.go
	disk/disk_fallback.go
	disk/disk_freebsd.go
	disk/disk_linux.go
	disk/disk_openbsd.go
	disk/disk_test.go
	disk/disk_unix.go
	disk/disk_windows.go
	docker/docker.go
	docker/docker_linux.go
	docker/docker_notlinux.go
	host/host.go
	host/host_darwin.go
	host/host_fallback.go
	host/host_freebsd.go
	host/host_linux.go
	host/host_openbsd.go
	host/host_solaris.go
	host/host_test.go
	host/host_windows.go
	internal/common/common.go
	internal/common/common_darwin.go
	internal/common/common_test.go
	internal/common/common_unix.go
	internal/common/common_windows.go
	load/load.go
	load/load_darwin.go
	load/load_fallback.go
	load/load_linux.go
	load/load_test.go
	load/load_windows.go
	mem/mem.go
	mem/mem_darwin.go
	mem/mem_darwin_cgo.go
	mem/mem_darwin_nocgo.go
	mem/mem_fallback.go
	mem/mem_freebsd.go
	mem/mem_linux.go
	mem/mem_openbsd.go
	mem/mem_solaris.go
	mem/mem_test.go
	mem/mem_windows.go
	net/net.go
	net/net_darwin.go
	net/net_fallback.go
	net/net_freebsd.go
	net/net_linux.go
	net/net_openbsd.go
	net/net_test.go
	net/net_unix.go
	net/net_windows.go
	process/process.go
	process/process_darwin.go
	process/process_fallback.go
	process/process_freebsd.go
	process/process_linux.go
	process/process_openbsd.go
	process/process_posix.go
	process/process_test.go
	process/process_windows.go
Please commit your changes or stash them before you merge.
Aborting
package github.com/shirou/gopsutil/...: exit status 1

**Comment by Lomanic** [comment]
Looks like you modified locally gopsutil and that `git pull` will overwrite your changes. Check with `git status`. Closing as not related to the lib but with [git usage](https://stackoverflow.com/questions/15745045/how-do-i-resolve-git-saying-commit-your-changes-or-stash-them-before-you-can-me).
