### ISSUE TITLE
A and B drives excluded

### ISSUE THREAD

**Issue by sparkblaze** [shirou/gopsutil#582]
Is there a particular design reason that A and B drives are excluded inside disk_windows.go? Both letters can be assigned to drives within Windows without causing issues.

https://github.com/shirou/gopsutil/blob/eb1f1ab16f2ef35f23024e10888dfdb5c17fcb92/disk/disk_windows.go#L86

**Comment by shirou** [comment]
because original psutil [skips it](https://github.com/giampaolo/psutil/blob/master/psutil/_psutil_windows.c#L2634). The comment says "it introduces a considerable slowdown."

**Comment by egonelbre** [comment]
My guess is that by reading `A:` or `B:` on a machine with floppy drive it will cause the floppy drive to wake up and start reading it, which is slow.
