### ISSUE TITLE
[Linux]What's the differences between setting percpu to "true" and "false" in func Percent(interval time.Duration, percpu bool) ([]float64, error)?

### ISSUE THREAD

**Issue by FlyingFishPeng** [shirou/gopsutil#588]
I want to get the total  percentage of cpu used(us + sy + ni + wa) of my server, but I don't know how to set the percpu of "Percent(interval time.Duration, percpu bool) ". My test codes:
```
cpuMsg, err := cpu.Percent(time.Second, false)
cputmp, _ := cpu.Percent(time.Second, true)
fmt.Println("----------cpuMsg----------->", cpuMsg)
fmt.Println("----------cputmp----------->", cputmp)
```
The output is:
![image](https://user-images.githubusercontent.com/27657307/45625093-a899bb80-babe-11e8-8605-dd3b71cbd9d2.png)
```
----------cpuMsg-----------> [2.3959646823087843]
----------cputmp-----------> [0 21.000000019557774 1.0000000009313226 6.122448959227641 2.0202020178264397 0 0 0]
```

I don't understand what's the differences between these two massage. https://godoc.org/github.com/shirou/gopsutil/cpu says that " Returns one value per cpu, or a single value if percpu is set to false.". I guess that the "cputmp"  reprensents the total percentage of cpu used of each cpu or core, but I don't know what  is cpuMsg mean? 
My server has 8 cpus and each cpu has 1 core.

**Comment by Lomanic** [comment]
With percpu false, Percent returns system-wide CPU usage (one value returned). With percpu true, Percent returns CPU usage per each CPU core (one value for each core is returned).
The original psutil documentation is stating it like this https://psutil.readthedocs.io/en/latest/#psutil.cpu_percent

> Return a float representing the current system-wide CPU utilization as a percentage.
> When percpu is True returns a list of floats representing the utilization as a percentage for each CPU. First element of the list refers to first CPU, second element to second CPU and so on.

**Comment by FlyingFishPeng** [comment]
> With percpu false, Percent returns system-wide CPU usage (one value returned). With percpu true, Percent returns CPU usage per each CPU core (one value for each core is returned).
> The original psutil documentation is stating it like this https://psutil.readthedocs.io/en/latest/#psutil.cpu_percent
> 
> > Return a float representing the current system-wide CPU utilization as a percentage.
> > When percpu is True returns a list of floats representing the utilization as a percentage for each CPU. First element of the list refers to first CPU, second element to second CPU and so on.
> 
> Looks like you are looking for the total usage with percpu false.



> With percpu false, Percent returns system-wide CPU usage (one value returned). With percpu true, Percent returns CPU usage per each CPU core (one value for each core is returned).
> The original psutil documentation is stating it like this https://psutil.readthedocs.io/en/latest/#psutil.cpu_percent
> 
> > Return a float representing the current system-wide CPU utilization as a percentage.
> > When percpu is True returns a list of floats representing the utilization as a percentage for each CPU. First element of the list refers to first CPU, second element to second CPU and so on.
> 
> Looks like you are looking for the total usage with percpu false.

Got it!Thanks!
