### ISSUE TITLE
cpu.Percent() not implemented on darwin?

### ISSUE THREAD

**Issue by iwind** [shirou/gopsutil#592]
As "Process class" table in README file describes, "cpu_percent" should work on darwin, but my codes did not work:

* OS: macOS Mojave (Version 10.14)
* CPU: Intel Core i7
* Golang Codes:
~~~golang
stat, err := cpu.Percent(1 * time.Second, true)
log.Println(err)
~~~
Print out:
~~~
not implemented yet
~~~

**Comment by iwind** [comment]
It's my fault, `cgo` should be enabled when build.

**Comment by Lomanic** [comment]
This package+OS combination is one of the few exceptions needing cgo in gopsutil, we might improve the documentation to reflect that.

**Comment by axetroy** [comment]
this still happend in v3

**Comment by chengfeiZhou** [comment]
this still happend in v3

**Comment by iwind** [comment]
> this still happend in v3

works when `CGO_ENABLED=1`, such as
~~~bash
env GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build ...
~~~
