### ISSUE TITLE
Many undefined functions in process on OpenBSD/amd64

### ISSUE THREAD

**Issue by Lomanic** [shirou/gopsutil#604]
```
src/github.com/shirou/gopsutil/process/process.go:135:15: undefined: Pids
src/github.com/shirou/gopsutil/process/process.go:156:20: p.Times undefined (type *Process has no field or method Times)
src/github.com/shirou/gopsutil/process/process.go:166:20: p.Times undefined (type *Process has no field or method Times)
src/github.com/shirou/gopsutil/process/process.go:209:25: p.MemoryInfo undefined (type *Process has no field or method MemoryInfo)
src/github.com/shirou/gopsutil/process/process.go:224:20: p.CreateTime undefined (type *Process has no field or method CreateTime)
src/github.com/shirou/gopsutil/process/process.go:229:16: p.Times undefined (type *Process has no field or method Times)
src/github.com/shirou/gopsutil/process/process_posix.go:128:16: p.Uids undefined (type *Process has no field or method Uids, but does have uids)
*** Error code 2

Stop.
make: stopped in /z/go/bhyve-vm-goagent
```
_Originally posted by @araujobsd in https://github.com/shirou/gopsutil/issues/349#issuecomment-359325468_

**Comment by Lomanic** [comment]
Experienced the same issue while implementing #596 on OpenBSD, triggered with `GOOS=openbsd go build github.com/shirou/gopsutil/process` on amd64, I don't see anything suspicious in `process/process_openbsd.go`, is anybody able to run this `GOOS=openbsd go build …` command successfully?

**Comment by Lomanic** [comment]
This has to do with cgo , compilation on an OpenBSD host works properly, and explicitly setting `CGO_ENABLED=1` in `CGO_ENABLED=1 GOOS=openbsd go build github.com/shirou/gopsutil/process` makes the error vanish (another one shows up: `/usr/local/go/src/net/cgo_resold.go:21:102: cannot use _Ctype_ulong(len(b)) (type _Ctype_ulong) as type _Ctype_uint in argument to _C2func_getnameinfo`, but it might be some different C header compared to OpenBSD).

**Comment by azr** [comment]
Hello there @Lomanic, did you manage to make this error go away ? My guess is that we might need to build from a native OpenBSD system.

**Comment by Lomanic** [comment]
Yes indeed, you can't cross-compile from Linux (tested on Debian 9) to OpenBSD as OpenBSD implementation relies on cgo and cgo needs some OpenBSD system headers. Here is another occurence of this error https://git.kivikakk.ee/kivikakk/meres/issues/3 (compiling go-sqlite3 in this case).
