### ISSUE TITLE
It is not meet expectation when I use process.CmdlineSlice() to get redis-server cmdline in centos

### ISSUE THREAD

**Issue by dafanshu520** [shirou/gopsutil#606]
It is not meet expectation when I use process.CmdlineSlice() to get redis-server cmdline in centos, as followings:

ps -ef|grep redis-server
```
root      4386     1  0 Sep26 ?        04:53:24 redis-server 192.168.0.1:6379
```
ll /proc/4386
```
lrwxrwxrwx 1 root root 0 Nov  9 19:20 exe -> /usr/bin/redis-server
```
cat /proc/4386/cmdline
```
redis-server 192.168.0.1:6379
```
but the index 0 of the slice is redis-server 192.168.0.1:6379 instead of redis-server, is there anything wrong ?

**Comment by Lomanic** [comment]
From `man procps`


> **/proc/[pid]/cmdline**    
This read-only file holds the complete command line for the process, unless the process is a zombie. In the latter case, there is nothing in this file: that is, a read on this file will return 0 characters. The command-line arguments appear in this file as a set of strings separated by null bytes ('\0'), with a further null byte after the last string. 

This follows our implementation: https://github.com/shirou/gopsutil/blob/48177ef5f8809fc72b716c414435f2d4cff8e24d/process/process_linux.go#L833-L853

To see null bytes in your terminal: `cat -v /proc/4386/cmdline`

**Comment by dafanshu520** [comment]
thanks for your patience！
