### ISSUE TITLE
"Cannot change thread mode after it is set." error when calling disk.IOCounters on Windows

### ISSUE THREAD

**Issue by ericrange** [shirou/gopsutil#618]
**Describe the bug**
Sometimes i get an error when i want to get the io counters. But just sometimes...
"Cannot change thread mode after it is set."

**To Reproduce**
```go
        parts, err := disk.Partitions(false)
	for _, part := range parts {
		u, errUsage := disk.Usage(part.Mountpoint)
		if errUsage != nil {
			logger.Error.Println(errUsage)
			continue
		}

		counters, errIO := disk.IOCounters(part.Mountpoint)
		if errIO != nil {
		=>	logger.Error.Println(errIO)
                "Cannot change thread mode after it is set."
                ....
```

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Environment (please complete the following information):**
 - [x] Windows: [Windows Server 2012R2]
 - [ ] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
 - [ ] Mac OS: [paste the result of `sw_vers` and `uname -a`
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

**Comment by shirou** [comment]
I have created this gist.
https://gist.github.com/shirou/004b2a859ed5f33ca659e431b7378d17

- linux( 4.15.0-38-generic, go1.11.1) -> not error
- freebsd(11.2-RELEASE-p4, go1.11.1) -> not error

I have not digged the golang source code, but is it windows only?

**Comment by ericrange** [comment]
it seems that it is windows only. never got such an error for linux.
But as i said. it appears only "sometimes". Every 5 minutes, i guess.

**Comment by Lomanic** [comment]
Solution is probably to remove calls to WMI (see https://github.com/shirou/gopsutil/issues/692#issuecomment-496607303), performance counters might be an option here but way less easy to request than wmi (thanks to stackexchange/wmi package). [Here](https://bitbucket.org/mixmastamyk/winstats/src/b9e81bc2e43bbbdd68e466f008f7fa8c4bbe0b51/winstats.py#lines-272) is an example in Python, [here](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/win_perf_counters/pdh.go) is a promising package in Go.

**Comment by Lomanic** [comment]
disk.IOCounters doesn't use WMI internally after #850 was merged.
