### ISSUE TITLE
CPUPercent can't convert float64 to string

### ISSUE THREAD

**Issue by marshyski** [shirou/gopsutil#62]
When I try to convert CPUPercent from float64 to string I get the type error below.  I think it's because of the surrounding [] that's returned.  Not entirely sure why they're there, when the rest of the CPU returns don't have [].

    cpuPercent, _ := cpu.CPUPercent(time.Duration(1) * time.Second, false)
    cpuusedprctConv := strconv.FormatFloat(cpuPercent, 'f', -1, 64)

Error:  cannot use cpuPercent (type []float64) as type float64 in argument to strconv.FormatFloat

**Comment by shirou** [comment]
Because a node can have multiple CPUs, `CPUPercent` returnes array of float64. If you specify `percpu` argument to false or the node have only one CPU, you can use `cpuPercent[0]`.

**Comment by marshyski** [comment]
Ah okay, I apologize for that. Thank you for the help!
