### ISSUE TITLE
Add OpenBSD 6.4+ CPU States

### ISSUE THREAD

**Issue by pkotsiop** [shirou/gopsutil#621]
**Is your feature request related to a problem? Please describe.**
The cpu states of OpenBSD have changed (most probably since 6.3) and this logically (wrong information is returned) breaks most of the functions at cpu_openbsd.go.

**Describe the solution you'd like**
The best solution would be to create a script to extract the values from sched.h during build and if sched.h is not found then hardcode them and report a warning (i do not now GO and if warnings are possible during builds tho). Finally the script would create cpu_openbsd.go with the respective cpu states.

**Describe alternatives you've considered**
Create a script with hardcored different sets of values, figure out the version of openbsd during build and finally create cpu_openbsd.go.

**Additional context**
Tested on 6.2 (old values) and 6.4 (new values), but i do not have access at a 6.3 atm.

New cpu states from sched.h of an obsd6.4:

```c
#define CP_USER         0
#define CP_NICE         1
#define CP_SYS          2
#define CP_SPIN         3
#define CP_INTR         4
#define CP_IDLE         5
#define CPUSTATES       6
```

**Comment by Lomanic** [comment]
These values were changed in https://github.com/openbsd/src/commit/531d8034253fb82282f0f353c086e9ad827e031c and in a backward incompatible way…

Problem is not to detect these values at build time on the build machine but at runtime (you could compile on host A on OpenBSD 6.2 and run your binary on host B on OpenBSD 6.4 or vice versa)… `host.PlatformInformation` could be used for example.

**Comment by Lomanic** [comment]
https://ftp.hostserver.de/pub/OpenBSD/6.3/sys.tar.gz -> ./sys/sched.h

```c
#define CP_USER         0
#define CP_NICE         1
#define CP_SYS          2
#define CP_INTR         3
#define CP_IDLE         4
#define CPUSTATES       5
```

This change comes from OpenBSD 6.4.
