### ISSUE TITLE
memory test case is failed on darwin

### ISSUE THREAD

**Issue by mznet** [shirou/gopsutil#622]
**Describe the bug**
TestVirtual_memory of memory test case is failed

**To Reproduce**
in `mem` directory, run `go test` command

**Expected behavior**
all test cases in mem directory should be passed

**Environment (please complete the following information):**
 - [ ] Windows: [paste the result of `ver`]
 - [ ] Linux: []
 - [x] Mac OS: [Darwin xxx-MacBook-Pro.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64]
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

**Additional context**
No cross-compiled. I've found out `Inactive` metric should be summed to total memory, However, i am not sure that's enough and there is something else to consider.

**Comment by Lomanic** [comment]
Thanks for the report @mznet.
