### ISSUE TITLE
README.rst: create_time IS supported on Windows.

### ISSUE THREAD

**Issue by MMulthaupt** [shirou/gopsutil#630]
**Describe the bug**
The table for supported features in `README.rst` reports that `create_time` is not supported for Windows, but it is.

**To Reproduce**
Search for `create_time` in `README.rst` and notice that there is no `x` in the column for Windows. Then check `process_windows.go` to see that indeed `(p *Process) CreateTime()` is fully implemented and working.

**Expected behavior**
There is an `x` in the column for Windows.

**Additional context**
We had started implementing this ourselves, when apparently we didn't need to.

**Comment by shirou** [comment]
merged. Thanks!
