### ISSUE TITLE
Sysctl issues on FreeBSD armv6

### ISSUE THREAD

**Issue by robbiet480** [shirou/gopsutil#648]
**Describe the bug**
[A clear and concise description of what the bug is.]

Sysctl calls for `hw.physmem` and `vfs.bufspace` are expecting the wrong size (64 instead of 32) on FreeBSD armv6 systems.

**To Reproduce**
```go
// paste example code reproducing the bug you are reporting
physmem, err := unix.SysctlUint64("hw.physmem")
if err != nil { // error will be NIO
  fmt.Printf("physmem ERROR: %+v\n", err)
  panic(err)
}
buffers, err := unix.SysctlUint64("vfs.bufspace")
if err != nil { // error will be NIO
  fmt.Printf("bufspace ERROR %+v\n", err)
  panic(err)
}

```

The errors are fixed and values appear correct if `SysctlUint64` is changed to `SysctlUint32`.

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Environment (please complete the following information):**
 - [ ] Windows: [paste the result of `ver`]
 - [ ] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
 - [ ] Mac OS: [paste the result of `sw_vers` and `uname -a`
 - [X] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

```
[2.4.4-RELEASE][root@pfsense.local]/root: freebsd-version -k -r -u
11.2-RELEASE-p6
11.2-RELEASE-p6
11.2-RELEASE-p6
[2.4.4-RELEASE][root@pfsense.local]/root: uname -a
FreeBSD pfsense.local 11.2-RELEASE-p6 FreeBSD 11.2-RELEASE-p6 #5 ed5153fb2b9(factory-RELENG_2_4_4): Wed Dec 12 14:41:43 EST 2018     root@buildbot2.nyi.netgate.com:/build/factory-crossbuild-244/obj/armv6/tDULKC6G/arm.armv6/build/factory-crossbuild-244/pfSense/tmp/FreeBSD-src/sys/pfSense-SG-3100  arm
[2.4.4-RELEASE][root@pfsense.local]/root:
```

**Additional context**
[Cross-compiling? Paste the command you are using to cross-compile and the result of the corresponding `go env`]

```
$ GOOS=freebsd GOARCH=arm GOARM=7 go env
GOARCH="arm"
GOBIN=""
GOCACHE="/Users/robbiet480/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="freebsd"
GOPATH="/Users/robbiet480/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
GOARM="7"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6d/4n3mhsvx3ts7fmx4jb2zqw5r0000gn/T/go-build732691446=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by shirou** [comment]
I have opened #649. could you check it works or not?

**Comment by Lomanic** [comment]
Fixed in aforementioned MR.
