### ISSUE TITLE
cannot find package "github.com/shirou/gopsutil/internal/common"

### ISSUE THREAD

**Issue by wwwwwwchun** [shirou/gopsutil#660]
when i build the go files ,the centos 7.4 while print a error ,

sh coverall.sh
?       github.com/gopsutil-2.19.02     [no test files]
cpu/cpu.go:13:2: cannot find package "github.com/shirou/gopsutil/internal/common" in any of:
        /data/go/src/github.com/shirou/gopsutil/internal/common (from $GOROOT)
        /data/go/goProject/src/github.com/shirou/gopsutil/internal/common (from $GOPATH)

how to solve this proplem?
thank you

**Comment by Lomanic** [comment]
How did you install the library? Is GOPATH properly set (`go env GOPATH`)? What's in `/data/go/goProject/src/github.com/shirou/gopsutil/internal/common`?

**Comment by wwwwwwchun** [comment]
go path is GOPATH="/data/go/goProject",
in my centos7.4 server,i hav'nt /data/go/goProject/src/github.com/shirou/gopsutil/internal/common,
the source code putted in the /data/go/goProject/src/github.com/gopsutil-2.19.02

**Comment by Lomanic** [comment]
This has nothing to do with gopsutil but with how it was installed: go is unable to find the gopsutil lib because it is in the wrong path, install it with `go get -v github.com/shirou/gopsutil` (it should be in `$GOPATH/src/github.com/shirou/gopsutil`).
