### ISSUE TITLE
host/host_linux_amd64.go:33: undefined: _Ctype_struct___0

### ISSUE THREAD

**Issue by wwwwwwchun** [shirou/gopsutil#662]
when i execut sh coverall.sh command,
the result like:

```
?       github.com/shirou/gopsutil      [no test files]
ok      github.com/shirou/gopsutil/cpu  0.243s  coverage: 80.9% of statements
ok      github.com/shirou/gopsutil/disk 0.008s  coverage: 67.0% of statements
ok      github.com/shirou/gopsutil/docker       0.006s  coverage: 17.4% of statements
# github.com/shirou/gopsutil/host [github.com/shirou/gopsutil/host.test]
host/host_linux_amd64.go:33: undefined: _Ctype_struct___0
FAIL    github.com/shirou/gopsutil/host [build failed]
```

how can i do ?

**Comment by Lomanic** [comment]
I don't reproduce on Linux x64. Please tell us more about your environment (this is what the questions in the issue template are for) so we can try to trigger this same error.

**Comment by wwwwwwchun** [comment]
the server env is : 
os : CentOS Linux release 7.3.1611 (Core)
bit : 64bit
go version:go version go1.12.1 linux/amd64
export GOROOT=/data/go
export GOPATH=/data/go/goProject
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOROOT/bin
export PATH=$PATH:$GOPATH/bin
