### ISSUE TITLE
Add device id to disk.PartitionStat

### ISSUE THREAD

**Issue by danielnelson** [shirou/gopsutil#664]
**Is your feature request related to a problem? Please describe.**

I have functionality that is meant to act similarly to the `df` command, it uses `disk.Partitions(` to get a list of partitions, and then follows it up with a call to `disk.Usage(`.

One place where our gopsutil based tool differs from the coreutils `df` utility is that `df` only reports one mount when there are multiple mounts per device, unless this behavior is disabled with `df -a`.

When working with bind mounts, most commonly in Docker, there may be many duplicate mounts, and it would be nice to be able to mimic the behavior of `df`.  The `df` tool uses the device ID (major/minor number) to compare identity of devices and this seems like a good method.

**Describe the solution you'd like**
Add `DeviceID` field to the disk.PartitionStat struct, or, a more robust way to get the device ID.

On Linux, this information is contained in the primary file already being parsed `/proc/self/mountinfo`.  For other platforms, I'm not sure, perhaps there is something equivilent on Windows?

**Describe alternatives you've considered**
I attempted to lookup this information after the call to `disk.Partitions` with `man 2 stat`, but this can fail if the device is not found or it doesn't have a device file. In docker the device file may be elsewhere on the system when using HOST_PROC to mount the root filesystem from the host into the container.

**Additional context**
https://github.com/influxdata/telegraf/issues/5615

**Comment by shirou** [comment]
Sorry, I can not get it. Is this occurred inside a docker container? And I think `disk_linux.go` already uses `/proc/self/mountinfo` [here](https://github.com/shirou/gopsutil/blob/master/disk/disk_linux.go#L229).

**Comment by danielnelson** [comment]
I was trying to write a better explanation about this tonight, and I think I have found a way that I can make it work without any changes.  I'll continue working on this and if I run into an issue I can't resolve then I'll reopen with a more clear report.

**Comment by tmm1** [comment]
@danielnelson what was your solution?

**Comment by danielnelson** [comment]
Unfortunately I can't remember, it has been too long and I never ended up fixing the related issue in Telegraf, sorry.
