### ISSUE TITLE
Missing ProcsTotal in load

### ISSUE THREAD

**Issue by genofire** [shirou/gopsutil#667]
https://godoc.org/github.com/shirou/gopsutil/load

```
type MiscStat struct {
    ProcsTotal int `json:"procsTotal"`
    ProcsRunning int `json:"procsRunning"`
    ProcsBlocked int `json:"procsBlocked"`
    Ctxt         int `json:"ctxt"`
}
```

**Comment by Lomanic** [comment]
What do you mean?

**Comment by genofire** [comment]
> The value after the slash is the number of kernel scheduling entities that currently exist on the system. 
```
genofire@ ~ % cat /proc/loadavg
0.92   0.60   0.50         2/916    22393
load1 load5 load15  running/total   highestpid
```

**Comment by pytimer** [comment]
@genofire You mean that the `MiscStat` struct should add process total, is it? I can take it and implement it. But i want to know which struct should add the process total, `AvgStat` or `MiscStat`?

@genofire @Lomanic What do you think?

**Comment by genofire** [comment]
I prefer `MiscStat` together with the count of `ProcsRunning`

**Comment by shirou** [comment]
I agree to add `ProcsTotal` to `MiscStat`.

**Comment by pytimer** [comment]
@shirou I found you create a issue about [Rename load.MiscStat](https://github.com/shirou/gopsutil/issues/680), if i implement `ProcsTotal`,  do i need to care it?

**Comment by pytimer** [comment]
I send a pr to implement it, but i only know linux about it, so i only implement it.

**Comment by shirou** [comment]
Thank you for your contribution! I will add same information on other platform.
