### ISSUE TITLE
Avoid Floats in Reported Metrics

### ISSUE THREAD

**Issue by tychoish** [shirou/gopsutil#669]
**Is your feature request related to a problem? Please describe.**

In a few months, I'd like to start using data from gopsutil to collect timeseries data about system performance. We have a timeseries data format that we've used before [ftdc](https://github.com/mongodb/ftdc), but it doesn't work well with floats, and a large number of 

**Describe the solution you'd like**

I think in a lot of cases we can just change fields that are currently float64 to use int64s, as I think many values are actually integers.

It might also make sense, in cases where underlying values are the result of division in gopsutil, to represent the values before division using 

**Describe alternatives you've considered**

We could mirror gopsutil types with and convert to integer types, truncate values before compression, or provide some kind of gopsutil-integer fork, but it seems like this might be generally useful to everyone, so I'd like to think about the best ways to upstream it if interested. 

**Additional context**

We're willing to do some/most of the work here, but wanted to gauge interest or appropriate direction before beginning to figure it out on our own.

**Comment by mznet** [comment]
@tychoish I don't think so, many system metrics can be consider as `Integer`, however, there are a few metrics should exist as `Float` such as `load` and `cpu`. Observing fine changes, floating point,  of `load` and `cpu` can be sometime pretty important. These minor changes let us forecast the events we should handle for the future.

**Comment by Lomanic** [comment]
This would completely break backward compatibility for little reason. Converting types should be done in downstream programs or libraries. Agreeing with @mznet also.

**Comment by tychoish** [comment]
I'm pretty sure that I've noticed some drift in types over the past couple of years, nothing major, and we could change field names a bit to to make that transition easier. 

In cases where floats are actually the correct type, or that there is some fractional component, we could replace with some kind of utility type that could capture the operation operation and provide/resolve to computed number, solving both use cases.

**Comment by cmattoon** [comment]
Agreed with above - I'd expect the float -> int conversion to be the responsibility of some stats exporter and for gopsutil to give me as-raw-as-possible data for writing such an exporter. I think the upstream solution is `int(floatval)`. 

There's also the issue of writing values back, or interacting with C, etc, where type information needs preserved. Converting from float to int to float is lossy, and converting back and forth, twice, for no reason, via some utility type, is generally going to be a non-starter for that class of programs.

What float64s would you change to int64?

**Comment by Lomanic** [comment]
Closing as won't implement, this is really specific and should be handled downstream.
