### ISSUE TITLE
build failed on mac about cgo

### ISSUE THREAD

**Issue by upccup** [shirou/gopsutil#67]
i meet a problem when build gopsutil on mac 

full error output:
not-type:1:35: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_1_2(void) { GoBytes *__cgo_undefined__; }
                        
not-const:1:63: error: invalid operands to binary expression ('_GoBytes_ (*)(void *, int)' and 'int')
void __cgo_f_1_3(void) { enum { __cgo__undefined__ = (GoBytes)*1 }; }
                                            
not-type:2:52: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_2_2(void) { HOST_CPU_LOAD_INFO_COUNT *__cgo_undefined__; }
                                                   
not-const:3:81: error: indirection requires pointer operand ('int' invalid)
void __cgo_f_3_3(void) { enum { __cgo__undefined__ = (host_cpu_load_info_data_t)*1 }; }
                                                                                
not-const:4:67: error: indirection requires pointer operand ('int' invalid)
void __cgo_f_4_3(void) { enum { __cgo__undefined__ = (host_info_t)*1 }; }
                                                                  
not-type:5:47: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_5_2(void) { host_processor_info *__cgo_undefined__; }
                                              
not-const:5:75: error: invalid operands to binary expression ('kern_return_t (*)(host_t, processor_flavor_t, natural_t *, processor_info_array_t *, mach_msg_type_number_t *)' and 'int')
void __cgo_f_5_3(void) { enum { __cgo__undefined__ = (host_processor_info)*1 }; }
                                             
not-type:6:43: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_6_2(void) { host_statistics *__cgo_undefined__; }
                                       
not-const:6:71: error: invalid operands to binary expression ('kern_return_t (*)(host_t, host_flavor_t, host_info_t, mach_msg_type_number_t *)' and 'int')
void __cgo_f_6_3(void) { enum { __cgo__undefined__ = (host_statistics)*1 }; }
                                         
not-const:7:62: error: indirection requires pointer operand ('int' invalid)
void __cgo_f_7_3(void) { enum { __cgo__undefined__ = (host_t)*1 }; }

**Comment by shirou** [comment]
cgo is required to build on darwin (see #66). I think this error is related to cgo. Could you check your installed go argument? Go should be build with cgo-enabled.

Could you try to build `CGO_ENABLED=1` like
```
CGO_ENABLED=1 go test ./...
```

Thank you.

**Comment by upccup** [comment]
@shirou   it's ok after i reinstall with  *sudo brew install go*.   Thank you very much

**Comment by shirou** [comment]
grad to hear that. if you meet other problem, feel free to open an issue.
