### ISSUE TITLE
Race condition in `process.Exe()` on macOS

### ISSUE THREAD

**Issue by InTheorium** [shirou/gopsutil#670]
**Describe the bug**
A race condition triggers when calling the `Exe()` method on macOS: https://github.com/shirou/gopsutil/blob/master/process/process_darwin.go#L102

```
==================
WARNING: DATA RACE
Write at 0x00c0000b25f0 by goroutine 8:
  bytes.(*Buffer).ReadFrom()
      /usr/local/go/src/bytes/buffer.go:203 +0x4b
  io.copyBuffer()
      /usr/local/go/src/io/io.go:388 +0x3f5
  os/exec.(*Cmd).writerDescriptor.func1()
      /usr/local/go/src/io/io.go:364 +0x7a
  os/exec.(*Cmd).Start.func1()
      /usr/local/go/src/os/exec/exec.go:409 +0x34

Previous write at 0x00c0000b25f0 by goroutine 6:
  bytes.(*Buffer).ReadFrom()
      /usr/local/go/src/bytes/buffer.go:203 +0x4b
  io.copyBuffer()
      /usr/local/go/src/io/io.go:388 +0x3f5
  os/exec.(*Cmd).writerDescriptor.func1()
      /usr/local/go/src/io/io.go:364 +0x7a
  os/exec.(*Cmd).Start.func1()
      /usr/local/go/src/os/exec/exec.go:409 +0x34

Goroutine 8 (running) created at:
  os/exec.(*Cmd).Start()
      /usr/local/go/src/os/exec/exec.go:408 +0x9c3
  github.com/shirou/gopsutil/internal/common.Pipeline()
      /Users/bluger/dev/go/pkg/mod/github.com/shirou/gopsutil@v2.18.12+incompatible/internal/common/common.go:362 +0x477
  github.com/shirou/gopsutil/process.(*Process).ExeWithContext()
      /Users/bluger/dev/go/pkg/mod/github.com/shirou/gopsutil@v2.18.12+incompatible/process/process_darwin.go:126 +0x40d
  main.main()
      /Users/bluger/dev/go/pkg/mod/github.com/shirou/gopsutil@v2.18.12+incompatible/process/process_darwin.go:103 +0xcd

Goroutine 6 (running) created at:
  os/exec.(*Cmd).Start()
      /usr/local/go/src/os/exec/exec.go:408 +0x9c3
  github.com/shirou/gopsutil/internal/common.Pipeline()
      /Users/bluger/dev/go/pkg/mod/github.com/shirou/gopsutil@v2.18.12+incompatible/internal/common/common.go:362 +0x477
  github.com/shirou/gopsutil/process.(*Process).ExeWithContext()
      /Users/bluger/dev/go/pkg/mod/github.com/shirou/gopsutil@v2.18.12+incompatible/process/process_darwin.go:126 +0x40d
  main.main()
      /Users/bluger/dev/go/pkg/mod/github.com/shirou/gopsutil@v2.18.12+incompatible/process/process_darwin.go:103 +0xcd
==================
```

**To Reproduce**
Replace `<insert pid>` with a valid PID from your system and build using `go build -race`. Running it will immediately trigger a race condition.

```
package main

import (
    "github.com/shirou/gopsutil/process"
)

func main() {
    procData, _ := process.NewProcess(<insert pid>)
    procData.Exe()
}
```

**Expected behavior**
A race condition should not occur.

**Environment (please complete the following information):**
 - [ ] Windows: [paste the result of `ver`]
 - [ ] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
 - [ ] Mac OS: [paste the result of `sw_vers` and `uname -a`
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

```
ProductName: Mac OS X
ProductVersion: 10.14.3
BuildVersion: 18D109

Darwin Brians-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```

**Additional context**
[Cross-compiling? Paste the command you are using to cross-compile and the result of the corresponding `go env`]

**Comment by shirou** [comment]
Thank you so much! I can reproduce in Linux.
https://gist.github.com/shirou/4fe0204a731e32e1f9a9f5735a1c9359

So It must be in `common.Pipeline()` But still I could not found the root cause. If you find something, please update this issue. Thanks!

**Comment by Lomanic** [comment]
I think we should remove this function, it's only used [in `process.Exe()` on darwin](https://github.com/shirou/gopsutil/blob/2cbc9195c892b304060269ef280375236d2fcac9/process/process_darwin.go#L126) and it would be more optimized to not spawn an awk and sed pair of commands (forking is more expensive than reimplementing what these commands do, especially awk that's a complete language and relatively slow).

**Comment by shirou** [comment]
Sounds good!
