### ISSUE TITLE
CPU Stolen never set

### ISSUE THREAD

**Issue by lootek** [shirou/gopsutil#676]
**Is your feature request related to a problem? Please describe.**
`Stolen` field defined in https://github.com/shirou/gopsutil/blob/c0ca431bf14f97366fb6267a7174115216f180d9/cpu/cpu.go#L30 is never set.

**Describe the solution you'd like**
There is a `Steal` field, that's being set for linux only. Since it's probably a duplicate, I'd opt for removing `Stolen` (it's a breaking change however so _aliasing_ it to `Steal` is also a kind of solution here. 

**Additional context**
`Stolen` field should not be used in calculation for summing up CPU usage (it doesn't change the result but introduces some noise into code).

**Comment by Lomanic** [comment]
If it's not set and it duplicates another field I honestly think it would be better to remove that useless field. If users use it, their code is already broken, if they update their gopsutil version they would be able to fix their code and use the proper field.

**Comment by shirou** [comment]
Good catch! `Stolen` is added `2015-02-13`, perhaps I was so sleepy. let's remove `Stolen` field. I have created a PR, #677

**Comment by shirou** [comment]
#677 is merged. Thank you for the report!
