### ISSUE TITLE
[process][linux] Reimplement TOP  process.CPUPercent()

### ISSUE THREAD

**Issue by c95611** [shirou/gopsutil#690]
**[Issue]**
Hi, I am learening GO and I was tring to reimplement Top (Linux's instruction).
I found when using process.CPUPercent() to output the process's CPU Usage, there some different compare to Top's CPU Usage.
If I create a dead loop, it take times to increase the value of %CPU, and it seems the %CPU value of TOP is more sensitive to precess.CPUPercent.
How this solve or the answer.
Please help me with my questions.Thanks!
(sorry for the poor english)

**[the value]**
![image](https://user-images.githubusercontent.com/43921070/58249860-8addce00-7d92-11e9-808b-e1ab684f336b.png)

**[open dead loop]**
a.out is a dead loop process, it takes time to increase the value and seems can not get to 100
![image](https://user-images.githubusercontent.com/43921070/58249989-dee8b280-7d92-11e9-8afd-93e43f345377.png)

**[CODE]**
```go
func NewSort() {
	ProcessInfo,err := process.Processes()
	p = ProcessInfo
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("PID    PPID   USER  %%CPU  %%MEM Status Name\n")
	sort.Sort(pInfo(p))
	for i := 0; i < number; i++ {
		pid		:= p[i].Pid
		ppid,_	:= p[i].Ppid()
		user,_	:= p[i].Username()
		cpu,_	:= p[i].CPUPercent()
		mem,_	:= p[i].MemoryPercent()
		sta,_	:= p[i].Status()
		str,_	:= p[i].Name()


		fmt.Printf("%-6v %-6v %-5v %-5.1f %-5.1f %-5v %-15v\n", pid, ppid, user, cpu, mem, sta, str)
	}
	fmt.Println()
}
```

**Comment by Lomanic** [comment]
Implementation between top and gopsutil should be compared to see how they differ, it has to be in these few C files https://gitlab.com/procps-ng/procps/tree/master/top.

Do you have the same result if trying to do the same thing in python and original psutil? As gopsutil is a port of python's version, we should be faithful to the original instead of top.

**Comment by Lomanic** [comment]
Closing in favor of #732.
