### ISSUE TITLE
Unexpected counter reset in net.IOCounters on windows

### ISSUE THREAD

**Issue by boeckstefan** [shirou/gopsutil#693]
**Describe the bug**
* Usage of uint32 as a uint64 value in net.IOCounters for windows
* see https://godoc.org/golang.org/x/sys/windows#MibIfRow
* those are cast to uint64 on [https://github.com/shirou/gopsutil/blob/e146c2e08a4527e58c240fb43f9184bb63d17bc8/net/net_windows.go#L97 ](https://github.com/shirou/gopsutil/blob/e146c2e08a4527e58c240fb43f9184bb63d17bc8/net/net_windows.go#L97)
* Counter reset had to be checked manually (uint subtraction produce very wrong overflows, resulting in a very high net usage like EB/s)

**To Reproduce**
```go
// see code in explaination
```

**Expected behavior**
* If possible real uint64 as counters would be nice, as uint32 counters canl overflow every 3,2 seconds on a 10GBit interface.

**Environment (please complete the following information):**
 - [x] Windows: [all versions]
 - [ ] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
 - [ ] Mac OS: [paste the result of `sw_vers` and `uname -a`
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

**Comment by Lomanic** [comment]
> If possible real uint64 as counters would be nice, as uint32 counters canl overflow every 3,2 seconds on a 10GBit interface.

The [MIB_IFROW structure](https://docs.microsoft.com/fr-fr/windows/desktop/api/ifmib/ns-ifmib-_mib_ifrow) (corresponding to [windows.MibIfRow](https://godoc.org/golang.org/x/sys/windows#MibIfRow)) is defined with DWORD fields (uint32) in win32 API, we can't do much about that.

Not sure how we could handle that kind of overflow in gopsutil though. How were you able to check that on your side @boeckstefan?

**Comment by boeckstefan** [comment]
We found an error while monitoring network usage through net.IOCounters. We poll those counters every 5 minutes subtract the new from the old value and divide through said 5 minutes. While it works very well on linux on windows we got a strange error every few hours on windows server. We then logged every IOCounter we messured and compared them and found a 32bit counter reset when an error occurred. Due to the nature of uint64 overflows the subtraction value didn't make any sense (An uint32 substraction would have made sens).

* Further investigation showed that the gopsutils cast an uint32 into an uint64 (see above)
* Sadly i don't have any idea how to handle it in gopsutils, i was hoping that maybe windows would provide some 64bit counters.
* Our workaround is:
``` go
func Diff32in64Counter(a, b uint64) uint64 {
	return uint64(uint32(a) - uint32(b))
}
```
* But 32Bit counterstats for a 10GBit interface can run out in between 3 to 4s. Meaning you had to pull those counterstat quite often (2^32 / (10GBit/s /8) = 3,43 seconds).
* Searching through some wmi classes for an alternative reveals that they don't provide IOCounters only values for bytes in seconds (but maybe i'm missing somthing here)

**Comment by boeckstefan** [comment]
* searching through windows issues, this issue is the same as #554 (sorry didn't see it earlier)
* in issue #554 such a counter reset is described (convert the numbers there to binary)

**Comment by Lomanic** [comment]
There is in fact a [MIB_IF_ROW2](https://docs.microsoft.com/fr-fr/windows/desktop/api/netioapi/ns-netioapi-_mib_if_row2) structure defined in win32 API that has some fields defined as ULONG64 (uint64), available for Vista+ (used with [GetIfEntry2](https://docs.microsoft.com/en-us/windows/desktop/api/netioapi/nf-netioapi-getifentry2)). So as on other implementations on Windows, we should check if GetIfEntry2 is available and use it and a new MIB_IF_ROW2 type instead of windows.GetIfEntry.
