### ISSUE TITLE
platformFamily is empty on macOS

### ISSUE THREAD

**Issue by martinlindhe** [shirou/gopsutil#694]
**Describe the bug**
Value platformFamily in host.InfoStat is empty on macOS.

**To Reproduce**
```go
package main

import (
	"fmt"

	"github.com/shirou/gopsutil/host"
)

func main() {
	i, _ := host.Info()
	fmt.Printf("%+v", i)
	// output: {"hostname":"laptop","uptime":124542,"bootTime":1558595441,"procs":411,"os":"darwin","platform":"darwin","platformFamily":"","platformVersion":"10.14.5","kernelVersion":"18.6.0","virtualizationSystem":"","virtualizationRole":"","hostid":"xxx-xx-xx-xx-xxx"}
}
```

**Expected behavior**
platformFamily should be "darwin"

**Comment by Lomanic** [comment]
Indeed, platformFamily gets set to an empty string by `PlatformInformation` [here](https://github.com/shirou/gopsutil/blob/master/host/host_darwin.go#L46) despite being set as `darwin` [a few lines before](https://github.com/shirou/gopsutil/blob/master/host/host_darwin.go#L33). 

But compared to what's done on windows and linux platforms (respectively returning if host is a server or not ; returning the distribution type), I'm not convinced returning the same thing as the `platform` or OS fields is the right thing to do. *BSDs also return an empty string. Only exception seems to be Solaris which has its platformFamily set to `solaris`.

We could instead return if host is a server or not like  on windows [this way](https://stackoverflow.com/questions/2645185/how-to-programmatically-detect-mac-os-x-server-edition), which is a more interesting information than repeating the other fields in this value.
