### ISSUE TITLE
cpu.PercentWithContext ignores context cancellation

### ISSUE THREAD

**Issue by mlaterman** [shirou/gopsutil#724]
**Describe the bug**
The cpu.PercentWithContext function ignores context cancellation 

**To Reproduce**
```go
ctx, cancel := context.WithCancel(context.Background())
cancel()
values, err := cpu.PercentWithContext(ctx, time.Second, false)
// the PercentWithContext will wait a second and not return due to a cancelled context
```

**Expected behavior**
```go
values, err := cpu.PercentWithContext(ctx, time.Second, false)
```
Should return with an error indicating a cancelled context

**Environment (please complete the following information):**
The issue should be present across all environments as method at: https://github.com/shirou/gopsutil/blob/master/cpu/cpu.go#L142 does not use the passed context

**Comment by shirou** [comment]
Currently, `ctx` is used by only a few method (method invoking external programs). I have added `ctx` for all methods to just a consistency. But your question is true, we'd better to expand cancellation to all method. PR is always welcome!

**Comment by xCoderly** [comment]
when CPU Load get higher i got context deadline exceeded!

how can i work without timeouts.?!

how can i set the Timeout that's in the comman package? from cpu / host / mem?

`Timeout  = 30 * time.Second
`

**Comment by 0x5d** [comment]
@shirou is there any progress on actually using the passed context to functions like [KillWithContext](https://github.com/shirou/gopsutil/blob/27358e8a2f8387f8aa0c9dfd96b69d5b44a4e6a8/process/process_posix.go#L170)? I was about to use some of them and just by chance went to read the source, but noticed the passed values are ignored, like you mentioned.

**Comment by JmPotato** [comment]
I think https://github.com/shirou/gopsutil/commit/34df4904f66be9b3b4a62c879a4ec4547072bc80 have fixed this problem. Cloud we close this issue? cc @mlaterman @shirou

**Comment by mlaterman** [comment]
Confirmed this is no longer an issue
