### ISSUE TITLE
common.NumProc on linux reports incorrect values

### ISSUE THREAD

**Issue by traetox** [shirou/gopsutil#730]
**Describe the bug**
common.NumProc on linux does not differentiate between pid dirs and other proc directories

**To Reproduce**
```go
// N/A
```

**Expected behavior**
common.NumProc only reports actual PIDs

**Environment (please complete the following information):**
 - [X] Linux: [all]

**Additional context**

**Comment by shirou** [comment]
Thank you for your report! it is closed via #731
