### ISSUE TITLE
A process's  CpuPercent is different from taskmanager's.

### ISSUE THREAD

**Issue by Lonenso** [shirou/gopsutil#732]
Hi,I am using gopsutil to monitor a process's resource like every 5 seconds.

I found gopsutil's process.CpuPercent times 2(core nums) hardly equals its cpupercent which seen in task manager. 
![image](https://user-images.githubusercontent.com/22173979/62193333-1e8ed480-b3aa-11e9-96e7-bdfa50e2976d.png)

But, It works a little better on linux(centos 7, same code).
![image](https://user-images.githubusercontent.com/22173979/62194126-c789ff00-b3ab-11e9-9cc0-a37e9412b731.png)

How to fix this? 
And sorry about my English.
Here's the code.

```
package main

import (
	"fmt"
	"github.com/shirou/gopsutil/process"
	"os"
	"runtime"
)

func main() {
	for {
		pid := os.Getpid()
		ps, err := process.NewProcess(int32(pid))
		if err != nil {
			panic(err.Error())
		}

		cp, err := ps.CPUPercent() 
		if err != nil {
			panic(err.Error())
		}
		mp, err := ps.MemoryPercent()
		if err != nil {
			panic(err.Error())
		}
		pn, err := ps.Name()
		if err != nil {
			panic(err.Error())
		}
		cores := runtime.NumCPU()
		fmt.Printf("pid: %d cores: %d cpu: %fmem: %fname: %s\n", pid, cores, cp, mp, pn)
	}
}
```

**Comment by Lomanic** [comment]
It's #690 again, but this time on Windows. gopsutil is a port of psutil, can you compare values from python original implementation and from gopsutil? We aim them to be the same as psutil, we don't care so much about what's displayed in the OS task manager (be it Windows task manager or (h)top on Unix), in this case we can't know how Windows task manager (or the OS probably) calculates these values.

**Comment by Lonenso** [comment]
@Lomanic thanks for your reply. I'll test it.
