### ISSUE TITLE
osx no mach_host_self and mach_task_self

### ISSUE THREAD

**Issue by shaojintian** [shirou/gopsutil#736]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
```go
// paste example code reproducing the bug you are reporting
```

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Environment (please complete the following information):**
 - [ ] Windows: [paste the result of `ver`]
 - [ ] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
 - [1 ] Mac OS: [paste the result of `sw_vers` and `uname -a`
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

**Additional context**
[Cross-compiling? Paste the command you are using to cross-compile and the result of the corresponding `go env`]
![image](https://user-images.githubusercontent.com/40530183/62343154-3ab28300-b51c-11e9-94c8-ace91ca6f035.png)

**Comment by shaojintian** [comment]
github.com/shirou/gopsutil@v2.19.6+incompatible/cpu/cpu_darwin_cgo.go:37:43: could not determine kind of name for C.mach_host_self
/gopsutil@v2.19.6+incompatible/cpu/cpu_darwin_cgo.go:49:23: could not determine kind of name for C.mach_task_self_

**Comment by Lomanic** [comment]
This is a bad bug report. You give absolutely zero context and care so much you submit an empty issue template. I won't beg for information already asked in the template so I will just close this issue as invalid unless you edit your first message with what's asked in the template.

**Comment by shaojintian** [comment]
It is totally definitely obviously clear enough!
it is cpu/cpu_drawin_cgo.go 
![image](https://user-images.githubusercontent.com/40530183/62355234-2fbe1980-b541-11e9-892e-6e531cda3f40.png)
YOUR project  import some C library like above
my system file lacks C.mach_host_self  variable
I need you to teel me where is the variable "mach_host_self ' in these C headers files

**Comment by shaojintian** [comment]
![image](https://user-images.githubusercontent.com/40530183/62355431-9a6f5500-b541-11e9-98eb-e5f4bf321bc3.png)

**Comment by shaojintian** [comment]
Why I need to follow your template ?
I am your slave?
