### ISSUE TITLE
undefined: "golang.org/x/sys/windows".PROCESS_QUERY_LIMITED_INFORMATION

### ISSUE THREAD

**Issue by AndreKR** [shirou/gopsutil#743]
**Describe the bug**
Error when compiling with Go 1.12:

`undefined: "golang.org/x/sys/windows".PROCESS_QUERY_LIMITED_INFORMATION`

**To Reproduce**
```go
package main
import _ "github.com/shirou/gopsutil/process"
func main() {}
```

**Expected behavior**
No errors

**Environment (please complete the following information):**
 - [X] Windows: `Microsoft Windows [Version 6.1.7601]`

**Notes**

The constant was recently added to Go (https://github.com/golang/sys/commit/79a91cf218c425e1f4d48cd960839b45dd4d065f), but is not yet available in the current stable version (Go 1.12).

Is this package supposed to work with Go 1.12? Otherwise please close this issue and I'll wait for Go 1.13.

**Comment by Lomanic** [comment]
I don't think it's related to Go version, but with `golang.org/x/sys/windows` version, can you try updating it with `go get -u golang.org/x/sys/windows`?

**Comment by AndreKR** [comment]
Indeed that works. I was pretty sure those `/x/` packages were part of the Go distribution. Sorry for the noise.

**Comment by Lomanic** [comment]
No problem, glad to help.
