### ISSUE TITLE
undefined: "golang.org/x/sys/windows".ERROR_INVALID_PARAMETER

### ISSUE THREAD

**Issue by AndreKR** [shirou/gopsutil#744]
**Describe the bug**
Error when compiling:

`undefined: "golang.org/x/sys/windows".ERROR_INVALID_PARAMETER`

**To Reproduce**
```go
package main
import _ "github.com/shirou/gopsutil/process"
func main() {}
```

**Expected behavior**
No errors

**Environment (please complete the following information):**
 - [X] Windows: `Microsoft Windows [Version 6.1.7601]`

**Notes**

I was unable to find any version of `types_windows.go` that would include this constant.

**Comment by Lomanic** [comment]
Closing as it's the same thing as https://github.com/shirou/gopsutil/issues/743

**Comment by AndreKR** [comment]
Indeed it works with the newest version of `golang.org/x/sys/windows`, the constant is in `zerrors_windows.go`.
