### ISSUE TITLE
About CPUTimes 

### ISSUE THREAD

**Issue by upccup** [shirou/gopsutil#76]
Hi @shirou  i have a question CPUTimes 
if i give the param percpu false. Through the code, I think I get to be the first CPU information  but you write as "cpu-total"  Both are equal it?

**Comment by shirou** [comment]
original python psutil returns cpu-total-sum if percpu is false. And gopsutil also returns cpu-total-sum if percpu is false. if you find a bug, please let me know with what architecture you use.

Thank you.

**Comment by upccup** [comment]
@shirou Thank you for your reply  i use it in ubuntu14.4 with golang 
Through your code I understand it is that you get the first piece of CPU state when the parameter is the value false instead of all or a combination of all of the CPU and CPU state   I'm not sure whether you do it for all the CPU state reaction

**Comment by shirou** [comment]
`/proc/stat` on Linux is like this.

```
cpu  8396257 168024 2066813 4683926935 373796 2084 106614 182508 0 0
cpu0 2093478 128915 943679 2343735446 323843 545 8658 97828 0 0
cpu1 6302778 39108 1123134 2340191488 49953 1539 97956 84679 0 0
```

The first line is a total of all cpu times. So, if `percpu` is False, we need only first line, I think.

**Comment by upccup** [comment]
@shirou I get it . I was wrong to thank you very much
