### ISSUE TITLE
How to calculate the CPU usage of a process in Windows?

### ISSUE THREAD

**Issue by hjzCy** [shirou/gopsutil#765]
```go
pro, _ := process.NewProcess(644)
fmt.Println(pro.CPUPercent())
```

`CPUPercent()` The result is not consistent with the CPU usage result of the process in the task manager. How can I get it?

**Comment by Lomanic** [comment]
You can't. Microsoft doesn't publish the formula for calculating this the same way as shown in the Task Manager.

Duplicate of https://github.com/shirou/gopsutil/issues/732
