### ISSUE TITLE
Add /v2 suffix in go.mod to be compliant with go 1.13

### ISSUE THREAD

**Issue by MMulthaupt** [shirou/gopsutil#770]
Starting with Go 1.13, it is not possible to use gopsutil via go modules without resorting to using a pseudo-version identifier in go.mod.

E.g., instead of `v2.19.8` one must use `e4ec7b275ada`, which resolves to `v0.0.0-20190901111213-e4ec7b275ada` with `go mod tidy`.

Please see this issue report for more info: https://github.com/golang/go/issues/34402

**Comment by Lomanic** [comment]
I reopened #663 for this, thanks for the report.
