### ISSUE TITLE
Request for bogomips as part of cpuinfo.

### ISSUE THREAD

**Issue by selvik** [shirou/gopsutil#78]
Thanks for the useful tool!  It would be great if bogomips could be added as part of the CPU stats.

**Comment by shirou** [comment]
Bogomips is defined for only Linux. Since gopsutil is for the multi-platform, I can not add platform-specific field to the `CPUInfoStat`, sorry.

**Comment by selvik** [comment]
Ahh...valid point, that makes sense! Thanks for replying.

**Comment by shirou** [comment]
Thanks for your understanding. I close this issue.
