### ISSUE TITLE
diskio utilization

### ISSUE THREAD

**Issue by Dong-Chan** [shirou/gopsutil#791]
**Is your feature request related to a problem? Please describe.**
I can't ease know diskio busy or not.

**Describe the solution you'd like**
I want to show utilization of diskio when I monitor disk input or output.

**Additional context**
gopsutil can compute util for the reponse result.

**Comment by Lomanic** [comment]
You can get disk statistics with [disk.IOCounters](https://godoc.org/github.com/shirou/gopsutil/disk#IOCounters).

gopsutil won't provide helper functions for this kind of tasks, as API is already large and this is not the intent of (go)psutil.
