### ISSUE TITLE
[QUESTION] system interrupt and context switches

### ISSUE THREAD

**Issue by MarcMagnin** [shirou/gopsutil#792]
I'm looking to get the `dstat --sys` interrupts and context switches (linux). Is there is a way to get those via gopsutils?

dstat ref: https://linux.die.net/man/1/dstat

**Comment by Lomanic** [comment]
The only context switches reported by gopsutil are for individual processes with [process.NumCtxSwitches()](https://godoc.org/github.com/shirou/gopsutil/process#Process.NumCtxSwitches). I don't find any reported interrupts.
