### ISSUE TITLE
[QUESTION] io stats

### ISSUE THREAD

**Issue by MarcMagnin** [shirou/gopsutil#793]
`dstat -r` provides read and write requests issued to all block devices in the system.

Is there is a way to get this information from gopsutil?

Thanks.

**Comment by Lomanic** [comment]
[disk.IOCounters](https://godoc.org/github.com/shirou/gopsutil/disk#IOCounters) reports disk io stats for disks, you will have to sum all the disks.

**Comment by MarcMagnin** [comment]
thanks! Can we get net IOs also.

**Comment by Lomanic** [comment]
[net.IOCounters](https://godoc.org/github.com/shirou/gopsutil/net#IOCounters)
