### ISSUE TITLE
Monitor Process Usage(watching changes on process)

### ISSUE THREAD

**Issue by safwanolaimat** [shirou/gopsutil#811]
How i can calculate process usage 
I have did this
```
cmd := exec.Command("someCommand")
cmd.Start()
p, _ := process.NewProcess(int32(cmd.Process.Pid))
fmt.Println(p.MemoryInfo())
fmt.Println(p.CPUPercent())
```

**Comment by Lomanic** [comment]
Simply call repeatedly over time these two functions until your command finishes.

**Comment by safwanolaimat** [comment]
@Lomanic 
I don't think this the right situation because at some time maybe the cpu load going and i will miss that if the check be after this happen its nanoseconds

**Comment by safwanolaimat** [comment]
@Lomanic this library uses /proc/${pid}/... for check
why not use fs to detect changes then send it back ?

**Comment by Lomanic** [comment]
>  why not use inotify to detect changes then send it back ?

Tracking process usage over time is not in the (already large) scope of this library. 

Also [inotify only partially supports procfs](https://stackoverflow.com/questions/13697615/inotify-add-watch-to-proc-folder) and is only available on Linux.
