### ISSUE TITLE
[disk], resolving symlinks on /dev/mapper not respecting paths when running in container

### ISSUE THREAD

**Issue by i-prudnikov** [shirou/gopsutil#817]
**Describe the bug**
This line is trying to evaluate link not respecting the case when running in container.
https://github.com/shirou/gopsutil/blob/master/disk/disk_linux.go#L304

**Expected behavior**
Disk statistics can be gathered when running in container and host fs is mounted inside container.

**To Reproduce**
https://github.com/influxdata/telegraf/issues/6898

**Environment (please complete the following information):**
 - [X] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
```
Linux <HOSTNAME> 4.4.0-154-generic #181-Ubuntu SMP Tue Jun 25 05:29:03 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
root@logs-02:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Possible solution:**
 Either to remove the entire block https://github.com/shirou/gopsutil/blob/master/disk/disk_linux.go#L303-L308 (this is preferable as symlink contains the name of LVM and it is not making sense to eval it to the name of device) or to change the above-mentioned line line to:
```go
devpath, err := filepath.EvalSymlinks(common.GetEnv("HOST_MOUNT_PREFIX","/",d.Device))
```

**Comment by Lomanic** [comment]
#819 was merged, closing (FYI,  @i-prudnikov, you can [set your commit message with the right keywords](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords) to automatically close the referenced issue)
