### ISSUE TITLE
What is the units for mem.VirtualMemory ?

### ISSUE THREAD

**Issue by safwanolaimat** [shirou/gopsutil#825]
I just want to ask what is the unit when i call ```mem.VirtualMemory()```

**Comment by shirou** [comment]
Could you tell me which platform/os/distribution are you using?

**Comment by safwanolaimat** [comment]
@shirou  linux/ubuntu

**Comment by shirou** [comment]
Then, it is `byte`.

**Comment by safwanolaimat** [comment]
@shirou thanks
