### ISSUE TITLE
What option can i get from PlatformInformationWithContext func' for platform variable?

### ISSUE THREAD

**Issue by mosheDO** [shirou/gopsutil#828]
Hi 

Is there an option to know all the possible results for platform variable, from this function and how it will look like, for example 
for "Windows 10 Enterprise”. I will get ‘Microsoft Windows 10 Enterprise’
has someone have a list of all the possibilities?

Regards, Moshe

**Comment by Lomanic** [comment]
* Windows: Reg key [`HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProductName`](https://github.com/shirou/gopsutil/blob/0d7dd621d2b5688be07c51c8ddba5c8e97b121f1/host/host_windows.go#L216-L223)
* Linux: [these cases are not exhaustive](https://github.com/shirou/gopsutil/blob/0d7dd621d2b5688be07c51c8ddba5c8e97b121f1/host/host_linux.go#L344-L365) but can give an idea
* [Darwin](https://github.com/shirou/gopsutil/blob/0d7dd621d2b5688be07c51c8ddba5c8e97b121f1/host/host_darwin.go#L187-L189)/[FreeBSD](https://github.com/shirou/gopsutil/blob/0d7dd621d2b5688be07c51c8ddba5c8e97b121f1/host/host_freebsd.go#L176)/[OpenBSD](https://github.com/shirou/gopsutil/blob/0d7dd621d2b5688be07c51c8ddba5c8e97b121f1/host/host_openbsd.go#L125-L127): `sysctl kern.ostype` lowercased
* Solaris: ["solaris"](https://github.com/shirou/gopsutil/blob/0d7dd621d2b5688be07c51c8ddba5c8e97b121f1/host/host_solaris.go#L252)

**Comment by Lomanic** [comment]
Just to answer explicitly your question, as these values are obtained dynamically at runtime, we can't have an exhaustive list, as it can differ from machine to machine.

**Comment by mosheDO** [comment]
@Lomanic Yes, I know that but I need to built a list that contains all the avaliable opthions because im running a software that dependes on your libarary, and I cant find any docs on Microsoft website or anyother website for that matter.

So as a last resort I thought asking here, but thanks for answer :)
