### ISSUE TITLE
macOS: Unable to build using Go Modules

### ISSUE THREAD

**Issue by paulquerna-okta** [shirou/gopsutil#832]
**Describe the bug**
- https://github.com/shirou/gopsutil/pull/800
- This PR added `host/include/smc.h` and `host/include/smc.c`.  These files are in the `include` sub-directory.  This directory includes no go files, so Go modules does not include them when `go mod vendor` is used.  Either the h & c files should be moved into the host directory, or a dummy go file should be added to `include`

**To Reproduce**
Go mod vendor gopsutil, then try to build:
```
# github.com/shirou/gopsutil/host
vendor/github.com/shirou/gopsutil/host/host_darwin_cgo.go:9:11: fatal error: 'include/smc.c' file not found
 #include "include/smc.c"
          ^~~~~~~~~~~~~~~
1 error generated.
```

**Environment (please complete the following information):**
 - [ ] Windows: [paste the result of `ver`]
 - [ ] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
 - [x] Mac OS: [paste the result of `sw_vers` and `uname -a`
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

**Comment by jetgeng** [comment]
i meet the same issue. 
sw_vers out is:

```bash
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76
```
uname -a is:

```
Darwin Gengs-MBP.geng 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

```

**Comment by axetroy** [comment]
Is there any solution for this now?

**Comment by mafredri** [comment]
@axetroy no good solution. But as a work-around you can manually copy the missing source/header files to your `vendor` folder (in the appropriate directory) and commit them. Note that `go mod` will get rid of them the next time it's run, so care must be taken.

The solution is to either add dummy `.go` files to the directories so that they will be considered as Go modules or to move them up a directory so they are accompanied by Go files.

**Comment by axetroy** [comment]
@mafredri Thx.
if this is a solution. why not send a PR and create an empty go file in the folder.

This issue should have stumped too many people

**Comment by Lomanic** [comment]
Weeks or months ago I tried to rename `include/smc.{c,h}` to `host_darwin.{c,h}`, as in the disk package, didn't commit this work anywhere unfortunately as this was not compiling anymore or (as I better remember it) had build warnings that I didn't understand how to remove. 

Will try the empty .go file workaround, to satisfy this (once again) broken go-mod.
