### ISSUE TITLE
undefined: "golang.org/x/sys/windows".EnumProcesses

### ISSUE THREAD

**Issue by sjt-xfwh** [shirou/gopsutil#835]
..\..\pkg\mod\github.com\shirou\gopsutil@v2.20.1+incompatible\process\process_windows.go:174:13: undefined: "golang.org/x/sys/windows".EnumProcesses
..\..\pkg\mod\github.com\shirou\gopsutil@v2.20.1+incompatible\process\process_windows.go:212:32: undefined: "golang.org/x/sys/windows".PROCESS_QUERY_LIMITED_INFORMATION
..\..\pkg\mod\github.com\shirou\gopsutil@v2.20.1+incompatible\process\process_windows.go:281:32: undefined: "golang.org/x/sys/windows".PROCESS_QUERY_LIMITED_INFORMATION
..\..\pkg\mod\github.com\shirou\gopsutil@v2.20.1+incompatible\process\process_windows.go:384:32: undefined: "golang.org/x/sys/windows".PROCESS_QUERY_LIMITED_INFORMATION
..\..\pkg\mod\github.com\shirou\gopsutil@v2.20.1+incompatible\process\process_windows.go:448:32: undefined: "golang.org/x/sys/windows".PROCESS_QUERY_LIMITED_INFORMATION
..\..\pkg\mod\github.com\shirou\gopsutil@v2.20.1+incompatible\process\process_windows.go:494:32: undefined: "golang.org/x/sys/windows".PROCESS_QUERY_LIMITED_INFORMATION
..\..\pkg\mod\github.com\shirou\gopsutil@v2.20.1+incompatible\process\process_windows.go:798:32: undefined: "golang.org/x/sys/windows".PROCESS_QUERY_LIMITED_INFORMATION
..\..\pkg\mod\github.com\shirou\gopsutil@v2.20.1+incompatible\process\process_windows.go:813:32: undefined: "golang.org/x/sys/windows".PROCESS_QUERY_LIMITED_INFORMATION
..\..\pkg\mod\github.com\shirou\gopsutil@v2.20.1+incompatible\process\process_windows.go:847:32: undefined: "golang.org/x/sys/windows".PROCESS_QUERY_LIMITED_INFORMATION

**Comment by sjt-xfwh** [comment]
on windows 10

**Comment by Lomanic** [comment]
Duplicate of #743.

**Comment by e9571** [comment]
update new golang.org\x\sys

**Comment by e9571** [comment]
https://github.com/golang/sys
