### ISSUE TITLE
telegraf monitoring disk abnormal 

### ISSUE THREAD

**Issue by fcddk** [shirou/gopsutil#851]
We monitored the ceph rbd mount disk through the telegraf disk input plugin, which caused the ceph rbd umount to be abnormal, and finally delete telegraf pod was just fine. telegraf uses this project code to monitor the disk.

version:
v2.17.13

**Comment by Lomanic** [comment]
(downstream issue https://github.com/influxdata/telegraf/issues/7121, can't understand why it wasn't linked here or there)

There is nothing we can do with a bug described with the  vague adjective of "abnormal" without any data point and without any description of how to reproduce it. How about following the issue template that already asks for this information?

This is not the telegraf project also and I shouldn't dig in all its code while you already found that it was getting its data from gopsutil.

As a sidenote, this is an antique version of gopsutil (and telegraf) released in… 2017. Try updating gopsutil (and/or telegraf) first.

Starting to get really tired of this kind of bug reports without any actionable information where I have to squeeze and extrapolate information out from them. Volunteer OSS maintainers time is not less precious than yours.
