### ISSUE TITLE
FreeBSD build failing

### ISSUE THREAD

**Issue by tmm1** [shirou/gopsutil#853]
```
[freebsd-x86_64] ../gopath/pkg/mod/github.com/shirou/gopsutil@v2.20.3-0.20200314133625-53cec6b37e6a+incompatible/disk/disk_freebsd.go:87:51: cannot use stat.Mntfromname[:] (type []byte) as type []int8 in argument to common.IntToString
[freebsd-x86_64] ../gopath/pkg/mod/github.com/shirou/gopsutil@v2.20.3-0.20200314133625-53cec6b37e6a+incompatible/disk/disk_freebsd.go:88:49: cannot use stat.Mntonname[:] (type []byte) as type []int8 in argument to common.IntToString
[freebsd-x86_64] ../gopath/pkg/mod/github.com/shirou/gopsutil@v2.20.3-0.20200314133625-53cec6b37e6a+incompatible/disk/disk_freebsd.go:89:50: cannot use stat.Fstypename[:] (type []byte) as type []int8 in argument to common.IntToString
[freebsd-x86_64] ../gopath/pkg/mod/github.com/shirou/gopsutil@v2.20.3-0.20200314133625-53cec6b37e6a+incompatible/disk/disk_freebsd.go:173:43: cannot use stat.Fstypename[:] (type []byte) as type []int8 in argument to common.IntToString
```

This just started out of nowhere. Not sure what changed. I think I upgraded x/sys

**Comment by tmm1** [comment]
Looks like there were some changes in x/sys/unix for freebsd in the last few days: https://github.com/golang/sys/commit/5766fd39f98ddd8d769ad4aedcee557dd28de90f#diff-2b37904226feaa1ac0c049523015d0bcL126-R128

**Comment by ianlancetaylor** [comment]
Please open an issue at https://golang.org/issue or discuss at https://golang.org/cl/223698.  Thanks.

**Comment by i0rek** [comment]
We just ran into this. It is not fixed in sys just yet. It could be fixed in gopsutil by casting, would you accept a PR for that?

**Comment by shirou** [comment]
Thanks. PR is always welcome!

**Comment by xxxserxxx** [comment]
@ncabatoff, @samsalisbury, @shirou, and @lomanic: pinning x/sys to v0.0.0-20200316230553-a7d97aace0b0 also works.  Specifically, Hashicorp, it lets you use the current version of `gopsutil`: you don't have to pin to a 2-y/o version.

For anyone finding this, in your project:
```
go get golang.org/x/sys@a7d97aace0b0
```
this should update your `go.mod` and allow you to build on FreeBSD.

**Comment by Lomanic** [comment]
You're exactly right @xxxserxxx, I tested this OK on FreeBSD 12, this is the last commit before x/sys breaking change, I'm preparing a PR to pin this with dep.

**Comment by tklauser** [comment]
FWIW, I've sent #895 which would allow building against `golang.org/x/sys@latest` on FreeBSD again.

**Comment by shirou** [comment]
#895 has been merged. Thank you!
