### ISSUE TITLE
Why the RAM size called "VirtualMemory" rather than "PhysicalMemory"?

### ISSUE THREAD

**Issue by ZHLHZHU** [shirou/gopsutil#858]
I found ```mem.VirtualMemory()``` always returns Ram size

**Comment by Lomanic** [comment]
This is inherited from the original library gopsutil is a port of https://psutil.readthedocs.io/en/latest/#psutil.virtual_memory

**Comment by ZHLHZHU** [comment]
> This is inherited from the original library gopsutil is a port of https://psutil.readthedocs.io/en/latest/#psutil.virtual_memory

thx.
