### ISSUE TITLE
FYI reading /proc/meminfo is expensive on linux

### ISSUE THREAD

**Issue by client9** [shirou/gopsutil#86]
FYI reading /proc/meminfo is expensive on linux.  By expensive I mean it takes significant CPU and on a heavily loaded machines, interferes with memory allocation.  

I found out about this from an engineer at a large company.  Looks like Linux just found out about it too:

http://lkml.iu.edu/hypermail/linux/kernel/1508.1/04141.html

I don't have a solution, but thought you might find this interesting.

**Comment by shirou** [comment]
Thank you for your information. It seems I have no solution about this kernel level. I think I have to wait until Linus or someone else solves.

**Comment by delandtj** [comment]
there is already a preliminary patch, nothing to do , reading /proc/meminfo
is going to be a lot less expensive . as of linux-4.3, probably

Jan

**Comment by shirou** [comment]
awesome. Then, I just wait.

Thank you for your information!
