### ISSUE TITLE
github.com/shirou/gopsutil/process error with /golang.org/x/sys/windows

### ISSUE THREAD

**Issue by LeoLee98** [shirou/gopsutil#873]

**Comment by LeoLee98** [comment]
undefined: "golang.org/x/sys/windows".EnumProcesses
undefined: "golang.org/x/sys/windows".PROCESS_QUERY_LIMITED_INFORMATION

**Comment by LeoLee98** [comment]
GOOS=windows

**Comment by shirou** [comment]
What golang version are you using? `EnumProcesses` is introduced from this [commit](https://github.com/golang/sys/commit/e8c54fb511f6a2d695a4403ae0dab1c05aef011a), so golang 1.14 is required for windows I think.

**Comment by Lomanic** [comment]
Duplicate of #743. See https://github.com/shirou/gopsutil/issues/743#issuecomment-519241791

The /x packages are unrelated to the Go version, they are just like other 3rd-party packages in this regard.
