### ISSUE TITLE
Disk Latency

### ISSUE THREAD

**Issue by AtakanColak** [shirou/gopsutil#875]
How could we calculate disk latency given the metrics in disk.IOCounters without using external tools?

**Comment by Lomanic** [comment]
Sorry for taking so long to reply, I think you are looking for iowait which is usually what is measured if one wants to see if a disk is struggling reading/writing. In gopsutil, this is [IOCountersStat.IoTime](https://godoc.org/github.com/shirou/gopsutil/disk#IOCountersStat)

[This is the following field on linux](https://github.com/shirou/gopsutil/blob/afe0c04c5d5a6cdf653565e4cbd2616657e3542c/disk/disk_linux.go#L412) ([Documentation/iostats.txt](https://www.kernel.org/doc/Documentation/iostats.txt)

```
Field 11 -- weighted # of milliseconds spent doing I/Os
    This field is incremented at each I/O start, I/O completion, I/O
    merge, or read of these stats by the number of I/Os in progress
    (field 9) times the number of milliseconds spent doing I/O since the
    last update of this field.  This can provide an easy measure of both
    I/O completion time and the backlog that may be accumulating.
```
