### ISSUE TITLE
load.Avg() doesn't work on Android

### ISSUE THREAD

**Issue by tmm1** [shirou/gopsutil#877]
Android is no longer allowing access to /proc:

```
$ cat /proc/loadavg
cat: /proc/loadavg: Permission denied
```

However busybox uptime still shows loadavg on Android, and it seems to use `sys/sysinfo.h`

```
$ uptime
 22:29:23 up  2:28,  load average: 2.38, 2.42, 2.40
```

https://github.com/mirror/busybox/blob/b097a84d62dcfcf201a695b54bcfafae70cac8a6/procps/uptime.c#L67

**Comment by tmm1** [comment]
It should be possible to invoke this syscall directly:

http://man7.org/linux/man-pages/man2/sysinfo.2.html

https://golang.org/pkg/syscall/#Sysinfo

Might be better to always do this on Linux? It is one syscall instead of multiple to open/read from /proc

**Comment by tmm1** [comment]
https://stackoverflow.com/a/12303849/332798 explains how to calculate the numbers from the sysinfo results

**Comment by Lomanic** [comment]
Thanks for your findings and opening the corresponding PR, also not later than yesterday I even commented that we should use sysinfo to get uptime here https://github.com/shirou/gopsutil/pull/857#issuecomment-629858607
