### ISSUE TITLE
cpu.CpuInfo() return empty data on Raspberry Pi

### ISSUE THREAD

**Issue by ranjib** [shirou/gopsutil#88]
cpu.CPUInfo() returns empty data on Raspberry Pi 2 (quadcore, ARM v7) running ubuntu 15.04 (kernel 3.17)  . This is due to /proc/cpuinfo being differently formatted. Following is an example:
```
processor : 0
model name  : ARMv7 Processor rev 5 (v7l)
BogoMIPS  : 57.60
Features  : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant : 0x0
CPU part  : 0xc07
CPU revision  : 5
```
CPU frequency cant be obtained from /proc/cpuinfo on ARM. There are two ways to get this data:
a) Invoke `lscpu`   and parse the resulting data
b) read /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq (one entry for each core)

I dont know whats the preferred way to implement this, @shirou if you can give some feedback, i'd be happy to implement this :-)
thanks for this awesome library

**Comment by shirou** [comment]
Thank you for the report!
I confirmed about could not get CPUInfo on ARM v7, ubuntu 15.04 by using https://www.scaleway.com/.

I prefer more widely used way. I think your a) `lscpu` approach is major than b). I would appreciate you if you make some PR. Thank you.

**Comment by ranjib** [comment]
@shirou awesome.
Question: lscpu output is fairly different than /proc/cpuinfo , 
 - it does not have things like flags, cpu family etc. 
- fields are inconsistent across arch. I'm posting examples of intel and arm `lscpu` data. e.g. CPU MHz has min & max fields on arm
- lscpu data is aggregate output. i.e. unlike cpuinfo which has one entry per core, lscpu is summary of all cpu

I am thinking of several things, but not sure which one is best. 
- introduce a separate struct to expose lscpu info (consumer codes need to be updated)
- interpret and build a array of CPUStats from lscpu data (not sure we'll get all logic right, or we;ll have all data.)
comments?
Intel lscpu output
```
  Architecture:          x86_64 
  CPU op-mode(s):        32-bit, 64-bit
  Byte Order:            Little Endian                                                                                                    
  CPU(s):                4                                                                                                                
  On-line CPU(s) list:   0-3                                                                                                              
  Thread(s) per core:    2                                                                                                                
  Core(s) per socket:    2                                                                                                                
  Socket(s):             1                                                                                                                
  NUMA node(s):          1
  Vendor ID:             GenuineIntel
  CPU family:            6
  Model:                 58
  Stepping:              9
  CPU MHz:               2932.519
  BogoMIPS:              4988.38
  Virtualization:        VT-x
  L1d cache:             32K                                                                                                              
  L1i cache:             32K                                                                                                              
  L2 cache:              256K                                                                                                             
  L3 cache:              4096K                                                                                                            
  NUMA node0 CPU(s):     0-3     
```
arm lscpu output
```
                                                                                                    
                                                                                                                                          
  Architecture:          armv7l                                                                                                           
  Byte Order:            Little Endian                                                                                                    
  CPU(s):                4                                                                                                                
  On-line CPU(s) list:   0-3                                                                                                              
  Thread(s) per core:    1                                                                                                                
  Core(s) per socket:    4                                                                                                                
  Socket(s):             1                                                                                                                
  Model name:            ARMv7 Processor rev 5 (v7l)                                                                                      
  CPU max MHz:           900.0000                                                                                                         
  CPU min MHz:           600.0000                   
```

**Comment by shirou** [comment]
@ranjib Thank you for the information. On my understanding, only ARM can not get information from `/proc/cpuinfo`. So I think how about separating into two files `cpu_linux.go` and `cpu_linux_arm.go` such as 

- for amd, get from `/proc/cpuinfo`
- for ARM, get from `lscpu`

Will that work?

**Comment by cbednarski** [comment]
@shirou That sounds good to me! I am not familiar with arm on linux outside of [Rasbpian](https://www.raspberrypi.org/downloads/raspbian/) but that's my primary use case for this feature. Let me know if you need help with this.
