### ISSUE TITLE
disk.IOCounters() fails with "The system cannot find the file specified." error on Windows Server 2012 R2

### ISSUE THREAD

**Issue by superscari** [shirou/gopsutil#883]
execution cause err: "The system cannot find the file specified."
i found it happens in method syscall_Syscall9, exactly, 
cgocall(asmstdcallAddr, unsafe.Pointer(c)) (line 214, runtime/syscall_windows.go),   
errno := asmcgocall(fn, arg)   (line 131,runtime/cgocall.go)

i can repeat it in different pc of win server 2012 r2, wish your help

**Comment by Lomanic** [comment]
I can only speculate this error comes from [this call to CreateFile](https://github.com/shirou/gopsutil/blob/42aec722ba8952b292752d508ad89da04d10887e/disk/disk_windows.go#L169),  but this error is explicitly handled [here](https://github.com/shirou/gopsutil/blob/42aec722ba8952b292752d508ad89da04d10887e/disk/disk_windows.go#L171) (message text is [here](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-)), try to find for which disk the error occurs (print `szDevice` value before this line), and for which win32 call the error is returned in disk.IOCounters.

That the error happens in syscall_Syscall9 doesn't give any information about the issue as it's a generic function to do syscalls used by anything that does syscalls (also line numbers in source files are different between Go versions, without the version number this is even less useful).

Please get back with your findings, thank you.

**Comment by superscari** [comment]
recent findings:
1. no relation with golang, i tried more than 3 versions
2. err number is 2, ERROR_FILE_NOT_FOUND
and i finally get the diskio successfully by accident，i do as follows:
i. get older source before the selected record(1c8ddacaf7) in red box, then  replace,exec. 
ii. replace the older with  recent source, then exec
iii. so i get the diskio infos
![image](https://user-images.githubusercontent.com/16182046/82971547-88493080-a005-11ea-9a82-24748a4491c2.png)
that is totally accident, and now i can integrate the code to get diskio.
that may help you to make it clear

**Comment by Lomanic** [comment]
Are you still able to reproduce the issue? I would have preferred you to follow what I suggested in my previous message, to see if a specific disk was failing, or all, to see from which win32 call the error was coming from.

Maybe you encountered what's suggested in [psutil docs](https://psutil.readthedocs.io/en/latest/#psutil.disk_io_counters)

> Note: on Windows `diskperf -y` command may need to be executed first otherwise this function won’t find any disk. 

In this case, we should probably emulate what this command does as explained [here](https://stackoverflow.com/questions/30450157/how-to-get-global-windows-i-o-statistics) (it adds a reg entry `EnableCounterForIoctl` set to  `1` in  `HKLM\SYSTEM\CurrentControlSet\Services\PartMgr`).

Are you able to reproduce the problem again after calling `diskperf.exe -N`?

**Comment by Lomanic** [comment]
Tested on a Win7 VM and it seems diskperf doesn't do anything above Win2000, according to its output at least (doesn't create this registry entry either). Would have appreciated you getting back to me @superscari.
