### ISSUE TITLE
Discussion: FreeBSD & Memory

### ISSUE THREAD

**Issue by xxxserxxx** [shirou/gopsutil#886]
Some platforms provide rich sensor data.  Darwin, for instance, reports (at least) 21 different thermal sensors.  FreeBSD does this with memory; `sysctl -s` reports just under 40 different memory metrics. Swap data on FreeBSD is unambiguous and easy; however, because of the wealth of metrics, it is difficult to determine which metric represents **Total**.  `gopsutil` has chosen to use `hw.physmem` for this.  I'd like to discuss this choice; in particular, I'd like to understand how this attribute was chosen, whether it's the right choice, and whether we have access to any FreeBSD kernel-level resources we can discuss this with.

The impetus for this question comes from xxxserxxx/gotop#14, which was cloned from Caleb's cjbassi/gotop#88 (all cloned tickets lost original author information in the clone, so old tickets look like I'm talking to myself). After investigating this for a few hours, and testing in a FreeBSD VM, I determined:

1. Swap data is accurately reported
2. Few tools even try to simplify memory reporting
3. Those that do don't choose the same simplifications gopsutil does

The last point causes trouble as evidenced by xxxserxxx/gotop#14, where somebody sees that gotop's numbers don't match their other, more popular, and older tool[1], and so they don't trust gotop and file a bug.  While there's only one active issue open, I've had people comment on "bad values" from gotop on FreeBSD in email, comments on other tickets, and chat.

Given the complexity of how to determine memory use (Linux has this, only much less confusingly), I don't believe that there's a perfect choice.  However, `hw.physmem` doesn't seem to be a *common* choice in FreeBSD tools, so I'd like to either discuss using a different metric (which doesn't require a change to gopsutil, but it might be beneficial to change it there), or have a FreeBSD Authority weigh in that it is, indeed, the best metric for a summary like **Total**.  The latter would be ideal, and if that's the case, I can more easily appeal to authority in responses to complaints about this.

[1] I would also like to throw in here that `top` on FreeBSD reports entirely wrong information for swap space, and that it's other numbers for memory are a bit off the authoritative tools `sysctl` and `vmstat`, so I'm suspicious about bugs that use it as a baseline for correctness.

**Comment by Lomanic** [comment]
The answer is the same as for #732 or  #690: gopsutil is a port of psutil, not (h)top  & co, we aim to return the same values as psutil and follow it as a reference (though we sometimes diverge from it and have a wider API as things are missing in Go stdlib compared to Python's for example). `hw.physmem` is used for the `total` in https://github.com/giampaolo/psutil/blob/5e47e0bcba7585909a11e9c7424e864fc26a7fd2/psutil/arch/freebsd/specific.c#L415 for FreeBSD.

[psutil.virtual_memory() documentation](https://psutil.readthedocs.io/en/latest/#psutil.virtual_memory) says that `total` is _total physical memory (exclusive swap)_. We should probably make it clear also in [gopsutil's docs](https://godoc.org/github.com/shirou/gopsutil/mem#VirtualMemoryStat).
