### ISSUE TITLE
Antivirus software detection when using newer version of gopsutil package (Windows)

### ISSUE THREAD

**Issue by nikita-vanyasin** [shirou/gopsutil#892]
Hi!

We are developing a [monitoring agent](https://github.com/cloudradar-monitoring/cagent) which extensively uses gopsutil library.
Everything worked just fine for almost two years.

But this month I've upgraded gopsutil package from v2.19.01 to v2.20.5 and it resulted in many false-positive detections by antivirus software.
This is a serious problem for our end-users.

Interestingly, .exe binaries are never reported. Only the MSI-packed files are reported. I guess antivirus software has different algorithms when checking MSI.

VirusTotal scan results:
Our product ([v1.9.2](https://github.com/cloudradar-monitoring/cagent/releases/tag/1.9.2)) built with gopsutil **v2.19.01**:
https://www.virustotal.com/gui/file/e6751343713932b4e26f3b10d9987b7cf7b547a8cc000e6ca20182e0513109ae/detection

Our product ([v1.9.4](https://github.com/cloudradar-monitoring/cagent/releases/tag/1.9.4)) built with gopsutil **v2.20.5**:
https://www.virustotal.com/gui/file/796b5e0a228c3346a02e4a666037d9d5fa300c181d013360d8bebbba4b0722c6/detection

The only change between two versions is gopsutil library upgrade. See the diff: https://github.com/cloudradar-monitoring/cagent/compare/1.9.2...1.9.4

I understand that false-positives should not be a concern of gopsutil development team, but the problem stops us from upgrading to a newer version.

We've already sent some false-positive reports to BitDefender and Microsoft Defender support, but not sure if this will help.

**Comment by Lomanic** [comment]
You're right that we can't do much. Even more if it's the MSI that's reported, not the .exe where gopsutil is included. I was suspecting that it comes from #862, but gopsutil's Process.Cmdline() is not used on Windows in cagent as you use [your own implementation](https://github.com/cloudradar-monitoring/cagent/blob/68da99132d59c7bd832c26ab21b47239774d51aa/pkg/winapi/facade.go#L28), which is used for a moment (I can add that you could reduce your Windows-specific code as gopsutil is not using slow WMI calls anymore for process.Cmdline and disk.IOCounters nowadays).
