### ISSUE TITLE
Used memory on Linux includes Slab

### ISSUE THREAD

**Issue by james-bebbington** [shirou/gopsutil#899]
The `mem_linux` code currently calculates used memory as: `Total - Free - Buffers - Cached`: https://github.com/shirou/gopsutil/blob/master/mem/mem_linux.go#L170

I think this should instead be `Total - Free - Buffers - Cached - Slab` as per https://access.redhat.com/solutions/406773

I would make a PR but I'm not 100% sure (and this would be a breaking change) so would be great if someone could confirm first

**Comment by mznet** [comment]
@james-bebbington The document you mentioned says `Used Memory` can be calculated as `Total - Free - Buffers - Cached - Slab`, but this calculation seems not to be exact IMHO.

The exact formula to get `Used Memory` by Free command is `Total - Free - Buffers - Cached`. For more details, refer to [the link](https://gitlab.com/procps-ng/procps/-/blob/master/proc/sysinfo.c#L789).

[The comment](https://access.redhat.com/solutions/406773#comment-1847201) at the bottom of the RedHat document, is pointing out that.

**Comment by james-bebbington** [comment]
As per the comment you linked it would probably make the most sense to subtract `SReclaimable`. But I agree we should replicate what the Free command does (also this matches psutil). "Available" is probably a more useful stat to look at anyway for people who want an accurate representation of "used" memory.

Thanks for the info!
