### ISSUE TITLE
In linux cpu iowait should be treated like idle time. 

### ISSUE THREAD

**Issue by msays2000** [shirou/gopsutil#902]
https://github.com/shirou/gopsutil/blob/6d64cd6d43e7927e70891507b795c176a60caf37/cpu/cpu.go#L99

If iowait implies cpu is technically free to do any other ready work, then we should treat it as idle time. 

In python psutil and in htop it is treated as idle time. 

https://github.com/giampaolo/psutil/blob/550c825c95b537e9c3fee8452e5e1cd4fe5c704a/psutil/__init__.py#L1664-L1677

https://github.com/torvalds/linux/blob/447976ef4fd09b1be88b316d1a81553f1aa7cd07/kernel/sched/cputime.c#L244-L253

**Comment by msays2000** [comment]
sample PR: https://github.com/shirou/gopsutil/pull/903

**Comment by Grandmother** [comment]
Fixed in this commit: https://github.com/shirou/gopsutil/commit/d1cc7d2125cdccc309c104917b221f08ee0fa731

**Comment by Grandmother** [comment]
@shirou, I can't close the issue, could you please?
