### ISSUE TITLE
build broken on freebsd due to invalid cast in disk/getFsType()

### ISSUE THREAD

**Issue by knz** [shirou/gopsutil#906]
**Describe the bug**

Build fails:

```
/github.com/shirou/gopsutil/disk/disk_freebsd.go:195:43: cannot use stat.Fstypename[:] (type []byte) as type []int8 in argument to common.IntToString
```

**To Reproduce**

build on FreeBSD

**Expected behavior**

build succeeds

**Environment (please complete the following information):**

FreeBSD 13-CURRENT on amd64

**Additional context**

The following diff fixes the bug and keeps the functionality:

```diff
@@ -192,5 +193,5 @@ func parseDevstat(buf []byte) (Devstat, error) {
 }

 func getFsType(stat unix.Statfs_t) string {
-       return common.IntToString(stat.Fstypename[:])
+       return string(stat.Fstypename[:])
 }
```

**Comment by Lomanic** [comment]
Upgrade `golang.org/x/sys`, see #853 for context.
