### ISSUE TITLE
Add host file descriptors info (FDTotal, FDUsed, FDUsedPercent)

### ISSUE THREAD

**Issue by flaviostutz** [shirou/gopsutil#907]
**Is your feature request related to a problem? Please describe.**
I am creating a performance evaluator that needs to know total/available file handles on the system

**Describe the solution you'd like**
Create an API to get Allocated and Max File handles

**Describe alternatives you've considered**
Read /proc/sys/fs/nr_open and /proc/sys/fs/file-nr directly on my program

**Additional context**
Don't know if this should be added to MiscStats or as a new Stats in disk. Any tips?

**Comment by Lomanic** [comment]
gopsutil already has a too large API for its small manpower. As I wrote in https://github.com/shirou/gopsutil/pull/934#issuecomment-684845751, its value resides in providing the same API in a cross-platform way.

I'm not fond of this feature request as it's probably linux-only and yet another API to maintain.

**Comment by shirou** [comment]
I agree to @Lomanic . Since gopsutils is a golang port of psutil, and want to be a cross-platform. At the beginning of gopsutil development, I have added Linux specific API but now I don't want to add Linux specific APIs any more. (I am thinking deleting Docker API from v3)

**Comment by Lomanic** [comment]
Closing, as discussed.
