### ISSUE TITLE
v2.20.7 Release date

### ISSUE THREAD

**Issue by kunzimariano** [shirou/gopsutil#914]
**Is your feature request related to a problem? Please describe.**

Would it be possible to get an estimated date for the v2.20.7 release? And will [process.Groups()](https://github.com/shirou/gopsutil/blob/master/process/process.go#L318) be part of it?

**Additional context**
I'm trying to decide if I can wait for the release, or I need to use a workaround for the time being.

Thanks!

**Comment by Lomanic** [comment]
Thanks for the reminder, I've just pushed a new tag. [v2.20.7](https://github.com/Lomanic/gopsutil/releases/tag/v2.20.7)

cc @shirou as you always do it usually

**Comment by Lomanic** [comment]
process.Groups() is included https://github.com/shirou/gopsutil/blob/v2.20.7/process/process.go#L318

**Comment by shirou** [comment]
sorry and thank you! I want to wait golang 1.15 release a few days to #909, but I forget completely... as @Lomanic opened #915, I will try to set github-actions to automate. Thank you!

**Comment by kunzimariano** [comment]
Thanks for the quick reply!
