### ISSUE TITLE
github.com/shirou/gopsutil/host/host_darwin_cgo.go:9:11: fatal error: 'include/smc.c' file not found

### ISSUE THREAD

**Issue by php2go** [shirou/gopsutil#919]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
```go
// #cgo LDFLAGS: -framework IOKit
// #include <stdio.h>
// #include <string.h>
// #include "include/smc.c"
```

**Expected behavior**
# github.com/shirou/gopsutil/host
vendor/github.com/shirou/gopsutil/host/host_darwin_cgo.go:9:11: fatal error: 'include/smc.c' file not found
 #include "include/smc.c"
          ^~~~~~~~~~~~~~~
1 error generated.
**Environment (please complete the following information):**
 - [ ] Mac OS: [Darwin bogon 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

**Additional context**
go 1.15

**Comment by Lomanic** [comment]
Upgrade gopsutil, this is fixed since https://github.com/shirou/gopsutil/pull/889
