### ISSUE TITLE
do we use all exported methods?

### ISSUE THREAD

**Issue by MalloZup** [shirou/gopsutil#927]
Hi all first thx for this cool project! :rocket: 

I was wondering, personally I think that some methods shouldn't be public exported.
For example:
https://github.com/shirou/gopsutil/blob/7e94bb8bcde053b6d6c98bda5145e9742c913c39/process/process_linux.go#L85

is highly used internally and should be not exported. 
Thoughts on this?

**Comment by MalloZup** [comment]
closing for moment since I think is ok anyways!

**Comment by Lomanic** [comment]
We export too many internals but this function is not one of these.
