### ISSUE TITLE
[question] Why can't I use p.ModelName?

### ISSUE THREAD

**Issue by viktor02** [shirou/gopsutil#929]
You have similar code as an example that shows access to memory information. I tried to make access to the host and the processor by analogy, but it did not work with the processor and I cannot understand the error. What am I doing wrong?
```
package main

import (
	"fmt"
	"github.com/shirou/gopsutil/cpu"
)

func main() {
	p, _ := cpu.Info()
	fmt.Println(p.ModelName)
}
```
```
.\test.go:11:15: p.ModelName undefined (type []cpu.InfoStat has no field or method ModelName)
```

**Comment by Lomanic** [comment]
[`cpu.Info()`](https://godoc.org/github.com/shirou/gopsutil/cpu#Info) returns a slice of `cpu.InfoStat`s, so you have to iterate over them or use `p[0].ModelName` in your test for example.

**Comment by viktor02** [comment]
Thank you!
