### ISSUE TITLE
Enhancement: Avg req size for disk io

### ISSUE THREAD

**Issue by cholcombe973** [shirou/gopsutil#93]
I don't know how hard this would be to add but it would be really nice if the disk plugin exported avg  request size.  It would really help discern if you have sequential or random IO going on.  I could take a stab at making this work but I don't know any Go so the code might be horrible

**Comment by shirou** [comment]
Interesting. But, can `Avg req size` be calculated from Read/Write Count and Read/Write Bytes?
If so, I think adding new field is not required, I think.

**Comment by cholcombe973** [comment]
Let me read the iostat.c source code and get back to you.  I *think* you
can but I'm not positive.

**Comment by cholcombe973** [comment]
Ok so according to the iostat source code field #10 in https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats is how you calculate average request size.  This is for Linux.  I don't know if this works for any other OS unfortunately.

**Comment by shirou** [comment]
Thank you for confirming. If other platform can not calculate, some other good people will open a issue.

I close this issue. If you have any question or comment, feel free to reopen or open a new issue. Thank you.
