### ISSUE TITLE
docker.GetDockerIDList() exit status 1

### ISSUE THREAD

**Issue by xiaokugua250** [shirou/gopsutil#937]
**Describe the bug**
 dockerinfo.DockerIds,err= **docker.GetDockerIDList()**
 dockerinfo.DockerStats,err= **docker.GetDockerStat()**
	
return  **exit status 1** 
**To Reproduce**
```go
// paste example code reproducing the bug you are reporting

func TestSysAdvancedDockerInfo(t *testing.T) {
	list, err := docker.GetDockerIDList()
	if err != nil {
		fmt.Println(err)
	}
	for _, item := range list {
		fmt.Println(item)
	}
	/*docker,err := SysAdvancedDockerInfo()
	if err!= nil{
		fmt.Println(err)
	}
	fmt.Printf("%#v",docker)*/
}

====>
=== RUN   TestSysAdvancedDockerInfo
exit status 1
--- PASS: TestSysAdvancedDockerInfo (0.05s)
PASS
```

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Environment (please complete the following information):**
 - [ ] Windows: [paste the result of `ver`]
 - [x] Linux:   

```NAME="Ubuntu"  
VERSION="20.04 LTS (Focal Fossa)"   
ID=ubuntu  
ID_LIKE=debian  
PRETTY_NAME="Ubuntu 20.04 LTS"  
VERSION_ID="20.04"  
HOME_URL="https://www.ubuntu.com/"  
SUPPORT_URL="https://help.ubuntu.com/"  
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"  
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"  
VERSION_CODENAME=focal  
UBUNTU_CODENAME=focal  
```
 `Linux ubuntu 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - [ ] Mac OS: [paste the result of `sw_vers` and `uname -a`
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

**Additional context**
[Cross-compiling? Paste the command you are using to cross-compile and the result of the corresponding `go env`]

**Comment by Lomanic** [comment]
What is the result of `docker ps -q --no-trunc` ([the command that gets executed in docker.GetDockerIDList()](https://github.com/shirou/gopsutil/blob/4cfc60d68bd6d1573ea5453e14ba35d2564b7794/docker/docker_linux.go#L71))?

**Comment by xiaokugua250** [comment]
nothing，its a new machine
![image](https://user-images.githubusercontent.com/4617763/92422543-5ae95280-f1b0-11ea-9a06-dbf514e6e5bf.png)
![image](https://user-images.githubusercontent.com/4617763/92422598-853b1000-f1b0-11ea-9a22-dbe5ff328b9a.png)

**Comment by shirou** [comment]
Could not reproduce on my machine. what is the result of `echo $?` after `docker ps` ?

```
% docker ps -q --no-trunc
% echo $?
```

**Comment by Lomanic** [comment]
Impossible to reproduce for us, looks like an issue on your install @xiaokugua250 as `docker ps -q --no-trunc` returns a non-zero exit code.
