### ISSUE TITLE
Using gopsutil in a container

### ISSUE THREAD

**Issue by jchauncey** [shirou/gopsutil#94]
So there is a default /proc file system within a container that is used for container level pids etc... It would be nice to override where gopsutil looks so you could bind mount the host /proc file system into the container.

**Comment by shirou** [comment]
I think Docker can override `/proc` in a container such as `-v /proc/:/proc/:ro`. If my understanding is true, there are no needs to change proc filesystem path in gopsutil.

**Comment by shirou** [comment]
Hmm. When I run docker with `-v /proc/:/proc/:ro` then, 
`cannot be mounted because it is located inside "/proc"`.
So your PR is needed.

**Comment by jchauncey** [comment]
I think this used to be the case but newer docker clients don't allow it
