### ISSUE TITLE
Is Process.CPUPercent available on Linux? 

### ISSUE THREAD

**Issue by brunoqc** [shirou/gopsutil#95]
There's no "x" in the Linux column for process cpu_percent in the table on https://github.com/shirou/gopsutil#process-class but [Process.CPUPercent](https://godoc.org/github.com/shirou/gopsutil/process#Process.CPUPercent) seems to work on Linux.

Maybe the table is not up-to-date.

**Comment by shirou** [comment]
Thank you. I fixed up now.
