### ISSUE TITLE
MacOS 10.15.7 disk.Partitions() is failing

### ISSUE THREAD

**Issue by audiolion** [shirou/gopsutil#958]
**Describe the bug**
When compiling on MacOS 10.15.7, specifically the [Github Actions virtual environment for MacOS](https://github.com/actions/virtual-environments/releases/tag/macos-10.15%2F20201003.1) released yesterday, gopsutil is no longer compiling:
```
# github.com/shirou/gopsutil/disk
Error: ../../../go/pkg/mod/github.com/shirou/gopsutil@v2.20.8+incompatible/disk/disk_darwin.go:67:51: cannot use stat.Mntfromname[:] (type []byte) as type []int8 in argument to common.IntToString
Error: ../../../go/pkg/mod/github.com/shirou/gopsutil@v2.20.8+incompatible/disk/disk_darwin.go:68:49: cannot use stat.Mntonname[:] (type []byte) as type []int8 in argument to common.IntToString
Error: ../../../go/pkg/mod/github.com/shirou/gopsutil@v2.20.8+incompatible/disk/disk_darwin.go:69:50: cannot use stat.Fstypename[:] (type []byte) as type []int8 in argument to common.IntToString
Error: ../../../go/pkg/mod/github.com/shirou/gopsutil@v2.20.8+incompatible/disk/disk_darwin.go:85:43: cannot use stat.Fstypename[:] (type []byte) as type []int8 in argument to common.IntToString
```

The code this references is https://github.com/shirou/gopsutil/blame/master/disk/disk_darwin.go#L67 and was last touched 6 years ago.

**Environment (please complete the following information):**
 - [ ] Windows: [paste the result of `ver`]
 - [ ] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
 - [x ] Mac OS: System Version: macOS 10.15.7 (19H2)
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

**Comment by chrisamti** [comment]
go the same problem. it seems since 
https://github.com/golang/sys/commit/cec0259cc958035adfa20ac405303250390cb449
it's broken.

**Comment by tonyking97** [comment]
Any update on this issue?

**Comment by chrisamti** [comment]
A workaround that worked me: 

inside your project 
```go get -u golang.org/x/sys@release-branch.go1.13```

Maybe you first need to remove old org/x/sys package from you env:

```go clean -i -n golang.org/x/sys```

followed by a

```go get -u golang.org/x/sys@release-branch.go1.13```
