### ISSUE TITLE
在linux上试了一下，发现此模块输出的磁盘空间和内存大小跟free、df命令的输出有误差

### ISSUE THREAD

**Issue by YJiWei** [shirou/gopsutil#959]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
```go
// paste example code reproducing the bug you are reporting
```

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Environment (please complete the following information):**
 - [ ] Windows: [paste the result of `ver`]

 - [ ] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
[root@test:~/myscripts/go]$ go run check.go 
内存共计：3G, 剩余：1G, 使用率：26.64%
/共计：39G, 已用：19G, 剩余：20G, 使用率：48.69%
/opt共计：70G, 已用：7G, 剩余：64G, 使用率：9.80%
[root@test:~/myscripts/go]$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.9G        1.0G        1.1G         41M        1.8G        2.5G
Swap:          8.0G         26M        8.0G
[root@test:~/myscripts/go]$ df -h
Filesystem               Size  Used Avail Use% Mounted on
devtmpfs                 2.0G     0  2.0G   0% /dev
tmpfs                    2.0G     0  2.0G   0% /dev/shm
tmpfs                    2.0G   41M  1.9G   3% /run
tmpfs                    2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/sda3                 40G   19G   20G  49% /
/dev/sda2                488M  113M  340M  25% /boot
/dev/mapper/centos-data   71G  6.6G   61G  10% /opt
tmpfs                    396M     0  396M   0% /run/user/0
[root@test:~/myscripts/go]$ uname -a 
Linux test 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

 - [ ] Mac OS: [paste the result of `sw_vers` and `uname -a`
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]

**Additional context**
[Cross-compiling? Paste the command you are using to cross-compile and the result of the corresponding `go env`]

**Comment by shirou** [comment]
English please
