### ISSUE TITLE
Get Network interface stats using IOCountersStat

### ISSUE THREAD

**Issue by sivarajendranaidu** [shirou/gopsutil#960]
**Is your feature request related to a problem? Please describe.**
Looking to get Network interface stats which has fields described in IOCountersStat.
Is this featured supported ?
I don't see the external interface for the same.
Please provide your inputs

**Comment by Lomanic** [comment]
I don't understand your question, [`net.IOCounters`](https://godoc.org/github.com/shirou/gopsutil/net#IOCounters) returns a slice of  [`net.IOCountersStat`](https://godoc.org/github.com/shirou/gopsutil/net#IOCountersStat)s.
