### ISSUE TITLE
windows load avg() not implemented yet

### ISSUE THREAD

**Issue by sanxun0325** [shirou/gopsutil#973]
**Describe the bug**

windows load avg() not implemented yet,have a plan to make it happen?

**To Reproduce**

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Environment (please complete the following information):**
 - Windows: 

**Additional context**

**Comment by shirou** [comment]
PR is always welcome!

**Comment by AtakanColak** [comment]
[Related psutil doc](https://psutil.readthedocs.io/en/latest/#psutil.getloadavg)
