### ISSUE TITLE
error: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]

### ISSUE THREAD

**Issue by airbnb-gps** [shirou/gopsutil#976]
If you attempt to build this package on macOS using LLVM/Clang 11.0 (the upstream version number, not Apple's version numbers, which are different), you get the following error:

```
cpu/cpu_darwin_cgo.go:13:5: error: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if TARGET_OS_MAC
    ^
1 error generated.
```

This is because LLVM/Clang 11 automatically adds `-Werror,-Wundef-prefix=TARGET_OS_` as default compiler arguments and apparently `TARGET_OS_MAC` isn't defined in this compilation environment.

The reason it is not defined, I'm not sure. `TargetConditionals.h` defines this symbol and unless I'm looking at the wrong SDK, I think `TARGET_OS_MAC` should always be defined when building on/for macOS.

I can work around this by adding `#cgo CFLAGS: -Wno-undef-prefix` or `#include <TargetConditionals.h>` to the failing `import "C"` comment. The latter is likely more robust and seemingly indicates that `TargetConditions.h` isn't being included by another `#include` in this block.

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H2
```

I'm also building with the `macosx10.15` SDK.

**Comment by Lomanic** [comment]
I fear I won't be able to help as the following works `CC=clang CXX=clang++ go build github.com/shirou/gopsutil/...` with `Apple LLVM version 9.0.0 (clang-900.0.39.2)` (`clang --version | head -1`) on MacOS 10.12 and I won't be able to install xcode as it needs an Apple ID account.

I will maybe try to install a newer version with [homebrew](https://brew.sh) ([following this article](https://embeddedartistry.com/blog/2017/02/24/installing-llvm-clang-on-osx/)), hoping it's not too different from xcode's version.

> I can work around this by adding `#cgo CFLAGS: -Wno-undef-prefix`

Without  touching gopsutil code you could also set the `CGO_CFLAGS` env variable to this value.

**Comment by tlightsky** [comment]
also meet this problem in `clang version 11.0.0`

**Comment by Lomanic** [comment]
@tlightsky did you try calling `go build` with `CGO_CFLAGS=-Wno-undef-prefix`?

**Comment by nehaljwani** [comment]
This is the relevant commit in clang: https://github.com/llvm/llvm-project/commit/f47b8851318d5ec2fa1e7867f3fdb86101cdc1da

**Comment by tlightsky** [comment]
> @tlightsky did you try calling `go build` with `CGO_CFLAGS=-Wno-undef-prefix`?

yeah, seems not helping,
after failed with llvm@9, 
I removed all my llvm and it works now

**Comment by bobrik** [comment]
#1042 addresses the issue with @airbnb-gps's suggestion.

**Comment by towben** [comment]
sudo go get github.com/shirou/gopsutil

**Comment by DerekStrickland** [comment]
I recently ran into a very similar issue BigSur 11.6.1 where building failed with the following

```shell
# github.com/shirou/gopsutil/v3/mem
In file included from _cgo_export.c:3:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdlib.h:181:5: warning: 'TARGET_OS_IPHONE' is not defined, evaluates to 0 [-Wundef-prefix=TARGET_OS_]
```

I ended up having to add both `CGO_CFLAGS=-Who-undef-prefix` and `SDKROOT`  like so.

```shell
CGO_CFLAGS=-Wno-undef-prefix \
SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk \
CGO_ENABLED=1 \
GOOS=darwin \
GOARCH=amd64 \
CC=clang \
go build 
```

I'm just leaving this comment as a resource for the community.  No request for action from the repo maintainers.

**Comment by turion** [comment]
Is this going to be backported to 21.1? I.e. are the vendored versions bumped there?

**Comment by shawn888** [comment]
May be related to CGO. For a temporary solution, use the following instructions before building the project.
`go env -w CGO_ENABLED="0"`

**Comment by isheraz** [comment]
> @tlightsky did you try calling `go build` with `CGO_CFLAGS=-Wno-undef-prefix`?

worked on Mac - M1 2020
